/**
 * /api/cron/cambridge-test
 * Runs 400 Cambridge O/A Level questions through Starky and stores results.
 * Triggered manually or via cron. Results stored in Supabase.
 * This creates verifiable evidence: "Starky answered 400 Cambridge questions."
 */

import Anthropic from '@anthropic-ai/sdk';
import { getSupabase } from '../../../utils/supabase';

export const config = { api: { bodyParser: true }, maxDuration: 300 };

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY, timeout: 30000 });

// 400 Cambridge questions across 10 subjects, O Level and A Level
const QUESTIONS = [
  // ═══ BIOLOGY (40 questions) ═══
  ...[
    'Define osmosis and explain why it is important in plant cells. [3]',
    'Describe the structure of DNA and explain how it carries genetic information. [4]',
    'Explain the process of photosynthesis including the word equation. [3]',
    'Compare mitosis and meiosis in terms of purpose and outcome. [4]',
    'Explain how antibodies help defend the body against disease. [3]',
    'Describe the structure and function of the heart. [4]',
    'Explain the greenhouse effect and its impact on global warming. [3]',
    'What is natural selection? Explain with an example. [4]',
    'Describe how enzymes work using the lock and key model. [3]',
    'Explain the difference between aerobic and anaerobic respiration. [3]',
    'Describe the nitrogen cycle. [4]',
    'Explain how the kidney produces urine. [4]',
    'What are the differences between arteries, veins and capillaries? [3]',
    'Describe the stages of the menstrual cycle. [4]',
    'Explain what happens during gaseous exchange in the alveoli. [3]',
    'Describe the structure and function of a neurone. [3]',
    'Explain how insulin regulates blood glucose levels. [3]',
    'What is genetic engineering? Give one advantage and one disadvantage. [3]',
    'Describe the carbon cycle. [4]',
    'Explain the role of stomata in transpiration. [3]',
    'Describe the process of protein synthesis. [4]',
    'Explain the concept of homeostasis with an example. [3]',
    'What are the effects of smoking on the lungs? [3]',
    'Describe how a reflex arc works. [4]',
    'Explain the importance of water in biological systems. [3]',
    'What is eutrophication? Describe its causes and effects. [4]',
    'Explain how vaccination prevents disease. [3]',
    'Describe the process of digestion in the human alimentary canal. [4]',
    'What is selective breeding? How does it differ from natural selection? [3]',
    'Explain the role of hormones in plant growth. [3]',
    'A Level: Explain the light-dependent reactions of photosynthesis. [6]',
    'A Level: Describe the structure of ATP and its role in metabolism. [4]',
    'A Level: Explain the process of transcription and translation. [6]',
    'A Level: Describe the immune response including B and T lymphocytes. [6]',
    'A Level: Explain the Hardy-Weinberg principle and its assumptions. [4]',
    'A Level: Describe the role of the liver in metabolism. [6]',
    'A Level: Explain the mechanism of muscle contraction. [6]',
    'A Level: Describe genetic drift and its effect on small populations. [4]',
    'A Level: Explain the role of the nephron in osmoregulation. [6]',
    'A Level: Describe the Calvin cycle in detail. [6]',
  ].map(q => ({ subject: 'Biology', question: q })),

  // ═══ CHEMISTRY (40 questions) ═══
  ...[
    'Define an isotope and give an example. [2]',
    'Explain ionic bonding using sodium chloride as an example. [3]',
    'Describe the test for carbon dioxide gas. [2]',
    'Balance this equation: Fe + O2 → Fe2O3 [2]',
    'Explain why metals are good conductors of electricity. [2]',
    'Describe the differences between exothermic and endothermic reactions. [3]',
    'What is the pH scale? What does a pH of 3 indicate? [2]',
    'Explain how electrolysis of brine works. [4]',
    'Describe the properties of transition metals. [3]',
    'Explain what happens when an acid reacts with a metal carbonate. [3]',
    'What is a catalyst? How does it affect the rate of reaction? [3]',
    'Describe the fractional distillation of crude oil. [4]',
    'Explain covalent bonding using water as an example. [3]',
    'What is an alloy? Why are alloys harder than pure metals? [3]',
    'Describe the test for hydrogen gas. [2]',
    'Explain the reactivity series of metals. [3]',
    'What is cracking? Why is it important? [3]',
    'Describe how to prepare a pure dry sample of copper sulfate. [4]',
    'Explain the difference between complete and incomplete combustion. [3]',
    'What are polymers? Give two examples. [3]',
    'Describe the structure of diamond and graphite. [4]',
    'Explain Le Chatelier\'s principle with an example. [3]',
    'What is the mole concept? Calculate the number of moles in 36g of water. [3]',
    'Describe how the Haber process works. [4]',
    'Explain oxidation and reduction in terms of electron transfer. [3]',
    'What are homologous series? Describe the alkane series. [3]',
    'Describe the process of rusting and how it can be prevented. [3]',
    'Explain metallic bonding. [3]',
    'What is an endothermic reaction? Give an example. [2]',
    'Describe how chromatography can be used to separate dyes. [3]',
    'A Level: Explain the concept of enthalpy change and Hess\'s Law. [6]',
    'A Level: Describe the mechanism of nucleophilic substitution (SN2). [4]',
    'A Level: Explain how a buffer solution works. [4]',
    'A Level: Describe the Born-Haber cycle for NaCl. [6]',
    'A Level: Explain the concept of electronegativity and bond polarity. [4]',
    'A Level: Describe the chemistry of transition metal complexes. [6]',
    'A Level: Explain the Boltzmann distribution and its relevance to catalysis. [4]',
    'A Level: Describe the reactions of carboxylic acids. [4]',
    'A Level: Explain redox titrations using potassium manganate(VII). [4]',
    'A Level: Describe the structure and reactions of benzene. [6]',
  ].map(q => ({ subject: 'Chemistry', question: q })),

  // ═══ PHYSICS (40 questions) ═══
  ...[
    'State Newton\'s three laws of motion. [3]',
    'Calculate the speed of a car that travels 150m in 10 seconds. [2]',
    'Explain the difference between mass and weight. [2]',
    'Describe how a transformer works. [3]',
    'What is the principle of conservation of energy? [2]',
    'Explain how a lens forms a real image. [3]',
    'Calculate the resistance when V=12V and I=3A. [2]',
    'Describe the electromagnetic spectrum in order of wavelength. [3]',
    'Explain what causes a change of state. [3]',
    'What is the difference between speed and velocity? [2]',
    'Describe an experiment to determine the density of an irregular solid. [4]',
    'Explain how a nuclear power station generates electricity. [4]',
    'Calculate the work done when a force of 50N moves an object 8m. [2]',
    'Describe the properties of alpha, beta, and gamma radiation. [4]',
    'Explain what is meant by specific heat capacity. [2]',
    'What is Hooke\'s Law? State its equation. [2]',
    'Describe the differences between series and parallel circuits. [3]',
    'Explain the concept of pressure in fluids. [3]',
    'What is the Doppler effect? Give an everyday example. [3]',
    'Calculate the gravitational potential energy of a 5kg mass at 10m height. [2]',
    'Describe how sound waves travel through air. [3]',
    'Explain total internal reflection and its applications. [3]',
    'What is electromagnetic induction? Describe Faraday\'s law. [3]',
    'Calculate the power of a device that uses 600J of energy in 30 seconds. [2]',
    'Describe the wave equation and calculate the frequency of a wave. [3]',
    'Explain the concept of terminal velocity. [3]',
    'What is a semiconductor? Name two common semiconductors. [2]',
    'Describe how a DC motor works. [4]',
    'Explain the concept of moments and the principle of moments. [3]',
    'What is radioactive half-life? Calculate after 3 half-lives. [3]',
    'A Level: Derive the equation for gravitational field strength. [4]',
    'A Level: Explain the photoelectric effect and its significance. [6]',
    'A Level: Describe simple harmonic motion with equations. [6]',
    'A Level: Explain wave-particle duality. [4]',
    'A Level: Describe the operation of a capacitor. [4]',
    'A Level: Explain special relativity and time dilation. [6]',
    'A Level: Describe the magnetic force on a moving charge. [4]',
    'A Level: Explain the concept of electric potential. [4]',
    'A Level: Describe nuclear fission and fusion. [6]',
    'A Level: Explain Kirchhoff\'s laws with circuit examples. [6]',
  ].map(q => ({ subject: 'Physics', question: q })),

  // ═══ MATHEMATICS (40 questions) ═══
  ...[
    'Solve: 3x + 7 = 22 [2]',
    'Factorise: x² + 5x + 6 [2]',
    'Find the area of a circle with radius 7cm. [2]',
    'Solve the simultaneous equations: 2x + y = 10 and x - y = 2 [3]',
    'Calculate the mean, median and mode of: 3, 5, 7, 5, 9, 5, 11 [3]',
    'Find the gradient of the line passing through (2,3) and (6,11). [2]',
    'Expand and simplify: (x + 3)(x - 5) [2]',
    'Convert 0.375 to a fraction in its simplest form. [2]',
    'Find the volume of a cylinder with radius 4cm and height 10cm. [2]',
    'Solve: x² - 9 = 0 [2]',
    'Calculate 15% of 240. [1]',
    'Find the nth term of the sequence: 3, 7, 11, 15, 19... [2]',
    'Calculate the hypotenuse of a right triangle with sides 6cm and 8cm. [2]',
    'Express 180 as a product of prime factors. [2]',
    'Find the equation of a line with gradient 2 passing through (1,5). [2]',
    'Simplify: (3x²y³)² [2]',
    'Calculate the probability of rolling a 6 on a fair dice. [1]',
    'Find the surface area of a cube with side length 5cm. [2]',
    'Solve the inequality: 4x - 3 > 13 [2]',
    'Calculate the compound interest on Rs 10,000 at 5% for 3 years. [3]',
    'Find the bearing of B from A if A is due north and B is 60° east. [2]',
    'Describe a transformation that maps shape A to shape B. [2]',
    'Calculate the interior angle of a regular octagon. [2]',
    'Solve: 2/(x+1) = 3/(x+4) [3]',
    'Find the distance between points (1,2) and (4,6). [2]',
    'Express 0.3̄ as a fraction. [2]',
    'Calculate the area of a trapezium with parallel sides 5cm and 9cm and height 4cm. [2]',
    'Simplify: √50 + √18 [2]',
    'Find the HCF and LCM of 24 and 36. [2]',
    'Describe the graph of y = x² - 4x + 3. [3]',
    'A Level: Differentiate y = 3x⁴ - 2x² + 5x - 1 [2]',
    'A Level: Integrate ∫(2x³ + 3x)dx [2]',
    'A Level: Find the stationary points of y = x³ - 6x² + 9x + 1 [4]',
    'A Level: Solve: sin²x + cos²x = 1 for 0 ≤ x ≤ 360° [3]',
    'A Level: Find the sum of the first 20 terms of the AP: 3, 7, 11... [3]',
    'A Level: Express in partial fractions: (3x+1)/((x+1)(x-2)) [3]',
    'A Level: Find dy/dx using the chain rule for y = (2x+3)⁵ [3]',
    'A Level: Calculate the binomial expansion of (1+x)⁴ [3]',
    'A Level: Solve the differential equation dy/dx = 2xy [4]',
    'A Level: Find the area under the curve y = x² between x=0 and x=3 [3]',
  ].map(q => ({ subject: 'Mathematics', question: q })),

  // ═══ ENGLISH LANGUAGE (40 questions) ═══
  ...[
    'Write a descriptive paragraph about a busy marketplace. [5]',
    'Identify three language techniques in: "The wind howled through the empty streets like a wounded animal." [3]',
    'Write a formal letter to a newspaper about environmental pollution. [8]',
    'Explain the effect of the metaphor: "Time is a thief." [2]',
    'Summarise the main arguments for and against social media use by teenagers. [4]',
    'Write the opening paragraph of a story set during a storm. [5]',
    'What is the difference between a simile and a metaphor? Give examples. [3]',
    'Write a speech persuading your school to introduce more sports facilities. [6]',
    'Identify the audience and purpose of an advertisement for a luxury car. [2]',
    'Explain what is meant by "pathetic fallacy" with an example. [2]',
    'Write a diary entry from the perspective of someone stranded on an island. [5]',
    'Analyse the use of repetition in political speeches. [3]',
    'Write a report on the benefits of reading for young people. [6]',
    'Explain the difference between active and passive voice. [2]',
    'Write a narrative that begins with the line: "She knew she should not have opened the door." [8]',
    'Identify and explain the tone of a given extract. [3]',
    'Write directions from your school to the nearest hospital. [4]',
    'Explain the purpose of rhetorical questions in persuasive writing. [2]',
    'Write a review of a book or film you have recently enjoyed. [5]',
    'What is emotive language? Why do writers use it? [2]',
    'Write a conversation between two friends planning a trip. [5]',
    'Explain the structure of a well-organised essay. [3]',
    'Write an article for a school magazine about healthy eating. [6]',
    'Identify three features of informal writing. [3]',
    'Write a description of your favourite place. [5]',
    'Explain what onomatopoeia is and give three examples. [2]',
    'Write a summary of a passage in no more than 100 words. [4]',
    'What is the effect of short sentences in descriptive writing? [2]',
    'Write a letter of complaint about poor service at a restaurant. [6]',
    'Explain the concept of register in language. [2]',
    'A Level: Analyse how language creates mood in an unseen prose extract. [8]',
    'A Level: Compare the narrative techniques in two different novels. [8]',
    'A Level: Evaluate the effectiveness of a political speech extract. [6]',
    'A Level: Write a critical commentary on an unseen poem. [8]',
    'A Level: Discuss the role of the unreliable narrator in fiction. [6]',
    'A Level: Analyse the representation of gender in media language. [6]',
    'A Level: Compare two texts from different periods on the same theme. [8]',
    'A Level: Evaluate the impact of context on the production of a text. [6]',
    'A Level: Write a transformational piece changing genre of a given text. [8]',
    'A Level: Discuss how writers use structure to create meaning. [6]',
  ].map(q => ({ subject: 'English', question: q })),

  // ═══ PAKISTAN STUDIES (40 questions) ═══
  ...[
    'Explain the Two-Nation Theory and its importance to the Pakistan Movement. [4]',
    'Describe the role of Sir Syed Ahmad Khan in Muslim education. [4]',
    'What was the Lahore Resolution of 1940? Why was it significant? [4]',
    'Explain the causes and effects of the War of Independence 1857. [4]',
    'Describe the geographical features of Northern Pakistan. [3]',
    'What were the 14 Points of Jinnah? [4]',
    'Explain the importance of the Khilafat Movement. [3]',
    'Describe the role of Allama Iqbal in the creation of Pakistan. [4]',
    'What were the causes of the partition of Bengal in 1905? [3]',
    'Explain the Lucknow Pact of 1916. [3]',
    'Describe the main industries of Pakistan. [3]',
    'What was the Simon Commission? Why was it boycotted? [3]',
    'Explain the Round Table Conferences. [4]',
    'Describe the problems Pakistan faced at independence in 1947. [4]',
    'What was the Objectives Resolution of 1949? [3]',
    'Explain the Kashmir dispute between Pakistan and India. [4]',
    'Describe the climate of Pakistan and its effects on agriculture. [3]',
    'What was the role of the Muslim League in the Pakistan Movement? [4]',
    'Explain the significance of the 1956 Constitution. [3]',
    'Describe the water resources of Pakistan. [3]',
    'What was the Cripps Mission? Why did it fail? [3]',
    'Explain the importance of CPEC for Pakistan. [4]',
    'Describe the education system in Pakistan. [3]',
    'What was the Cabinet Mission Plan? [3]',
    'Explain the role of women in the Pakistan Movement. [4]',
    'Describe the major crops grown in Pakistan. [3]',
    'What was the Mountbatten Plan? [3]',
    'Explain the significance of the 1973 Constitution. [4]',
    'Describe the transport system in Pakistan. [3]',
    'What were the causes of the 1971 war? [4]',
    'Explain the importance of Quaid-e-Azam\'s leadership. [4]',
    'Describe the mineral resources of Pakistan. [3]',
    'What was the Simla Deputation of 1906? [3]',
    'Explain the relationship between Pakistan and China. [4]',
    'Describe the population distribution of Pakistan. [3]',
    'What was the Government of India Act 1935? [3]',
    'Explain Pakistan\'s foreign policy challenges. [4]',
    'Describe the cultural heritage of Pakistan. [3]',
    'What was the Direct Action Day of 1946? [3]',
    'Explain the significance of the Indus Water Treaty. [4]',
  ].map(q => ({ subject: 'Pakistan Studies', question: q })),

  // ═══ ISLAMIAT (40 questions) ═══
  ...[
    'Describe the five pillars of Islam. [5]',
    'Explain the importance of Surah Al-Fatiha. [3]',
    'What is the significance of the Hijrah? [4]',
    'Describe the life of Prophet Muhammad (PBUH) in Madinah. [4]',
    'Explain the importance of Hajj and its rituals. [4]',
    'What are the articles of faith in Islam? [3]',
    'Describe the Battle of Badr and its significance. [4]',
    'Explain the concept of Zakat and its importance. [3]',
    'What is the importance of Friday prayers? [3]',
    'Describe the role of the Quran in a Muslim\'s life. [3]',
    'Explain the Treaty of Hudaibiya and its significance. [4]',
    'What are the rights of parents in Islam? [3]',
    'Describe the Farewell Sermon of the Prophet (PBUH). [4]',
    'Explain the concept of Jihad in Islam. [3]',
    'What is the importance of Ramadan and fasting? [3]',
    'Describe the contributions of Hazrat Abu Bakr (RA). [4]',
    'Explain the concept of Tawheed. [3]',
    'What are the rights of neighbours in Islam? [3]',
    'Describe the contributions of Hazrat Umar (RA). [4]',
    'Explain the importance of honesty in Islam. [3]',
    'What is the significance of the Night of Power (Laylat ul-Qadr)? [3]',
    'Describe the contributions of Hazrat Usman (RA). [4]',
    'Explain the Islamic concept of justice. [3]',
    'What are the six collections of Hadith? [3]',
    'Describe the contributions of Hazrat Ali (RA). [4]',
    'Explain the importance of Sadaqah. [3]',
    'What is the concept of Akhirah? [3]',
    'Describe the spread of Islam in the subcontinent. [4]',
    'Explain the importance of the Sunnah. [3]',
    'What is the Islamic view on education? [3]',
    'Explain Surah Al-Ikhlas and its message. [3]',
    'What is the importance of Shura (consultation) in Islam? [3]',
    'Describe the conquest of Makkah. [4]',
    'Explain the concept of Sabr (patience) in Islam. [3]',
    'What are the qualities of a good Muslim? [3]',
    'Describe the Islamic view on environmental protection. [3]',
    'Explain the importance of Bismillah. [2]',
    'What is the significance of Eid-ul-Adha? [3]',
    'Describe the role of mosques in Muslim society. [3]',
    'Explain the Islamic Golden Age and its contributions to science. [4]',
  ].map(q => ({ subject: 'Islamiat', question: q })),

  // ═══ ECONOMICS (40 questions) ═══
  ...[
    'Define opportunity cost and give an example. [2]',
    'Explain the law of demand with a diagram. [3]',
    'What is inflation? Describe its causes. [3]',
    'Explain the difference between a market economy and a planned economy. [3]',
    'What are the factors of production? [2]',
    'Describe the effects of unemployment on an economy. [3]',
    'Explain what is meant by GDP. [2]',
    'What is a tariff? Why do governments impose tariffs? [3]',
    'Describe the functions of money. [3]',
    'Explain the concept of elasticity of demand. [3]',
    'What is a monopoly? Give its advantages and disadvantages. [4]',
    'Describe the role of the central bank. [3]',
    'Explain the difference between fiscal and monetary policy. [3]',
    'What are externalities? Give an example of a negative externality. [3]',
    'Describe the circular flow of income. [3]',
    'Explain what causes a shift in the supply curve. [3]',
    'What is comparative advantage? How does it relate to trade? [3]',
    'Describe the multiplier effect. [3]',
    'Explain the difference between microeconomics and macroeconomics. [2]',
    'What is a budget deficit? How can it be reduced? [3]',
    'Describe the advantages and disadvantages of globalisation. [4]',
    'Explain the concept of market failure. [3]',
    'What is the balance of payments? [3]',
    'Describe the characteristics of a perfectly competitive market. [3]',
    'Explain how exchange rates are determined. [3]',
    'What is economic growth? How is it measured? [2]',
    'Describe the poverty cycle. [3]',
    'Explain the role of the World Bank and IMF. [3]',
    'What are subsidies? Why do governments provide them? [3]',
    'Describe the difference between progressive and regressive taxation. [3]',
    'A Level: Evaluate the effectiveness of supply-side policies. [6]',
    'A Level: Analyse the causes and consequences of deflation. [6]',
    'A Level: Discuss whether free trade is always beneficial. [6]',
    'A Level: Explain the theory of comparative advantage with numerical example. [6]',
    'A Level: Evaluate the Phillips Curve relationship. [6]',
    'A Level: Analyse the impact of quantitative easing. [6]',
    'A Level: Discuss the causes of income inequality. [6]',
    'A Level: Explain game theory and the prisoner\'s dilemma. [4]',
    'A Level: Evaluate different exchange rate systems. [6]',
    'A Level: Analyse the effectiveness of minimum wage legislation. [6]',
  ].map(q => ({ subject: 'Economics', question: q })),

  // ═══ COMPUTER SCIENCE (40 questions) ═══
  ...[
    'Convert the binary number 10110101 to denary. [2]',
    'Describe the fetch-decode-execute cycle. [3]',
    'What is the difference between RAM and ROM? [2]',
    'Write pseudocode for a program that finds the largest of three numbers. [3]',
    'Explain what a database primary key is. [2]',
    'Describe two methods of data validation. [2]',
    'What is a logic gate? Draw a truth table for an AND gate. [3]',
    'Explain the difference between a compiler and an interpreter. [3]',
    'Describe the purpose of an operating system. [3]',
    'What is an algorithm? Give an example. [2]',
    'Explain the concept of binary search. [3]',
    'Describe three types of network topology. [3]',
    'What is encryption? Why is it important? [2]',
    'Write pseudocode for a bubble sort algorithm. [4]',
    'Explain the difference between LAN and WAN. [2]',
    'Describe what HTML and CSS are used for. [2]',
    'What is a variable? Explain with an example. [2]',
    'Describe the concept of iteration in programming. [2]',
    'Explain the TCP/IP protocol suite. [3]',
    'What is cloud computing? Give two advantages. [3]',
    'Describe the difference between lossy and lossless compression. [2]',
    'What is SQL? Write a simple SELECT query. [3]',
    'Explain the concept of abstraction in computing. [2]',
    'Describe how email is sent and received. [3]',
    'What are the ethical issues surrounding AI? [3]',
    'Explain the concept of recursion with an example. [3]',
    'Describe the Von Neumann architecture. [3]',
    'What is phishing? How can it be prevented? [2]',
    'Explain the difference between TCP and UDP. [2]',
    'Describe the purpose of a firewall. [2]',
    'A Level: Explain the concept of Big O notation. [4]',
    'A Level: Describe the merge sort algorithm. [4]',
    'A Level: Explain object-oriented programming concepts. [4]',
    'A Level: Describe the Dijkstra shortest path algorithm. [4]',
    'A Level: Explain normalisation to 3NF in databases. [6]',
    'A Level: Describe the concept of virtual memory. [4]',
    'A Level: Explain the halting problem and its significance. [4]',
    'A Level: Describe how asymmetric encryption works. [4]',
    'A Level: Explain the concept of a Turing machine. [4]',
    'A Level: Describe the A* search algorithm. [4]',
  ].map(q => ({ subject: 'Computer Science', question: q })),

  // ═══ URDU (20 questions) ═══
  ...[
    'تشبیہ اور استعارہ میں کیا فرق ہے؟ مثالوں سے سمجھائیں۔ [3]',
    'اقبال کی نظم "خطاب بہ جوانان اسلام" کا خلاصہ بیان کریں۔ [4]',
    'مضمون لکھیں: میرا پسندیدہ شاعر [5]',
    'غالب کے ایک شعر کی تشریح کریں۔ [4]',
    'خط لکھیں: اپنے دوست کو سیر کی دعوت [4]',
    'نثر اور نظم میں فرق بیان کریں۔ [3]',
    'فیض احمد فیض کی شاعری کی خصوصیات بیان کریں۔ [4]',
    'درخواست لکھیں: چھٹی کے لیے [3]',
    'اردو ادب میں داستان کی اہمیت بیان کریں۔ [4]',
    'محاورے اور ضرب الامثال میں فرق بتائیں۔ [3]',
    'مضمون لکھیں: تعلیم کی اہمیت [5]',
    'غزل اور نظم میں فرق بیان کریں۔ [3]',
    'میر تقی میر کی شاعری کی خصوصیات بیان کریں۔ [4]',
    'خط لکھیں: اخبار کے ایڈیٹر کے نام [4]',
    'اردو زبان کی تاریخ مختصراً بیان کریں۔ [4]',
    'مضمون لکھیں: پاکستان کی ثقافت [5]',
    'قواعد: فعل کی اقسام بیان کریں۔ [3]',
    'سعادت حسن منٹو کی افسانہ نگاری پر نوٹ لکھیں۔ [4]',
    'مضمون لکھیں: سائنس کے فوائد اور نقصانات [5]',
    'اردو شاعری میں رومانوی تحریک کا جائزہ لیں۔ [4]',
  ].map(q => ({ subject: 'Urdu', question: q })),

  // ═══ GEOGRAPHY (20 questions) ═══
  ...[
    'Describe the formation of oxbow lakes. [4]',
    'Explain the causes of earthquakes along tectonic plate boundaries. [4]',
    'What is urbanisation? Describe its effects on developing countries. [4]',
    'Explain the water cycle with a labelled diagram description. [4]',
    'Describe the characteristics of a tropical rainforest climate. [3]',
    'What are the push and pull factors of migration? [3]',
    'Explain how volcanoes are formed at destructive plate margins. [4]',
    'Describe the effects of deforestation on the environment. [3]',
    'What is sustainable development? Give an example. [3]',
    'Explain the formation of sea stacks and caves. [4]',
    'Describe the effects of flooding on human activity. [3]',
    'What is a meander? How does it form? [3]',
    'Explain the difference between weather and climate. [2]',
    'Describe the demographic transition model. [4]',
    'What are the advantages and disadvantages of tourism? [4]',
    'Explain how soil erosion occurs and how it can be prevented. [3]',
    'Describe the features of a delta. [3]',
    'What is desertification? What causes it? [3]',
    'Explain the greenhouse effect and global warming. [3]',
    'Describe the settlement hierarchy. [3]',
  ].map(q => ({ subject: 'Geography', question: q })),
];

export default async function handler(req, res) {
  // Auth check
  const auth = req.headers.authorization || req.query.secret;
  if (auth !== process.env.CRON_SECRET && auth !== `Bearer ${process.env.CRON_SECRET}`) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  const sb = getSupabase();
  const batchSize = parseInt(req.query.batch || '20'); // Process N questions per call
  const startIdx = parseInt(req.query.start || '0');
  const endIdx = Math.min(startIdx + batchSize, QUESTIONS.length);

  const results = [];
  let answered = 0;

  for (let i = startIdx; i < endIdx; i++) {
    const q = QUESTIONS[i];
    try {
      const response = await client.messages.create({
        model: 'claude-3-haiku-20240307',
        max_tokens: 600,
        system: `You are Starky, a Cambridge exam specialist. Answer this ${q.subject} question as you would for a student preparing for their Cambridge O/A Level exam. Be precise, use mark scheme language, and show the key points that earn marks. Keep your answer concise and exam-focused.`,
        messages: [{ role: 'user', content: q.question }],
      });
      const answer = response.content?.[0]?.text || '';
      results.push({ subject: q.subject, question: q.question, answer, status: 'answered', index: i });
      answered++;

      // Store in Supabase
      if (sb) {
        await sb.from('cambridge_test_answers').insert({
          subject: q.subject,
          question: q.question,
          answer,
          model: 'claude-3-haiku-20240307',
          timestamp: new Date().toISOString(),
          question_index: i,
        }).catch(() => {});
      }
    } catch (err) {
      results.push({ subject: q.subject, question: q.question, answer: '', status: 'error', error: err.message, index: i });
    }
  }

  return res.status(200).json({
    total_questions: QUESTIONS.length,
    batch_start: startIdx,
    batch_end: endIdx,
    answered_in_batch: answered,
    next_batch_start: endIdx < QUESTIONS.length ? endIdx : null,
    results,
  });
}
