#!/bin/bash
# session-end.sh
# Unified Stop hook — runs on every Claude Code session exit.
# Auto-detects what to do for this specific repo.
#
# Does:
#   1. Writes .claude/SESSION.md (session handover)
#   2. Updates CLAUDE.md session snapshot (if CLAUDE.md exists)
#   3. Indexes Claude memory (if this repo has a ~/.claude/projects dir)
#   4. Triggers central backup (idempotent — only pushes if changed)
#
# Silent unless there's output to surface.

# Ensure we're in the repo root
cd "$(git rev-parse --show-toplevel 2>/dev/null || echo ".")"

[ -d .git ] || exit 0
mkdir -p .claude

# ─── 1. Write SESSION.md ───
PROJECT=$(basename "$(pwd)")
NOW=$(date '+%Y-%m-%d %H:%M')
UNCOMMITTED=$(git status --short 2>/dev/null)
TODAY_COMMITS=$(git log --since="$(date '+%Y-%m-%d') 00:00" --oneline 2>/dev/null)
TODAY_COUNT=$(echo "$TODAY_COMMITS" | grep -c "^[a-f0-9]" 2>/dev/null || echo 0)
RECENT=$(git log --oneline -5 2>/dev/null)
LAST_FILES=$(git diff HEAD~1 --name-only 2>/dev/null | head -10)
BRANCH=$(git branch --show-current 2>/dev/null)
AHEAD=$(git rev-list --count @{u}..HEAD 2>/dev/null || echo "?")

cat > .claude/SESSION.md <<EOF
# Session handover — ${PROJECT}
**Generated:** ${NOW}

## Current state
- Branch: ${BRANCH}
- Unpushed commits: ${AHEAD}
- Today's pushes: ${TODAY_COUNT}

## Uncommitted changes
${UNCOMMITTED:-_(working tree clean)_}

## Today's commits
\`\`\`
${TODAY_COMMITS:-(none)}
\`\`\`

## Last 5 commits
\`\`\`
${RECENT}
\`\`\`

## Files in last commit
\`\`\`
${LAST_FILES}
\`\`\`

## Where to resume
${UNCOMMITTED:+Continue uncommitted work above.}
${UNCOMMITTED:-No pending work. Last commit is the resume point.}

_Auto-generated by .claude/session-end.sh on every session exit._
EOF

# ─── 2. Update CLAUDE.md snapshot (only if CLAUDE.md exists) ───
if [ -f CLAUDE.md ] && [ -f .claude/update-claude-md.sh ]; then
  bash .claude/update-claude-md.sh >/dev/null 2>&1 || true
fi

# ─── 3. Index Claude memory (only if this repo has a memory dir) ───
# Memory lives at ~/.claude/projects/<encoded-path>/memory
ENCODED=$(pwd | sed 's|/|-|g')
MEM_DIR="/Users/khurramb/.claude/projects/${ENCODED}/memory"
if [ -d "$MEM_DIR" ] && [ -f .claude/auto-memory-index.sh ]; then
  bash .claude/auto-memory-index.sh >/dev/null 2>&1 || true
fi

# ─── 4. Central backup (idempotent — safe to call often) ───
BACKUP_SCRIPT="/Users/khurramb/projects/newworld-platform/scripts/backup-claude-state.sh"
if [ -x "$BACKUP_SCRIPT" ]; then
  bash "$BACKUP_SCRIPT" >/dev/null 2>&1 || true
fi

exit 0
