/**
 * utils/physicsAtomsOLevel.js
 * Cambridge Physics O Level (5054) — Knowledge Atoms
 *
 * Each atom is the smallest testable fact or skill at O Level.
 * Aligned to Cambridge 5054 syllabus.
 *
 * PROTECTED: This is a new file. No existing file is modified.
 */

export const physicsAtoms = [

  // ─────────────────────────────────────────────
  // UNIT 1: MEASUREMENT (~10 atoms)
  // ─────────────────────────────────────────────

  {
    id: "phys_meas_physquant_sibaseunits",
    subject: "physics",
    level: "o_level",
    unit: "Measurement",
    chapter: "Physical Quantities and Units",
    topic: "SI Base Units",
    atom: "The seven SI base units are: metre (m), kilogram (kg), second (s), ampere (A), kelvin (K), mole (mol), candela (cd)",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_meas_physquant_derived"]
  },
  {
    id: "phys_meas_physquant_derived",
    subject: "physics",
    level: "o_level",
    unit: "Measurement",
    chapter: "Physical Quantities and Units",
    topic: "Derived Units",
    atom: "Derived units are combinations of base units; e.g., speed in m/s, force in kg m/s² (N), energy in kg m²/s² (J)",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_meas_physquant_sibaseunits"]
  },
  {
    id: "phys_meas_physquant_prefixes",
    subject: "physics",
    level: "o_level",
    unit: "Measurement",
    chapter: "Physical Quantities and Units",
    topic: "Metric Prefixes",
    atom: "Common prefixes: nano (n) = 10⁻⁹, micro (μ) = 10⁻⁶, milli (m) = 10⁻³, centi (c) = 10⁻², kilo (k) = 10³, mega (M) = 10⁶",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: []
  },
  {
    id: "phys_meas_length_micrometer",
    subject: "physics",
    level: "o_level",
    unit: "Measurement",
    chapter: "Measuring Length",
    topic: "Micrometer Screw Gauge",
    atom: "A micrometer screw gauge measures lengths to the nearest 0.01 mm; the thimble scale reads in 0.01 mm divisions and must be added to the sleeve reading",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_meas_length_vernier"]
  },
  {
    id: "phys_meas_length_vernier",
    subject: "physics",
    level: "o_level",
    unit: "Measurement",
    chapter: "Measuring Length",
    topic: "Vernier Calipers",
    atom: "Vernier calipers measure lengths to the nearest 0.1 mm; the vernier scale reading is added to the main scale reading",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_meas_length_micrometer"]
  },
  {
    id: "phys_meas_time_period",
    subject: "physics",
    level: "o_level",
    unit: "Measurement",
    chapter: "Measuring Time",
    topic: "Pendulum Period",
    atom: "To reduce timing error, measure the time for 20 complete oscillations and divide by 20 to find the period T of a pendulum",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: []
  },
  {
    id: "phys_meas_scalar_vector",
    subject: "physics",
    level: "o_level",
    unit: "Measurement",
    chapter: "Scalars and Vectors",
    topic: "Scalar vs Vector",
    atom: "A scalar quantity has magnitude only (e.g. speed, mass, temperature, distance); a vector quantity has both magnitude and direction (e.g. velocity, force, displacement, acceleration)",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_meas_scalar_addition"]
  },
  {
    id: "phys_meas_scalar_addition",
    subject: "physics",
    level: "o_level",
    unit: "Measurement",
    chapter: "Scalars and Vectors",
    topic: "Vector Addition",
    atom: "Vectors are added using the parallelogram rule or triangle rule; the resultant is the single vector that has the same effect as the two component vectors",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_meas_scalar_vector"]
  },
  {
    id: "phys_meas_density_formula",
    subject: "physics",
    level: "o_level",
    unit: "Measurement",
    chapter: "Density",
    topic: "Density Formula",
    atom: "Density ρ = m/V where m is mass in kg and V is volume in m³; unit of density is kg/m³ or g/cm³",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_meas_density_irregular"]
  },
  {
    id: "phys_meas_density_irregular",
    subject: "physics",
    level: "o_level",
    unit: "Measurement",
    chapter: "Density",
    topic: "Irregular Object Density",
    atom: "The volume of an irregular solid is found by displacement: submerge in a measuring cylinder and measure the rise in water level; volume = final reading − initial reading",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_meas_density_formula"]
  },

  // ─────────────────────────────────────────────
  // UNIT 2: MOTION (~20 atoms)
  // ─────────────────────────────────────────────

  {
    id: "phys_motion_kinematics_displacement",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Kinematics",
    topic: "Distance and Displacement",
    atom: "Distance is the total path length travelled (scalar); displacement is the straight-line distance from start to finish in a specified direction (vector)",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_motion_kinematics_speed"]
  },
  {
    id: "phys_motion_kinematics_speed",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Kinematics",
    topic: "Speed and Velocity",
    atom: "Average speed = total distance / total time; average velocity = total displacement / total time; unit is m/s",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_motion_kinematics_displacement", "phys_motion_kinematics_acceleration"]
  },
  {
    id: "phys_motion_kinematics_acceleration",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Kinematics",
    topic: "Acceleration",
    atom: "Acceleration a = (v − u) / t where v is final velocity, u is initial velocity, t is time; unit is m/s²; deceleration is negative acceleration",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_motion_kinematics_speed", "phys_motion_eqn_vuat"]
  },
  {
    id: "phys_motion_eqn_vuat",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Equations of Motion",
    topic: "First Equation of Motion",
    atom: "v = u + at where v is final velocity (m/s), u is initial velocity (m/s), a is acceleration (m/s²), t is time (s); valid for uniform acceleration only",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_motion_eqn_sut", "phys_motion_eqn_v2u2"]
  },
  {
    id: "phys_motion_eqn_sut",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Equations of Motion",
    topic: "Second Equation of Motion",
    atom: "s = ut + ½at² where s is displacement (m); used when final velocity is unknown",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_motion_eqn_vuat", "phys_motion_eqn_v2u2"]
  },
  {
    id: "phys_motion_eqn_v2u2",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Equations of Motion",
    topic: "Third Equation of Motion",
    atom: "v² = u² + 2as where s is displacement (m); used when time is not given",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_motion_eqn_vuat", "phys_motion_eqn_sut"]
  },
  {
    id: "phys_motion_graph_dtvt",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Motion Graphs",
    topic: "Distance-Time Graph Gradient",
    atom: "The gradient (slope) of a distance–time graph equals the speed; a curved d-t graph means changing speed (acceleration or deceleration)",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_motion_graph_vtarea"]
  },
  {
    id: "phys_motion_graph_vtarea",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Motion Graphs",
    topic: "Velocity-Time Graph Area",
    atom: "The area under a velocity–time graph equals the distance (displacement) travelled; the gradient of a v-t graph equals the acceleration",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_motion_graph_dtvt"]
  },
  {
    id: "phys_motion_graph_uniform",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Motion Graphs",
    topic: "Uniform Motion on v-t Graph",
    atom: "A horizontal straight line on a v-t graph represents uniform motion (constant velocity, zero acceleration)",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_motion_graph_vtarea"]
  },
  {
    id: "phys_motion_freefall_g",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Free Fall",
    topic: "Acceleration due to Gravity",
    atom: "In free fall (no air resistance), all objects accelerate downward at g = 10 m/s² (or 9.8 m/s² where stated) regardless of mass",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_motion_freefall_terminal"]
  },
  {
    id: "phys_motion_freefall_terminal",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Free Fall",
    topic: "Terminal Velocity",
    atom: "Terminal velocity is reached when air resistance equals the weight of a falling object; the resultant force is zero so acceleration is zero and speed is constant",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_motion_freefall_g", "phys_forces_newton_first"]
  },
  {
    id: "phys_motion_freefall_vt_shape",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Free Fall",
    topic: "Velocity-Time Graph for Falling Object",
    atom: "For a falling object with air resistance: v-t graph starts steep (high acceleration), curves and flattens as air resistance grows, then is horizontal at terminal velocity",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_motion_freefall_terminal", "phys_motion_graph_vtarea"]
  },
  {
    id: "phys_motion_relative_speed",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Relative Motion",
    topic: "Relative Speed",
    atom: "When two objects move in the same direction, relative speed = difference of speeds; when moving toward each other, relative speed = sum of speeds",
    difficulty: 2,
    examWeight: "low",
    relatedAtoms: []
  },
  {
    id: "phys_motion_ticker_tape",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Practical Measurement of Motion",
    topic: "Ticker Tape Timer",
    atom: "A ticker tape timer makes 50 dots per second (at 50 Hz mains); the time interval between consecutive dots is 1/50 = 0.02 s; spacing between dots shows speed",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_motion_kinematics_acceleration"]
  },
  {
    id: "phys_motion_stroboscope",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Practical Measurement of Motion",
    topic: "Stroboscope",
    atom: "A stroboscope photograph shows the position of a moving object at equal time intervals; equal spacing = constant speed, increasing spacing = acceleration",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_motion_ticker_tape"]
  },
  {
    id: "phys_motion_projectile_horizontal",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Projectile Motion",
    topic: "Horizontal Projectile",
    atom: "A projectile has constant horizontal velocity (no horizontal force) and constant downward acceleration g; the two components of motion are independent",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_motion_freefall_g"]
  },
  {
    id: "phys_motion_inertia_def",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Inertia",
    topic: "Definition of Inertia",
    atom: "Inertia is the tendency of an object to resist any change in its state of rest or uniform motion; greater mass means greater inertia",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_forces_newton_first"]
  },
  {
    id: "phys_motion_momentum_def",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Momentum",
    topic: "Momentum Definition",
    atom: "Momentum p = mv where m is mass (kg) and v is velocity (m/s); momentum is a vector quantity; unit is kg m/s",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_motion_momentum_conservation"]
  },
  {
    id: "phys_motion_momentum_conservation",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Momentum",
    topic: "Conservation of Momentum",
    atom: "The total momentum of a closed system is conserved in any collision or explosion provided no external forces act: total momentum before = total momentum after",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_motion_momentum_def", "phys_forces_newton_third"]
  },
  {
    id: "phys_motion_impulse",
    subject: "physics",
    level: "o_level",
    unit: "Motion",
    chapter: "Momentum",
    topic: "Impulse",
    atom: "Impulse = force × time = Ft = change in momentum = mv − mu; unit is N s = kg m/s; a larger contact time reduces the force for a given change in momentum",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_motion_momentum_def", "phys_forces_newton_second"]
  },

  // ─────────────────────────────────────────────
  // UNIT 3: FORCES (~20 atoms)
  // ─────────────────────────────────────────────

  {
    id: "phys_forces_newton_first",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Newton's Laws",
    topic: "Newton's First Law",
    atom: "Newton's First Law: an object remains at rest or moves at constant velocity unless acted upon by a resultant (net) external force",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_motion_inertia_def", "phys_forces_newton_second"]
  },
  {
    id: "phys_forces_newton_second",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Newton's Laws",
    topic: "Newton's Second Law",
    atom: "Newton's Second Law: F = ma where F is resultant force (N), m is mass (kg), a is acceleration (m/s²); doubling the force doubles the acceleration for constant mass",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_forces_newton_first", "phys_forces_newton_third"]
  },
  {
    id: "phys_forces_newton_third",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Newton's Laws",
    topic: "Newton's Third Law",
    atom: "Newton's Third Law: for every action force there is an equal and opposite reaction force acting on a different object; the pair act on different bodies",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_forces_newton_second", "phys_motion_momentum_conservation"]
  },
  {
    id: "phys_forces_weight_def",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Weight and Mass",
    topic: "Weight Formula",
    atom: "Weight W = mg where m is mass (kg) and g is gravitational field strength (10 N/kg on Earth); weight is a force measured in newtons, mass is constant",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_forces_newton_second"]
  },
  {
    id: "phys_forces_friction_def",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Friction",
    topic: "Nature of Friction",
    atom: "Friction is a force that opposes the relative motion between surfaces in contact; it acts parallel to the surface and in the direction opposite to motion",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_forces_friction_factors"]
  },
  {
    id: "phys_forces_friction_factors",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Friction",
    topic: "Factors Affecting Friction",
    atom: "Friction depends on the nature of the surfaces (roughness) and the normal force pressing them together; it does not depend on the area of contact or speed",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_forces_friction_def"]
  },
  {
    id: "phys_forces_resultant",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Resultant Force",
    topic: "Adding Forces",
    atom: "The resultant force is the single force that has the same effect as all the individual forces combined; forces in the same direction add; opposite directions subtract",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_meas_scalar_addition"]
  },
  {
    id: "phys_forces_equilibrium",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Equilibrium",
    topic: "Conditions for Equilibrium",
    atom: "An object is in equilibrium when (1) the resultant force on it is zero AND (2) the resultant torque (moment) about any point is zero",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_forces_moment_def", "phys_forces_resultant"]
  },
  {
    id: "phys_forces_moment_def",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Moments",
    topic: "Moment of a Force",
    atom: "Moment of a force = force × perpendicular distance from the pivot; unit is N m; moment is a turning effect",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_forces_moment_principle"]
  },
  {
    id: "phys_forces_moment_principle",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Moments",
    topic: "Principle of Moments",
    atom: "Principle of Moments: for a body in equilibrium, the sum of clockwise moments about any point equals the sum of anticlockwise moments about the same point",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_forces_moment_def", "phys_forces_equilibrium"]
  },
  {
    id: "phys_forces_cog_def",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Centre of Gravity",
    topic: "Centre of Gravity Definition",
    atom: "The centre of gravity (centre of mass) of an object is the single point at which the entire weight of the object can be considered to act",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_forces_cog_stability"]
  },
  {
    id: "phys_forces_cog_stability",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Centre of Gravity",
    topic: "Stability and Centre of Gravity",
    atom: "Stability is increased by lowering the centre of gravity and widening the base; an object topples when the vertical line through its centre of gravity falls outside the base",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_forces_cog_def"]
  },
  {
    id: "phys_forces_cog_lamina",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Centre of Gravity",
    topic: "Finding CoG by Suspension",
    atom: "The centre of gravity of an irregular lamina is found by suspending it from two different points; the CoG lies at the intersection of the two plumb lines",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_forces_cog_def"]
  },
  {
    id: "phys_forces_elastic_hooke",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Elasticity",
    topic: "Hooke's Law",
    atom: "Hooke's Law: extension e is directly proportional to applied force F provided the elastic limit is not exceeded; F = ke where k is the spring constant (N/m)",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_forces_elastic_limit"]
  },
  {
    id: "phys_forces_elastic_limit",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Elasticity",
    topic: "Elastic Limit",
    atom: "The elastic limit is the maximum force beyond which a spring (or elastic material) does not return to its original length when the force is removed; it becomes permanently deformed",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_forces_elastic_hooke"]
  },
  {
    id: "phys_forces_springs_series",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Elasticity",
    topic: "Springs in Series and Parallel",
    atom: "Springs in series: total extension is the sum of individual extensions (softer system); springs in parallel: same extension, forces add (stiffer system)",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_forces_elastic_hooke"]
  },
  {
    id: "phys_forces_friction_types",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Friction",
    topic: "Useful and Harmful Friction",
    atom: "Friction is useful in brakes, walking, and gripping tools; it is harmful in engines and moving parts where it causes wear and heat energy loss",
    difficulty: 1,
    examWeight: "low",
    relatedAtoms: ["phys_forces_friction_def"]
  },
  {
    id: "phys_forces_upthrust",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Upthrust and Floating",
    topic: "Archimedes' Principle",
    atom: "Upthrust = weight of fluid displaced; an object floats when upthrust equals weight; it sinks when weight exceeds the maximum upthrust (weight of total fluid displaced)",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_forces_weight_def"]
  },
  {
    id: "phys_forces_free_body",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Force Diagrams",
    topic: "Free Body Diagrams",
    atom: "A free body diagram shows all forces acting ON a single object as arrows; arrow length represents magnitude, arrow direction represents direction of force",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_forces_resultant"]
  },
  {
    id: "phys_forces_turning_lever",
    subject: "physics",
    level: "o_level",
    unit: "Forces",
    chapter: "Moments",
    topic: "Levers as Force Multipliers",
    atom: "A lever is a rigid bar that pivots about a fulcrum; it can multiply force (load × load distance = effort × effort distance from principle of moments)",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_forces_moment_principle"]
  },

  // ─────────────────────────────────────────────
  // UNIT 4: ENERGY, WORK, POWER (~20 atoms)
  // ─────────────────────────────────────────────

  {
    id: "phys_energy_work_formula",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Work",
    topic: "Work Done Formula",
    atom: "Work done W = Fd where F is the force (N) and d is the displacement in the direction of the force (m); unit is joule (J) = N m; work is a scalar",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_energy_energy_conservation"]
  },
  {
    id: "phys_energy_ke_formula",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Kinetic Energy",
    topic: "Kinetic Energy Formula",
    atom: "Kinetic energy Eₖ = ½mv² where m is mass (kg) and v is speed (m/s); KE depends on the square of speed, so doubling speed quadruples KE",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_energy_pe_formula", "phys_energy_energy_conservation"]
  },
  {
    id: "phys_energy_pe_formula",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Gravitational Potential Energy",
    topic: "GPE Formula",
    atom: "Gravitational potential energy Eₚ = mgh where m is mass (kg), g = 10 N/kg, h is vertical height gained (m); unit is joule (J)",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_energy_ke_formula", "phys_energy_energy_conservation"]
  },
  {
    id: "phys_energy_energy_conservation",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Conservation of Energy",
    topic: "Law of Conservation of Energy",
    atom: "Energy cannot be created or destroyed; it can only be converted from one form to another; the total energy of a closed system remains constant",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_energy_ke_formula", "phys_energy_pe_formula"]
  },
  {
    id: "phys_energy_ke_pe_exchange",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Conservation of Energy",
    topic: "KE-PE Exchange",
    atom: "For a freely falling object (no air resistance), KE gained = PE lost; ½mv² = mgh; at any point KE + PE = constant total mechanical energy",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_energy_ke_formula", "phys_energy_pe_formula"]
  },
  {
    id: "phys_energy_power_formula",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Power",
    topic: "Power Formula",
    atom: "Power P = W/t = energy transferred / time; unit is watt (W) = J/s; also P = Fv where v is velocity",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_energy_work_formula"]
  },
  {
    id: "phys_energy_efficiency",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Efficiency",
    topic: "Efficiency Formula",
    atom: "Efficiency = (useful energy output / total energy input) × 100%; always less than 100% in real machines because some energy is wasted as heat or sound",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_energy_energy_conservation"]
  },
  {
    id: "phys_energy_forms",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Forms of Energy",
    topic: "Eight Main Energy Stores",
    atom: "The main energy stores are: kinetic, gravitational potential, elastic potential, chemical, thermal (internal), nuclear, electromagnetic (light), and electrical",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: []
  },
  {
    id: "phys_energy_sources_renewable",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Energy Sources",
    topic: "Renewable Energy Sources",
    atom: "Renewable energy sources are naturally replenished and will not run out: solar, wind, hydroelectric, tidal, wave, geothermal, and biofuel",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_energy_sources_nonrenewable"]
  },
  {
    id: "phys_energy_sources_nonrenewable",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Energy Sources",
    topic: "Non-Renewable Energy Sources",
    atom: "Non-renewable energy sources are finite and will eventually run out: coal, oil, natural gas (fossil fuels), and nuclear fuel (uranium)",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_energy_sources_renewable"]
  },
  {
    id: "phys_energy_fossil_combustion",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Energy Sources",
    topic: "Fossil Fuel Power Station",
    atom: "In a fossil fuel power station: chemical energy → heat (steam) → kinetic energy (turbine) → electrical energy (generator); each conversion loses energy as heat",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_energy_efficiency", "phys_energy_sources_nonrenewable"]
  },
  {
    id: "phys_energy_spring_elastic_pe",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Elastic Potential Energy",
    topic: "Elastic PE in a Spring",
    atom: "Elastic PE stored in a stretched or compressed spring Eₛ = ½ke² where k is spring constant (N/m) and e is extension (m); equals area under force-extension graph",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_forces_elastic_hooke"]
  },
  {
    id: "phys_energy_solar_panel",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Energy Sources",
    topic: "Solar Panels vs Solar Cells",
    atom: "Solar thermal panels heat water using infrared radiation from the Sun; photovoltaic (solar) cells convert light energy directly into electrical energy",
    difficulty: 2,
    examWeight: "low",
    relatedAtoms: ["phys_energy_sources_renewable"]
  },
  {
    id: "phys_energy_hydroelectric",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Energy Sources",
    topic: "Hydroelectric Power",
    atom: "In hydroelectric power stations, water falls from a high reservoir; GPE → KE of water → KE of turbine → electrical energy; near 90% efficient",
    difficulty: 2,
    examWeight: "low",
    relatedAtoms: ["phys_energy_pe_formula", "phys_energy_efficiency"]
  },
  {
    id: "phys_energy_work_angle",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Work",
    topic: "Work Done at an Angle",
    atom: "Work done = Fd cos θ where θ is the angle between the force and the direction of motion; if force is perpendicular to motion (θ = 90°), work done = 0",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_energy_work_formula"]
  },
  {
    id: "phys_energy_power_practical",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Power",
    topic: "Human Power Calculation",
    atom: "A person's power output can be measured by timing how quickly they climb stairs: P = mgh/t where h is height of stairs, t is time taken",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_energy_power_formula", "phys_energy_pe_formula"]
  },
  {
    id: "phys_energy_sankey",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Efficiency",
    topic: "Sankey Diagrams",
    atom: "A Sankey diagram shows energy transfers; arrow widths are proportional to the amount of energy; wasted energy (heat/sound) branches off to one side",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_energy_efficiency"]
  },
  {
    id: "phys_energy_cost_electricity",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Electrical Energy",
    topic: "Cost of Electrical Energy",
    atom: "Electrical energy used (kWh) = power (kW) × time (h); cost = energy in kWh × price per unit; 1 kWh = 3.6 × 10⁶ J",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_energy_power_formula"]
  },
  {
    id: "phys_energy_conservation_machines",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Simple Machines",
    topic: "Machines and Energy Conservation",
    atom: "A simple machine cannot create energy; it changes the size or direction of a force; in an ideal machine, work input = work output; in real machines, efficiency < 100%",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_energy_efficiency"]
  },
  {
    id: "phys_energy_wasted_heat",
    subject: "physics",
    level: "o_level",
    unit: "Energy, Work, Power",
    chapter: "Efficiency",
    topic: "Wasted Energy as Heat",
    atom: "In most energy conversions, energy is wasted as heat due to friction and electrical resistance; this energy dissipates to the surroundings and becomes less useful",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_energy_efficiency", "phys_energy_energy_conservation"]
  },

  // ─────────────────────────────────────────────
  // UNIT 5: PRESSURE (~15 atoms)
  // ─────────────────────────────────────────────

  {
    id: "phys_pressure_def_formula",
    subject: "physics",
    level: "o_level",
    unit: "Pressure",
    chapter: "Pressure",
    topic: "Pressure Formula",
    atom: "Pressure P = F/A where F is the force (N) perpendicular to the surface and A is the area (m²); unit is pascal (Pa) = N/m²",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_pressure_liquid_depth"]
  },
  {
    id: "phys_pressure_liquid_depth",
    subject: "physics",
    level: "o_level",
    unit: "Pressure",
    chapter: "Pressure in Liquids",
    topic: "Pressure with Depth",
    atom: "Pressure in a liquid P = hρg where h is depth (m), ρ is density (kg/m³), g = 10 N/kg; pressure increases with depth and does not depend on the shape of the container",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_pressure_def_formula", "phys_pressure_liquid_direction"]
  },
  {
    id: "phys_pressure_liquid_direction",
    subject: "physics",
    level: "o_level",
    unit: "Pressure",
    chapter: "Pressure in Liquids",
    topic: "Direction of Liquid Pressure",
    atom: "Pressure in a liquid acts in all directions equally at a given depth; it acts perpendicular to any surface in contact with the liquid",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_pressure_liquid_depth"]
  },
  {
    id: "phys_pressure_atmospheric",
    subject: "physics",
    level: "o_level",
    unit: "Pressure",
    chapter: "Atmospheric Pressure",
    topic: "Atmospheric Pressure Value",
    atom: "Standard atmospheric pressure is approximately 101 000 Pa (101 kPa); it is caused by the weight of the air column above and decreases with altitude",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_pressure_barometer"]
  },
  {
    id: "phys_pressure_barometer",
    subject: "physics",
    level: "o_level",
    unit: "Pressure",
    chapter: "Atmospheric Pressure",
    topic: "Mercury Barometer",
    atom: "A mercury barometer measures atmospheric pressure; standard pressure supports a mercury column of 760 mm (76 cm); P_atm = hρg where h = 0.76 m and ρ_mercury = 13 600 kg/m³",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_pressure_atmospheric", "phys_pressure_liquid_depth"]
  },
  {
    id: "phys_pressure_manometer",
    subject: "physics",
    level: "o_level",
    unit: "Pressure",
    chapter: "Atmospheric Pressure",
    topic: "U-tube Manometer",
    atom: "A U-tube manometer measures the difference in pressure between a gas and the atmosphere; the height difference h gives gauge pressure P = hρg",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_pressure_liquid_depth", "phys_pressure_atmospheric"]
  },
  {
    id: "phys_pressure_gas_boyle",
    subject: "physics",
    level: "o_level",
    unit: "Pressure",
    chapter: "Gas Pressure",
    topic: "Boyle's Law",
    atom: "Boyle's Law: at constant temperature, pressure P is inversely proportional to volume V for a fixed mass of gas; P₁V₁ = P₂V₂",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_pressure_gas_kinetic"]
  },
  {
    id: "phys_pressure_gas_kinetic",
    subject: "physics",
    level: "o_level",
    unit: "Pressure",
    chapter: "Gas Pressure",
    topic: "Kinetic Explanation of Gas Pressure",
    atom: "Gas pressure is caused by gas molecules colliding with the walls of the container; reducing volume increases collision frequency, raising pressure (explains Boyle's Law)",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_pressure_gas_boyle", "phys_thermal_kinetic_theory"]
  },
  {
    id: "phys_pressure_hydraulic",
    subject: "physics",
    level: "o_level",
    unit: "Pressure",
    chapter: "Hydraulic Systems",
    topic: "Hydraulic Pressure Transmission",
    atom: "Liquids transmit pressure equally in all directions (Pascal's Principle); in a hydraulic system, pressure at input = pressure at output: F₁/A₁ = F₂/A₂",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_pressure_liquid_direction"]
  },
  {
    id: "phys_pressure_hydraulic_examples",
    subject: "physics",
    level: "o_level",
    unit: "Pressure",
    chapter: "Hydraulic Systems",
    topic: "Hydraulic Examples",
    atom: "Examples of hydraulic systems: car brakes, hydraulic car lift, hydraulic press; in each, a small input force on a small area creates a large force on a larger area",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_pressure_hydraulic"]
  },
  {
    id: "phys_pressure_floating",
    subject: "physics",
    level: "o_level",
    unit: "Pressure",
    chapter: "Pressure in Liquids",
    topic: "Pressure Difference and Upthrust",
    atom: "Upthrust arises because liquid pressure on the bottom face of a submerged object is greater than on the top face; net upward pressure force = upthrust",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_pressure_liquid_depth", "phys_forces_upthrust"]
  },
  {
    id: "phys_pressure_syringe",
    subject: "physics",
    level: "o_level",
    unit: "Pressure",
    chapter: "Gas Pressure",
    topic: "Gas Pressure in a Syringe",
    atom: "If a syringe is sealed and the plunger pushed in (volume decreases at constant temperature), gas pressure increases because molecules hit walls more frequently (Boyle's Law)",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_pressure_gas_boyle", "phys_pressure_gas_kinetic"]
  },
  {
    id: "phys_pressure_temp_gas",
    subject: "physics",
    level: "o_level",
    unit: "Pressure",
    chapter: "Gas Pressure",
    topic: "Pressure-Temperature Law",
    atom: "At constant volume, pressure is proportional to absolute temperature (K): P₁/T₁ = P₂/T₂; increasing temperature increases the speed of molecules, raising pressure",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_pressure_gas_kinetic", "phys_thermal_thermometer_absolute"]
  },
  {
    id: "phys_pressure_sharp",
    subject: "physics",
    level: "o_level",
    unit: "Pressure",
    chapter: "Pressure",
    topic: "Sharp Edges and Pressure",
    atom: "A sharp knife edge has very small area; the same force over a smaller area produces greater pressure (P = F/A), making it easier to cut",
    difficulty: 1,
    examWeight: "low",
    relatedAtoms: ["phys_pressure_def_formula"]
  },
  {
    id: "phys_pressure_communicating_vessels",
    subject: "physics",
    level: "o_level",
    unit: "Pressure",
    chapter: "Pressure in Liquids",
    topic: "Communicating Vessels",
    atom: "In connected vessels containing the same liquid, the liquid level is the same in all vessels regardless of shape; this is because pressure at equal depths must be equal",
    difficulty: 2,
    examWeight: "low",
    relatedAtoms: ["phys_pressure_liquid_depth"]
  },

  // ─────────────────────────────────────────────
  // UNIT 6: THERMAL PHYSICS (~25 atoms)
  // ─────────────────────────────────────────────

  {
    id: "phys_thermal_kinetic_theory",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Kinetic Theory",
    topic: "Kinetic Molecular Model of Matter",
    atom: "All matter is made of tiny particles in constant random motion; the kinetic energy of particles increases with temperature; the arrangement and motion differs in solids, liquids, and gases",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_thermal_states_solid", "phys_thermal_states_liquid", "phys_thermal_states_gas"]
  },
  {
    id: "phys_thermal_states_solid",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Kinetic Theory",
    topic: "Solid State",
    atom: "In a solid, particles are closely packed in fixed positions and can only vibrate about those positions; solids have definite shape and volume, and are incompressible",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_thermal_kinetic_theory"]
  },
  {
    id: "phys_thermal_states_liquid",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Kinetic Theory",
    topic: "Liquid State",
    atom: "In a liquid, particles are close together but can move past each other; liquids take the shape of their container, have a definite volume, and are nearly incompressible",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_thermal_kinetic_theory"]
  },
  {
    id: "phys_thermal_states_gas",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Kinetic Theory",
    topic: "Gas State",
    atom: "In a gas, particles are far apart, move randomly at high speed, and have no fixed positions; gases fill any container and are easily compressed",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_thermal_kinetic_theory"]
  },
  {
    id: "phys_thermal_thermometer_absolute",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Temperature",
    topic: "Absolute Zero and Kelvin Scale",
    atom: "Absolute zero (0 K = −273 °C) is the lowest possible temperature, where particles have minimum kinetic energy; Kelvin temperature T(K) = T(°C) + 273",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_thermal_kinetic_theory"]
  },
  {
    id: "phys_thermal_expansion_solid",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Thermal Expansion",
    topic: "Expansion of Solids",
    atom: "Solids expand on heating because particles vibrate more and the average separation between them increases; different materials expand by different amounts (different expansion coefficients)",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_thermal_kinetic_theory", "phys_thermal_expansion_application"]
  },
  {
    id: "phys_thermal_expansion_application",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Thermal Expansion",
    topic: "Applications of Expansion",
    atom: "Applications of thermal expansion: bimetallic strip (fire alarm, thermostat), expansion joints in bridges and railway tracks, fitting metal rings onto wheels",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_thermal_expansion_solid"]
  },
  {
    id: "phys_thermal_expansion_liquid",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Thermal Expansion",
    topic: "Liquid in Glass Thermometer",
    atom: "A liquid-in-glass thermometer works because the liquid (mercury or alcohol) expands more than the glass on heating; the liquid rises up the capillary tube",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_thermal_expansion_solid"]
  },
  {
    id: "phys_thermal_heat_capacity",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Thermal Properties",
    topic: "Specific Heat Capacity",
    atom: "Specific heat capacity c is the energy required to raise the temperature of 1 kg of a substance by 1 °C (or 1 K); Q = mcΔT; unit is J/(kg °C) or J/(kg K)",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_thermal_heat_cap_water"]
  },
  {
    id: "phys_thermal_heat_cap_water",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Thermal Properties",
    topic: "High SHC of Water",
    atom: "Water has a very high specific heat capacity (4200 J/kg °C); this means it heats and cools slowly, making it useful as a coolant in car engines and as a heat store",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_thermal_heat_capacity"]
  },
  {
    id: "phys_thermal_latent_fusion",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Thermal Properties",
    topic: "Specific Latent Heat of Fusion",
    atom: "Specific latent heat of fusion lf is the energy needed to change 1 kg of solid to liquid at constant temperature; Q = mlf; temperature does not change during melting",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_thermal_latent_vaporisation"]
  },
  {
    id: "phys_thermal_latent_vaporisation",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Thermal Properties",
    topic: "Specific Latent Heat of Vaporisation",
    atom: "Specific latent heat of vaporisation lv is the energy needed to change 1 kg of liquid to vapour at constant temperature; Q = mlv; lv of water is much larger than lf",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_thermal_latent_fusion"]
  },
  {
    id: "phys_thermal_latent_kinetic",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Thermal Properties",
    topic: "Latent Heat and Kinetic Theory",
    atom: "During a change of state, energy input increases potential energy (breaks intermolecular bonds) not kinetic energy; temperature remains constant during the phase change",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_thermal_latent_fusion", "phys_thermal_kinetic_theory"]
  },
  {
    id: "phys_thermal_evaporation",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Thermal Properties",
    topic: "Evaporation vs Boiling",
    atom: "Evaporation occurs at the liquid surface at any temperature; faster molecules escape, leaving cooler liquid behind (cooling effect); boiling occurs throughout the liquid at a fixed boiling point",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_thermal_latent_vaporisation"]
  },
  {
    id: "phys_thermal_evap_factors",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Thermal Properties",
    topic: "Factors Affecting Evaporation Rate",
    atom: "Evaporation rate increases with higher temperature, larger surface area, lower humidity, and increased air flow over the surface",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_thermal_evaporation"]
  },
  {
    id: "phys_thermal_conduction_def",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Heat Transfer",
    topic: "Thermal Conduction",
    atom: "Conduction is the transfer of heat energy through a material without bulk movement of the material; in metals, free electrons carry energy efficiently; non-metals conduct poorly",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_thermal_convection_def", "phys_thermal_radiation_def"]
  },
  {
    id: "phys_thermal_convection_def",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Heat Transfer",
    topic: "Thermal Convection",
    atom: "Convection is heat transfer by the bulk movement of a fluid (liquid or gas); heated fluid becomes less dense and rises; cooler fluid sinks, setting up convection currents",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_thermal_conduction_def"]
  },
  {
    id: "phys_thermal_radiation_def",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Heat Transfer",
    topic: "Thermal Radiation",
    atom: "Thermal radiation is the transfer of energy as infrared electromagnetic waves; it can travel through a vacuum; all objects emit radiation, more intensely at higher temperatures",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_thermal_conduction_def"]
  },
  {
    id: "phys_thermal_radiation_surface",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Heat Transfer",
    topic: "Emission and Absorption of Radiation",
    atom: "Dull black surfaces are the best emitters AND best absorbers of thermal radiation; shiny silver surfaces are the poorest emitters and poorest absorbers (best reflectors)",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_thermal_radiation_def"]
  },
  {
    id: "phys_thermal_vacuum_flask",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Heat Transfer",
    topic: "Vacuum Flask",
    atom: "A vacuum flask reduces all three types of heat transfer: the vacuum between double walls stops conduction and convection; silvered walls reduce radiation",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_thermal_conduction_def", "phys_thermal_convection_def", "phys_thermal_radiation_def"]
  },
  {
    id: "phys_thermal_greenhouse",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Heat Transfer",
    topic: "Greenhouse Effect",
    atom: "The greenhouse effect: glass allows short-wave solar radiation in but absorbs and re-emits the longer-wave infrared from the warm interior, trapping heat inside",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_thermal_radiation_def"]
  },
  {
    id: "phys_thermal_home_insulation",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Heat Transfer",
    topic: "Home Insulation",
    atom: "Methods of reducing home heat loss: loft insulation (traps air, reduces conduction/convection), cavity wall insulation (reduces convection), double glazing (air gap reduces conduction), draught-proofing",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_thermal_conduction_def", "phys_thermal_convection_def"]
  },
  {
    id: "phys_thermal_cooling_curve",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Thermal Properties",
    topic: "Heating and Cooling Curves",
    atom: "On a heating curve, temperature rises then plateaus at melting point (solid→liquid), rises again then plateaus at boiling point (liquid→gas); plateaus indicate latent heat",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_thermal_latent_fusion", "phys_thermal_latent_vaporisation"]
  },
  {
    id: "phys_thermal_bimetallic",
    subject: "physics",
    level: "o_level",
    unit: "Thermal Physics",
    chapter: "Thermal Expansion",
    topic: "Bimetallic Strip",
    atom: "A bimetallic strip consists of two metals bonded together that expand by different amounts when heated; it bends toward the metal with the smaller expansion coefficient",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_thermal_expansion_solid", "phys_thermal_expansion_application"]
  },

  // ─────────────────────────────────────────────
  // UNIT 7: WAVES AND SOUND (~20 atoms)
  // ─────────────────────────────────────────────

  {
    id: "phys_waves_def_transverse",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Wave Properties",
    topic: "Transverse Waves",
    atom: "In a transverse wave, particles oscillate perpendicular to the direction of wave travel; examples include all electromagnetic waves and waves on a rope or string",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_waves_def_longitudinal"]
  },
  {
    id: "phys_waves_def_longitudinal",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Wave Properties",
    topic: "Longitudinal Waves",
    atom: "In a longitudinal wave, particles oscillate parallel to the direction of wave travel; sound is a longitudinal wave consisting of compressions and rarefactions",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_waves_def_transverse", "phys_waves_sound_speed"]
  },
  {
    id: "phys_waves_equation",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Wave Properties",
    topic: "Wave Equation",
    atom: "Wave speed v = fλ where f is frequency (Hz) and λ is wavelength (m); also v = distance / time; this applies to all types of wave",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_waves_def_transverse", "phys_waves_frequency_period"]
  },
  {
    id: "phys_waves_frequency_period",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Wave Properties",
    topic: "Frequency and Period",
    atom: "Frequency f = 1/T where T is the period (time for one complete oscillation) in seconds; frequency is measured in hertz (Hz) = cycles per second",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_waves_equation"]
  },
  {
    id: "phys_waves_amplitude_energy",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Wave Properties",
    topic: "Amplitude and Energy",
    atom: "Amplitude is the maximum displacement of a particle from its equilibrium position; energy carried by a wave is proportional to the square of its amplitude",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_waves_equation"]
  },
  {
    id: "phys_waves_reflection",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Wave Behaviour",
    topic: "Reflection of Waves",
    atom: "Waves are reflected at a boundary; angle of incidence = angle of reflection (measured from the normal); wavelength, frequency, and speed do not change on reflection",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_waves_refraction"]
  },
  {
    id: "phys_waves_refraction",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Wave Behaviour",
    topic: "Refraction of Waves",
    atom: "Refraction occurs when waves change speed on entering a new medium; frequency remains constant, but wavelength and speed change; the direction changes unless waves hit the boundary at 90°",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_waves_reflection"]
  },
  {
    id: "phys_waves_diffraction",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Wave Behaviour",
    topic: "Diffraction of Waves",
    atom: "Diffraction is the spreading of waves around the edges of an obstacle or through a gap; diffraction is most pronounced when the gap width is equal to the wavelength",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_waves_refraction"]
  },
  {
    id: "phys_waves_sound_speed",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Sound",
    topic: "Speed of Sound",
    atom: "Sound travels at approximately 340 m/s in air at room temperature; speed of sound is greater in liquids than gases and greatest in solids; sound cannot travel through a vacuum",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_waves_def_longitudinal"]
  },
  {
    id: "phys_waves_sound_pitch",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Sound",
    topic: "Pitch and Loudness",
    atom: "Pitch of a sound depends on frequency (higher frequency = higher pitch); loudness depends on amplitude (larger amplitude = louder sound); measured in decibels (dB)",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_waves_amplitude_energy", "phys_waves_frequency_period"]
  },
  {
    id: "phys_waves_sound_echo",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Sound",
    topic: "Echo and Reverberation",
    atom: "An echo is a reflected sound heard after a time delay; if the reflecting surface is less than 17 m away, the echo merges with the original sound producing reverberation",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_waves_reflection", "phys_waves_sound_speed"]
  },
  {
    id: "phys_waves_sound_hearing",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Sound",
    topic: "Audible Range",
    atom: "The human ear can detect frequencies between 20 Hz and 20 000 Hz (20 kHz); frequencies above 20 kHz are called ultrasound; below 20 Hz is infrasound",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_waves_ultrasound"]
  },
  {
    id: "phys_waves_ultrasound",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Sound",
    topic: "Ultrasound Applications",
    atom: "Ultrasound (>20 kHz) is used in medical scanning (foetal imaging, detecting tumours), sonar (measuring ocean depth), and detecting cracks in metal",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_waves_sound_hearing", "phys_waves_sonar"]
  },
  {
    id: "phys_waves_sonar",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Sound",
    topic: "SONAR Calculation",
    atom: "SONAR measures ocean depth using d = vt/2 where v is speed of sound in water (~1500 m/s) and t is the time for the pulse to travel to the seabed and back",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_waves_ultrasound", "phys_waves_sound_speed"]
  },
  {
    id: "phys_waves_em_spectrum",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Electromagnetic Spectrum",
    topic: "EM Spectrum Order",
    atom: "The electromagnetic spectrum in order of increasing frequency (decreasing wavelength): radio waves, microwaves, infrared, visible light, ultraviolet, X-rays, gamma rays",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_waves_em_speed", "phys_waves_em_properties"]
  },
  {
    id: "phys_waves_em_speed",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Electromagnetic Spectrum",
    topic: "Speed of EM Waves",
    atom: "All electromagnetic waves travel at the same speed in a vacuum: c = 3 × 10⁸ m/s; they are all transverse waves and can travel through a vacuum",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_waves_em_spectrum"]
  },
  {
    id: "phys_waves_em_properties",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Electromagnetic Spectrum",
    topic: "EM Wave Uses and Dangers",
    atom: "Radio: broadcasting; microwaves: cooking/communication; IR: remote controls/thermal imaging; UV: sterilisation/causes sunburn; X-rays: medical imaging; gamma: cancer treatment/sterilisation",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_waves_em_spectrum"]
  },
  {
    id: "phys_waves_ripple_tank",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Wave Behaviour",
    topic: "Ripple Tank Experiments",
    atom: "A ripple tank demonstrates reflection, refraction, and diffraction of water waves; shallow water slows waves (shorter wavelength), deeper water speeds them up",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_waves_reflection", "phys_waves_refraction", "phys_waves_diffraction"]
  },
  {
    id: "phys_waves_sound_medium",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Sound",
    topic: "Sound Needs a Medium",
    atom: "Sound requires a material medium to travel; it cannot travel through a vacuum because there are no particles to carry the vibrations (demonstrated by bell jar experiment)",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_waves_sound_speed"]
  },
  {
    id: "phys_waves_oscilloscope",
    subject: "physics",
    level: "o_level",
    unit: "Waves and Sound",
    chapter: "Sound",
    topic: "Oscilloscope Display of Sound",
    atom: "A CRO (cathode ray oscilloscope) displays sound as a transverse waveform; the height of the wave shows amplitude (loudness) and the number of waves per unit length shows frequency (pitch)",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_waves_sound_pitch", "phys_waves_amplitude_energy"]
  },

  // ─────────────────────────────────────────────
  // UNIT 8: LIGHT (~20 atoms)
  // ─────────────────────────────────────────────

  {
    id: "phys_light_reflection_law",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "Reflection",
    topic: "Laws of Reflection",
    atom: "Law of reflection: (1) angle of incidence = angle of reflection; (2) the incident ray, reflected ray, and normal all lie in the same plane; angles measured from the normal",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_light_plane_mirror"]
  },
  {
    id: "phys_light_plane_mirror",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "Reflection",
    topic: "Plane Mirror Image",
    atom: "A plane mirror produces an image that is: virtual (cannot be projected), upright, same size as the object, laterally inverted, and as far behind the mirror as the object is in front",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_light_reflection_law"]
  },
  {
    id: "phys_light_refraction_law",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "Refraction",
    topic: "Laws of Refraction",
    atom: "When light enters a denser medium it slows down and bends toward the normal; when it enters a less dense medium it speeds up and bends away from the normal; frequency stays constant",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_light_snell"]
  },
  {
    id: "phys_light_snell",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "Refraction",
    topic: "Snell's Law",
    atom: "Snell's Law: n₁ sin θ₁ = n₂ sin θ₂; refractive index n = sin(angle of incidence) / sin(angle of refraction) = c / v (speed in vacuum / speed in medium)",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_light_refraction_law", "phys_light_tir"]
  },
  {
    id: "phys_light_tir",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "Total Internal Reflection",
    topic: "Conditions for TIR",
    atom: "Total internal reflection (TIR) occurs when: (1) light travels from a denser to a less dense medium AND (2) the angle of incidence exceeds the critical angle",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_light_snell", "phys_light_critical_angle"]
  },
  {
    id: "phys_light_critical_angle",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "Total Internal Reflection",
    topic: "Critical Angle Formula",
    atom: "At the critical angle c, the refracted ray emerges along the boundary (90°); sin c = 1/n where n is the refractive index of the denser medium relative to air",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_light_tir"]
  },
  {
    id: "phys_light_tir_applications",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "Total Internal Reflection",
    topic: "Applications of TIR",
    atom: "TIR applications: optical fibres (telecommunications, medical endoscopes), periscope prisms (45° glass prisms), reflective road studs (cat's eyes)",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_light_tir"]
  },
  {
    id: "phys_light_optical_fibre",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "Total Internal Reflection",
    topic: "Optical Fibre",
    atom: "In an optical fibre, light enters the glass core and repeatedly undergoes TIR at the core-cladding boundary; cladding has a lower refractive index than the core",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_light_tir_applications"]
  },
  {
    id: "phys_light_convex_lens_terms",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "Lenses",
    topic: "Lens Terminology",
    atom: "Principal axis: line through the centre of a lens; focal point F: point where parallel rays converge after passing through a convex lens; focal length f: distance from lens to F",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_light_convex_lens_rays"]
  },
  {
    id: "phys_light_convex_lens_rays",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "Lenses",
    topic: "Ray Diagrams for Convex Lens",
    atom: "Three key rays for a convex (converging) lens: (1) parallel ray refracts through F; (2) ray through centre passes straight; (3) ray through F emerges parallel to the axis",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_light_convex_lens_images"]
  },
  {
    id: "phys_light_convex_lens_images",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "Lenses",
    topic: "Images Formed by Convex Lens",
    atom: "Object beyond 2F: real, inverted, diminished image (camera); at 2F: real, inverted, same size; between F and 2F: real, inverted, magnified (projector); inside F: virtual, upright, magnified (magnifying glass)",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_light_convex_lens_rays"]
  },
  {
    id: "phys_light_eye",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "The Eye",
    topic: "Parts of the Eye",
    atom: "In the human eye: cornea and lens refract light; iris controls light entering (pupil size); retina detects light; optic nerve sends signal to brain; ciliary muscles adjust lens shape (accommodation)",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_light_eye_defects"]
  },
  {
    id: "phys_light_eye_defects",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "The Eye",
    topic: "Sight Defects and Correction",
    atom: "Short sight (myopia): image forms in front of retina; corrected with diverging (concave) lens; long sight (hyperopia): image forms behind retina; corrected with converging (convex) lens",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_light_eye"]
  },
  {
    id: "phys_light_dispersion",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "Colour and Dispersion",
    topic: "Dispersion of White Light",
    atom: "White light disperses into a spectrum (ROYGBIV) when it passes through a prism because different colours have different refractive indices; violet refracts most, red least",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_light_refraction_law"]
  },
  {
    id: "phys_light_colour_filter",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "Colour and Dispersion",
    topic: "Colour Filters and Objects",
    atom: "A colour filter transmits its own colour and absorbs all others; a coloured object reflects its own colour and absorbs all others; in darkness, coloured objects appear black",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_light_dispersion"]
  },
  {
    id: "phys_light_primary_colours",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "Colour and Dispersion",
    topic: "Primary Colours of Light",
    atom: "The primary colours of light are red, green, and blue; mixing all three gives white light; mixing pairs: red+green=yellow, red+blue=magenta, green+blue=cyan (secondary colours)",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_light_colour_filter"]
  },
  {
    id: "phys_light_speed_medium",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "Refraction",
    topic: "Speed of Light in a Medium",
    atom: "The speed of light in a medium v = c/n where c = 3 × 10⁸ m/s and n is the refractive index; light slows down in denser optical media (n > 1)",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_light_snell"]
  },
  {
    id: "phys_light_shadow",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "Reflection",
    topic: "Shadows and Rectilinear Propagation",
    atom: "Light travels in straight lines (rectilinear propagation); a point source produces a sharp shadow (umbra); an extended source produces a partial shadow (penumbra) and full shadow (umbra)",
    difficulty: 1,
    examWeight: "low",
    relatedAtoms: []
  },
  {
    id: "phys_light_pinhole_camera",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "Reflection",
    topic: "Pinhole Camera",
    atom: "A pinhole camera produces an image that is inverted, real, and smaller than the object; image size / object size = image distance / object distance",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_light_shadow"]
  },
  {
    id: "phys_light_lens_formula",
    subject: "physics",
    level: "o_level",
    unit: "Light",
    chapter: "Lenses",
    topic: "Magnification",
    atom: "Linear magnification m = image height / object height = image distance / object distance; magnification > 1 means magnified, < 1 means diminished",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_light_convex_lens_images"]
  },

  // ─────────────────────────────────────────────
  // UNIT 9: ELECTRICITY (~30 atoms)
  // ─────────────────────────────────────────────

  {
    id: "phys_elec_charge_static",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Static Electricity",
    topic: "Electric Charge",
    atom: "There are two types of charge: positive and negative; like charges repel, unlike charges attract; charge is measured in coulombs (C); an electron has charge −1.6 × 10⁻¹⁹ C",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_elec_charge_induced"]
  },
  {
    id: "phys_elec_charge_induced",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Static Electricity",
    topic: "Charging by Induction",
    atom: "Charging by induction: a charged object brought near a conductor causes charge redistribution; earthing removes one sign of charge; when the charged object is removed, the conductor is left charged with the opposite sign",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_elec_charge_static"]
  },
  {
    id: "phys_elec_current_def",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Current Electricity",
    topic: "Electric Current",
    atom: "Electric current I = Q/t where Q is charge (C) and t is time (s); unit is ampere (A); conventional current flows from + to −; electron flow is from − to +",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_elec_pd_def"]
  },
  {
    id: "phys_elec_pd_def",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Current Electricity",
    topic: "Potential Difference",
    atom: "Potential difference (voltage) V is the energy transferred per unit charge; V = W/Q where W is work done (J) and Q is charge (C); unit is volt (V) = J/C",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_elec_current_def", "phys_elec_ohm"]
  },
  {
    id: "phys_elec_ohm",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Resistance",
    topic: "Ohm's Law",
    atom: "Ohm's Law: V = IR (voltage = current × resistance) provided temperature is constant; an ohmic conductor has constant resistance (straight line on V-I graph through origin)",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_elec_pd_def", "phys_elec_resistance_factors"]
  },
  {
    id: "phys_elec_resistance_factors",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Resistance",
    topic: "Factors Affecting Resistance",
    atom: "Resistance of a wire increases with: greater length, smaller cross-sectional area, higher temperature, and material type; R = ρL/A where ρ is resistivity",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_elec_ohm"]
  },
  {
    id: "phys_elec_series_current",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Series and Parallel Circuits",
    topic: "Current in Series",
    atom: "In a series circuit, the current is the same at every point; adding more components in series increases total resistance and reduces current",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_elec_series_voltage", "phys_elec_parallel_current"]
  },
  {
    id: "phys_elec_series_voltage",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Series and Parallel Circuits",
    topic: "Voltage in Series",
    atom: "In a series circuit, the supply voltage is shared (divided) between components; V_total = V₁ + V₂ + V₃; each component has a voltage proportional to its resistance",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_elec_series_current"]
  },
  {
    id: "phys_elec_series_resistance",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Series and Parallel Circuits",
    topic: "Resistance in Series",
    atom: "Total resistance in series: R_total = R₁ + R₂ + R₃; the total resistance is always greater than the largest individual resistance",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_elec_series_current"]
  },
  {
    id: "phys_elec_parallel_current",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Series and Parallel Circuits",
    topic: "Current in Parallel",
    atom: "In a parallel circuit, the total current from the supply equals the sum of currents through each branch: I_total = I₁ + I₂ + I₃",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_elec_parallel_voltage", "phys_elec_series_current"]
  },
  {
    id: "phys_elec_parallel_voltage",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Series and Parallel Circuits",
    topic: "Voltage in Parallel",
    atom: "In a parallel circuit, the voltage (p.d.) across each parallel branch is the same and equals the supply voltage",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_elec_parallel_current"]
  },
  {
    id: "phys_elec_parallel_resistance",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Series and Parallel Circuits",
    topic: "Resistance in Parallel",
    atom: "Total resistance in parallel: 1/R_total = 1/R₁ + 1/R₂ + 1/R₃; the total resistance is always less than the smallest individual resistance",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_elec_parallel_current"]
  },
  {
    id: "phys_elec_power_formula",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Electrical Power",
    topic: "Electrical Power Formulas",
    atom: "Electrical power P = IV = I²R = V²/R; unit is watt (W); energy transferred E = Pt = IVt; heating effect in a resistor is P = I²R",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_elec_ohm", "phys_energy_power_formula"]
  },
  {
    id: "phys_elec_heating_effect",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Electrical Power",
    topic: "Heating Effect of Current",
    atom: "When current flows through a resistor, electrical energy is converted to heat; Q = I²Rt where Q is heat produced (J), I is current (A), R is resistance (Ω), t is time (s)",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_elec_power_formula"]
  },
  {
    id: "phys_elec_fuse",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Safety",
    topic: "Fuse Operation",
    atom: "A fuse contains a thin wire that melts (breaks the circuit) when current exceeds its rated value; it protects the appliance cable from overheating and catching fire",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_elec_heating_effect", "phys_elec_earth_wire"]
  },
  {
    id: "phys_elec_earth_wire",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Safety",
    topic: "Earth Wire and MCB",
    atom: "The earth wire connects the metal case of an appliance to the ground; if the live wire touches the case, a large current flows to earth, blowing the fuse; MCBs trip automatically and can be reset",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_elec_fuse"]
  },
  {
    id: "phys_elec_mains_wiring",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Safety",
    topic: "Mains Cable Wiring",
    atom: "Three-core mains cable: live (brown) at ~230 V AC, neutral (blue) at 0 V, earth (yellow-green) at 0 V; the fuse and switch are always connected in the live wire",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_elec_earth_wire"]
  },
  {
    id: "phys_elec_ac_dc",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Current Electricity",
    topic: "AC vs DC",
    atom: "Direct current (DC) flows in one direction only (batteries, cells); alternating current (AC) reverses direction periodically; UK mains is 230 V AC at 50 Hz",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_elec_current_def"]
  },
  {
    id: "phys_elec_thermistor",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Resistance",
    topic: "Thermistor",
    atom: "An NTC thermistor's resistance decreases as temperature increases; used in temperature sensors; on a V-I graph it is non-ohmic (curved, not straight through origin)",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_elec_ldr"]
  },
  {
    id: "phys_elec_ldr",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Resistance",
    topic: "Light-Dependent Resistor",
    atom: "An LDR's resistance decreases as light intensity increases; used in automatic lighting circuits; in darkness, resistance is very high (~MΩ); in bright light, resistance is very low (~100 Ω)",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_elec_thermistor"]
  },
  {
    id: "phys_elec_diode",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Resistance",
    topic: "Semiconductor Diode",
    atom: "A diode allows current in one direction only (forward bias); in reverse bias, resistance is very high and current is negligible; used to convert AC to DC (rectification)",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_elec_ac_dc"]
  },
  {
    id: "phys_elec_emf_internal",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Current Electricity",
    topic: "EMF and Internal Resistance",
    atom: "EMF (ε) is the energy supplied per unit charge by a source; terminal voltage V = ε − Ir where I is current and r is internal resistance; terminal voltage drops as current increases",
    difficulty: 4,
    examWeight: "medium",
    relatedAtoms: ["phys_elec_pd_def"]
  },
  {
    id: "phys_elec_ammeter_voltmeter",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Measuring Electricity",
    topic: "Ammeter and Voltmeter Connection",
    atom: "An ammeter (low resistance) is connected in series to measure current; a voltmeter (high resistance) is connected in parallel to measure potential difference across a component",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_elec_current_def", "phys_elec_pd_def"]
  },
  {
    id: "phys_elec_voltage_divider",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Series and Parallel Circuits",
    topic: "Potential Divider",
    atom: "In a potential divider, two resistors in series share the supply voltage: V_out = V_in × R₂/(R₁ + R₂); used with thermistors and LDRs as sensing circuits",
    difficulty: 4,
    examWeight: "high",
    relatedAtoms: ["phys_elec_series_voltage", "phys_elec_thermistor", "phys_elec_ldr"]
  },
  {
    id: "phys_elec_charge_conservation",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Current Electricity",
    topic: "Kirchhoff's Current Law",
    atom: "At any junction in a circuit, the sum of currents entering equals the sum of currents leaving; this is a consequence of conservation of charge",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_elec_parallel_current"]
  },
  {
    id: "phys_elec_static_applications",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Static Electricity",
    topic: "Applications of Static Electricity",
    atom: "Applications: electrostatic precipitators (remove smoke particles), spray painting (charged paint attracted to grounded object), photocopiers and laser printers",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_elec_charge_static"]
  },
  {
    id: "phys_elec_static_hazards",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Static Electricity",
    topic: "Hazards of Static Electricity",
    atom: "Static electricity can cause sparks that ignite fuel vapour; prevented by earthing fuel tankers when filling aircraft or vehicles; lightning conductors earth charge from clouds",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_elec_charge_static"]
  },
  {
    id: "phys_elec_filament_lamp",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Resistance",
    topic: "Filament Lamp V-I Characteristic",
    atom: "A filament lamp is non-ohmic; as temperature increases with current, resistance increases; the V-I graph curves upward (resistance is not constant)",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_elec_ohm", "phys_elec_resistance_factors"]
  },
  {
    id: "phys_elec_relay",
    subject: "physics",
    level: "o_level",
    unit: "Electricity",
    chapter: "Magnetism",
    topic: "Relay Switch",
    atom: "A relay uses a small current in an electromagnet to switch a separate, high-current circuit on or off; it allows a low-voltage circuit to safely control a high-voltage circuit",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_mag_electromagnet"]
  },

  // ─────────────────────────────────────────────
  // UNIT 10: MAGNETISM AND ELECTROMAGNETISM (~20 atoms)
  // ─────────────────────────────────────────────

  {
    id: "phys_mag_properties",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Magnets",
    topic: "Properties of Magnets",
    atom: "Magnetic poles always exist in pairs (north and south); like poles repel, unlike poles attract; a freely suspended magnet aligns with Earth's magnetic field (compass)",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_mag_fieldlines"]
  },
  {
    id: "phys_mag_fieldlines",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Magnets",
    topic: "Magnetic Field Lines",
    atom: "Magnetic field lines run from north to south outside the magnet; they never cross; close, parallel lines indicate a strong, uniform field; lines spread apart in a weaker region",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_mag_properties"]
  },
  {
    id: "phys_mag_materials",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Magnets",
    topic: "Magnetic Materials",
    atom: "Ferromagnetic materials (iron, steel, nickel, cobalt) are attracted to magnets and can be magnetised; iron is a soft magnetic material (easy to magnetise/demagnetise); steel is hard (retains magnetism)",
    difficulty: 1,
    examWeight: "medium",
    relatedAtoms: ["phys_mag_induced"]
  },
  {
    id: "phys_mag_induced",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Magnets",
    topic: "Induced Magnetism",
    atom: "When a magnetic material is placed in a magnetic field, it becomes temporarily magnetised (induced magnetism); the end nearest the magnet's north pole becomes a south pole",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_mag_materials"]
  },
  {
    id: "phys_mag_current_field",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Electromagnetism",
    topic: "Magnetic Field Around a Wire",
    atom: "A current-carrying conductor produces a circular magnetic field around it; the direction is given by the right-hand grip rule: wrap fingers in direction of field, thumb points in direction of current",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_mag_solenoid_field"]
  },
  {
    id: "phys_mag_solenoid_field",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Electromagnetism",
    topic: "Solenoid Magnetic Field",
    atom: "A solenoid (coil of wire carrying current) produces a field similar to a bar magnet; field inside is uniform and strong; the end where current flows anticlockwise is the north pole",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_mag_current_field", "phys_mag_electromagnet"]
  },
  {
    id: "phys_mag_electromagnet",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Electromagnetism",
    topic: "Electromagnet Strength",
    atom: "Electromagnet strength increases with: more turns of wire, larger current, soft-iron core; it can be switched on/off unlike a permanent magnet; used in cranes, relays, loudspeakers",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_mag_solenoid_field"]
  },
  {
    id: "phys_mag_force_on_wire",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Motor Effect",
    topic: "Force on a Current-Carrying Wire",
    atom: "A current-carrying conductor in a magnetic field experiences a force (motor effect); F = BIL where B is magnetic flux density (T), I is current (A), L is length in field (m)",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_mag_flemings_left"]
  },
  {
    id: "phys_mag_flemings_left",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Motor Effect",
    topic: "Fleming's Left-Hand Rule",
    atom: "Fleming's Left-Hand Rule gives the direction of the motor force: thumb = force (motion), first finger = field (N→S), second finger = conventional current; the three are mutually perpendicular",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_mag_force_on_wire"]
  },
  {
    id: "phys_mag_dc_motor",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Motor Effect",
    topic: "DC Electric Motor",
    atom: "A DC motor has a coil in a magnetic field; a commutator reverses the current direction every half turn, ensuring the coil always turns the same way; motor speed increased by more turns, stronger field, or greater current",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_mag_flemings_left"]
  },
  {
    id: "phys_mag_induction_def",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Electromagnetic Induction",
    topic: "Faraday's Law",
    atom: "Electromagnetic induction: an EMF is induced in a conductor when there is a change in magnetic flux linking it (Faraday's Law); the induced EMF drives a current if the circuit is closed",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_mag_lenz"]
  },
  {
    id: "phys_mag_lenz",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Electromagnetic Induction",
    topic: "Lenz's Law",
    atom: "Lenz's Law: the induced current flows in a direction that opposes the change causing it (conservation of energy); increasing the flux induces a current that creates a field opposing the increase",
    difficulty: 4,
    examWeight: "medium",
    relatedAtoms: ["phys_mag_induction_def"]
  },
  {
    id: "phys_mag_induction_increase",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Electromagnetic Induction",
    topic: "Increasing Induced EMF",
    atom: "The induced EMF is increased by: moving the conductor faster, using a stronger magnet, increasing the number of turns in the coil, using a soft-iron core",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_mag_induction_def"]
  },
  {
    id: "phys_mag_ac_generator",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Electromagnetic Induction",
    topic: "AC Generator",
    atom: "An AC generator (alternator) uses slip rings so the coil rotates continuously; it produces alternating EMF that varies sinusoidally; a DC generator uses a commutator to produce pulsed DC",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_mag_induction_def"]
  },
  {
    id: "phys_mag_transformer_def",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Transformers",
    topic: "Transformer Action",
    atom: "A transformer works by electromagnetic induction; an AC in the primary coil creates a changing magnetic flux in the iron core, inducing an AC EMF in the secondary coil",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_mag_induction_def", "phys_mag_transformer_ratio"]
  },
  {
    id: "phys_mag_transformer_ratio",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Transformers",
    topic: "Transformer Ratio",
    atom: "Turns ratio equation: V_s/V_p = N_s/N_p; for a 100% efficient transformer: V_p I_p = V_s I_s (power in = power out); step-up transformer has N_s > N_p",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_mag_transformer_def"]
  },
  {
    id: "phys_mag_transformer_power",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Transformers",
    topic: "Transformers in Power Transmission",
    atom: "Electricity is transmitted at high voltage (low current) to reduce power lost as heat (P = I²R) in cables; step-up transformers increase voltage before transmission; step-down transformers reduce it for homes",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_mag_transformer_ratio", "phys_elec_power_formula"]
  },
  {
    id: "phys_mag_flemings_right",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Electromagnetic Induction",
    topic: "Fleming's Right-Hand Rule",
    atom: "Fleming's Right-Hand Rule gives the direction of the induced current in a generator: thumb = motion, first finger = field, second finger = induced current (generator rule)",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_mag_induction_def", "phys_mag_flemings_left"]
  },
  {
    id: "phys_mag_earth_field",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Magnets",
    topic: "Earth's Magnetic Field",
    atom: "Earth acts as a giant magnet; its geographic north pole is near the magnetic south pole (so a compass north pole points toward it); field lines run from south to north inside Earth",
    difficulty: 2,
    examWeight: "low",
    relatedAtoms: ["phys_mag_properties"]
  },
  {
    id: "phys_mag_loudspeaker",
    subject: "physics",
    level: "o_level",
    unit: "Magnetism and Electromagnetism",
    chapter: "Motor Effect",
    topic: "Loudspeaker",
    atom: "In a loudspeaker, an AC signal through a coil in a permanent magnetic field produces a varying force (motor effect); the coil vibrates and moves a cone to produce sound waves",
    difficulty: 3,
    examWeight: "medium",
    relatedAtoms: ["phys_mag_force_on_wire"]
  },

  // ─────────────────────────────────────────────
  // UNIT 11: ATOMIC PHYSICS (~15 atoms)
  // ─────────────────────────────────────────────

  {
    id: "phys_atom_structure",
    subject: "physics",
    level: "o_level",
    unit: "Atomic Physics",
    chapter: "The Atom",
    topic: "Nuclear Model of the Atom",
    atom: "An atom has a tiny, dense, positively-charged nucleus (protons and neutrons) surrounded by negatively-charged electrons in orbits; most of the atom is empty space",
    difficulty: 1,
    examWeight: "high",
    relatedAtoms: ["phys_atom_notation"]
  },
  {
    id: "phys_atom_notation",
    subject: "physics",
    level: "o_level",
    unit: "Atomic Physics",
    chapter: "The Atom",
    topic: "Nuclide Notation",
    atom: "Nuclear notation: ᴬ_Z X where A is the mass number (protons + neutrons) and Z is the proton number (atomic number); number of neutrons = A − Z",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_atom_structure", "phys_atom_isotopes"]
  },
  {
    id: "phys_atom_isotopes",
    subject: "physics",
    level: "o_level",
    unit: "Atomic Physics",
    chapter: "The Atom",
    topic: "Isotopes",
    atom: "Isotopes are atoms of the same element with the same proton number but different numbers of neutrons (different mass number); they have the same chemical properties but different physical properties",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_atom_notation"]
  },
  {
    id: "phys_atom_alpha",
    subject: "physics",
    level: "o_level",
    unit: "Atomic Physics",
    chapter: "Radioactivity",
    topic: "Alpha Particle",
    atom: "An alpha particle (α) consists of 2 protons + 2 neutrons (identical to a helium-4 nucleus); it has charge +2; it is the least penetrating but most ionising radiation; stopped by a few cm of air or paper",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_atom_beta", "phys_atom_gamma"]
  },
  {
    id: "phys_atom_beta",
    subject: "physics",
    level: "o_level",
    unit: "Atomic Physics",
    chapter: "Radioactivity",
    topic: "Beta Particle",
    atom: "A beta particle (β) is a fast-moving electron emitted from the nucleus when a neutron converts to a proton + electron; charge −1; penetrates further than alpha; stopped by a few mm of aluminium",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_atom_alpha", "phys_atom_gamma"]
  },
  {
    id: "phys_atom_gamma",
    subject: "physics",
    level: "o_level",
    unit: "Atomic Physics",
    chapter: "Radioactivity",
    topic: "Gamma Radiation",
    atom: "Gamma radiation (γ) is a high-frequency electromagnetic wave; it has no charge and no mass; it is the most penetrating but least ionising radiation; significantly reduced by thick lead or concrete",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_atom_alpha", "phys_atom_beta"]
  },
  {
    id: "phys_atom_decay_equations",
    subject: "physics",
    level: "o_level",
    unit: "Atomic Physics",
    chapter: "Radioactivity",
    topic: "Decay Equations",
    atom: "In alpha decay, A decreases by 4 and Z decreases by 2; in beta decay, A stays the same and Z increases by 1; mass number and proton number are both conserved in all nuclear equations",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_atom_alpha", "phys_atom_beta", "phys_atom_notation"]
  },
  {
    id: "phys_atom_half_life_def",
    subject: "physics",
    level: "o_level",
    unit: "Atomic Physics",
    chapter: "Radioactivity",
    topic: "Half-Life Definition",
    atom: "Half-life T½ is the time for the activity (or number of undecayed nuclei) of a radioactive sample to fall to half its initial value; it is constant and unaffected by physical or chemical conditions",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_atom_half_life_calc"]
  },
  {
    id: "phys_atom_half_life_calc",
    subject: "physics",
    level: "o_level",
    unit: "Atomic Physics",
    chapter: "Radioactivity",
    topic: "Half-Life Calculation",
    atom: "After n half-lives, the activity or amount remaining = N₀ × (½)ⁿ; e.g. after 3 half-lives, 1/8 of the original activity remains",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_atom_half_life_def"]
  },
  {
    id: "phys_atom_random",
    subject: "physics",
    level: "o_level",
    unit: "Atomic Physics",
    chapter: "Radioactivity",
    topic: "Random Nature of Decay",
    atom: "Radioactive decay is spontaneous and random; it cannot be predicted which nucleus will decay next and cannot be controlled by temperature, pressure, or chemical environment",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_atom_half_life_def"]
  },
  {
    id: "phys_atom_background",
    subject: "physics",
    level: "o_level",
    unit: "Atomic Physics",
    chapter: "Radioactivity",
    topic: "Background Radiation",
    atom: "Background radiation is always present from natural sources (cosmic rays, radon gas, rocks, food) and artificial sources (medical X-rays, nuclear industry); it must be subtracted from measured activity",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_atom_random"]
  },
  {
    id: "phys_atom_ionisation",
    subject: "physics",
    level: "o_level",
    unit: "Atomic Physics",
    chapter: "Radioactivity",
    topic: "Ionisation by Radiation",
    atom: "Alpha, beta, and gamma radiation ionise atoms by removing electrons; alpha is the most strongly ionising (charge +2, low speed, large), gamma is the least ionising; ionisation can damage living cells and DNA",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_atom_alpha", "phys_atom_safety"]
  },
  {
    id: "phys_atom_safety",
    subject: "physics",
    level: "o_level",
    unit: "Atomic Physics",
    chapter: "Radioactivity",
    topic: "Safety Precautions",
    atom: "Radiation safety precautions: use tongs (distance), minimise exposure time, use appropriate shielding (paper for α, aluminium for β, lead for γ), store in lead-lined containers, no eating/drinking in lab",
    difficulty: 2,
    examWeight: "medium",
    relatedAtoms: ["phys_atom_ionisation"]
  },
  {
    id: "phys_atom_uses",
    subject: "physics",
    level: "o_level",
    unit: "Atomic Physics",
    chapter: "Radioactivity",
    topic: "Uses of Radioactivity",
    atom: "Uses of radioactive sources: α in smoke detectors; β to control paper thickness (gamma absorbed too much); γ to treat cancer (radiotherapy), sterilise medical equipment, and trace blood flow; carbon-14 for radiocarbon dating",
    difficulty: 2,
    examWeight: "high",
    relatedAtoms: ["phys_atom_alpha", "phys_atom_beta", "phys_atom_gamma"]
  },
  {
    id: "phys_atom_nuclear_fission",
    subject: "physics",
    level: "o_level",
    unit: "Atomic Physics",
    chapter: "Nuclear Energy",
    topic: "Nuclear Fission",
    atom: "Nuclear fission: a large nucleus (e.g. U-235) absorbs a neutron and splits into two smaller nuclei, releasing 2 or 3 neutrons and a large amount of energy; the released neutrons can trigger a chain reaction",
    difficulty: 3,
    examWeight: "high",
    relatedAtoms: ["phys_atom_structure"]
  }

];
