// ============================================================
// STARKY ATOMS KNOWLEDGE BASE
// Version: 1.0 MVP — 233 atoms across 6 subjects
// Cambridge O Level: Chemistry, Physics, Biology, Mathematics, English
// Cambridge A Level: Economics
//
// EXPANSION PLAN:
// MVP v1 (now):  233 atoms — 6 subjects
// v2 (May 2026): 600 atoms — add History, Computer Science, Accounting
// v3 (Sep 2026): 1,200 atoms — full O Level suite + Urdu
// v4 (2027):     5,000 atoms — all Cambridge O+A Level subjects
// Target 2027:   15,000+ atoms — complete Cambridge atom map
// ============================================================

const STARKY_ATOMS = [

  // ═══ CHEMISTRY O LEVEL — 89 atoms ════════════════════════
  { id:"chem_som_001", subject:"chemistry", level:"o_level", unit:"States of Matter", chapter:"Kinetic Particle Theory", atom:"In a solid, particles are closely packed in fixed positions and vibrate about fixed points.", difficulty:1, examWeight:"high", relatedAtoms:["chem_som_002","chem_som_003"] },
  { id:"chem_som_002", subject:"chemistry", level:"o_level", unit:"States of Matter", chapter:"Kinetic Particle Theory", atom:"In a liquid, particles are close together but can move past each other — no fixed positions.", difficulty:1, examWeight:"high", relatedAtoms:["chem_som_001","chem_som_003"] },
  { id:"chem_som_003", subject:"chemistry", level:"o_level", unit:"States of Matter", chapter:"Kinetic Particle Theory", atom:"In a gas, particles are far apart, move rapidly and randomly in all directions with no fixed positions.", difficulty:1, examWeight:"high", relatedAtoms:["chem_som_001","chem_som_002"] },
  { id:"chem_som_004", subject:"chemistry", level:"o_level", unit:"States of Matter", chapter:"Changes of State", atom:"Melting: solid to liquid. Energy absorbed to overcome forces holding particles in fixed positions.", difficulty:1, examWeight:"high", relatedAtoms:["chem_som_005"] },
  { id:"chem_som_005", subject:"chemistry", level:"o_level", unit:"States of Matter", chapter:"Changes of State", atom:"Boiling: liquid to gas. Energy absorbed to completely overcome intermolecular forces.", difficulty:1, examWeight:"high", relatedAtoms:["chem_som_004","chem_som_006"] },
  { id:"chem_som_006", subject:"chemistry", level:"o_level", unit:"States of Matter", chapter:"Changes of State", atom:"Evaporation occurs at the surface of a liquid below boiling point — faster-moving particles escape.", difficulty:2, examWeight:"high", relatedAtoms:["chem_som_005"] },
  { id:"chem_som_007", subject:"chemistry", level:"o_level", unit:"States of Matter", chapter:"Diffusion", atom:"Diffusion is the net movement of particles from a region of high concentration to low concentration.", difficulty:1, examWeight:"high", relatedAtoms:["chem_som_008"] },
  { id:"chem_som_008", subject:"chemistry", level:"o_level", unit:"States of Matter", chapter:"Diffusion", atom:"Gases diffuse faster than liquids because gas particles move faster and have less interaction.", difficulty:2, examWeight:"high", relatedAtoms:["chem_som_007","chem_som_009"] },
  { id:"chem_som_009", subject:"chemistry", level:"o_level", unit:"States of Matter", chapter:"Diffusion", atom:"Lighter gases diffuse faster — NH3 (Mr 17) diffuses faster than HCl (Mr 36.5). White ring forms closer to HCl end.", difficulty:3, examWeight:"high", relatedAtoms:["chem_som_008"] },
  { id:"chem_som_010", subject:"chemistry", level:"o_level", unit:"States of Matter", chapter:"Brownian Motion", atom:"Brownian motion is the random movement of visible particles in a fluid, caused by collision with invisible molecules.", difficulty:2, examWeight:"medium", relatedAtoms:["chem_som_007"] },
  { id:"chem_atom_001", subject:"chemistry", level:"o_level", unit:"Atomic Structure", chapter:"Subatomic Particles", atom:"An atom contains three subatomic particles: protons (+1 charge), neutrons (0 charge) and electrons (-1 charge).", difficulty:1, examWeight:"high", relatedAtoms:["chem_atom_002","chem_atom_003"] },
  { id:"chem_atom_002", subject:"chemistry", level:"o_level", unit:"Atomic Structure", chapter:"Subatomic Particles", atom:"Protons and neutrons are in the nucleus. Electrons orbit in shells (energy levels) around the nucleus.", difficulty:1, examWeight:"high", relatedAtoms:["chem_atom_001","chem_atom_004"] },
  { id:"chem_atom_003", subject:"chemistry", level:"o_level", unit:"Atomic Structure", chapter:"Atomic Number and Mass", atom:"Atomic number = number of protons. Mass number = protons + neutrons. In a neutral atom, protons = electrons.", difficulty:1, examWeight:"high", relatedAtoms:["chem_atom_001","chem_atom_004"] },
  { id:"chem_atom_004", subject:"chemistry", level:"o_level", unit:"Atomic Structure", chapter:"Electron Configuration", atom:"Electron shells fill in order: shell 1 holds max 2, shell 2 holds max 8, shell 3 holds max 8 (at O Level).", difficulty:2, examWeight:"high", relatedAtoms:["chem_atom_003","chem_atom_005"] },
  { id:"chem_atom_005", subject:"chemistry", level:"o_level", unit:"Atomic Structure", chapter:"Electron Configuration", atom:"Sodium (Na, atomic number 11) has electron configuration 2,8,1. Chlorine (Cl, 17) has 2,8,7.", difficulty:2, examWeight:"high", relatedAtoms:["chem_atom_004"] },
  { id:"chem_atom_006", subject:"chemistry", level:"o_level", unit:"Atomic Structure", chapter:"Isotopes", atom:"Isotopes are atoms of the same element with the same atomic number but different mass numbers (different neutron count).", difficulty:2, examWeight:"high", relatedAtoms:["chem_atom_003","chem_atom_007"] },
  { id:"chem_atom_007", subject:"chemistry", level:"o_level", unit:"Atomic Structure", chapter:"Isotopes", atom:"Chlorine has two isotopes: Cl-35 (75%) and Cl-37 (25%), giving a relative atomic mass of 35.5.", difficulty:3, examWeight:"high", relatedAtoms:["chem_atom_006"] },
  { id:"chem_atom_008", subject:"chemistry", level:"o_level", unit:"Atomic Structure", chapter:"Isotopes", atom:"Isotopes have identical chemical properties (same electron configuration) but different physical properties (different mass).", difficulty:2, examWeight:"high", relatedAtoms:["chem_atom_006"] },
  { id:"chem_atom_009", subject:"chemistry", level:"o_level", unit:"Atomic Structure", chapter:"Relative Atomic Mass", atom:"Relative atomic mass (Ar) is the weighted average mass of isotopes of an element relative to 1/12 the mass of carbon-12.", difficulty:3, examWeight:"high", relatedAtoms:["chem_atom_007"] },
  { id:"chem_bond_001", subject:"chemistry", level:"o_level", unit:"Chemical Bonding", chapter:"Ionic Bonding", atom:"Ionic bonding: transfer of electrons from metal to non-metal, forming positive cations and negative anions.", difficulty:2, examWeight:"high", relatedAtoms:["chem_bond_002","chem_bond_003"] },
  { id:"chem_bond_002", subject:"chemistry", level:"o_level", unit:"Chemical Bonding", chapter:"Ionic Bonding", atom:"In NaCl: Na loses 1 electron forming Na+ (2,8). Cl gains 1 electron forming Cl- (2,8,8). Both achieve noble gas configuration.", difficulty:2, examWeight:"high", relatedAtoms:["chem_bond_001"] },
  { id:"chem_bond_003", subject:"chemistry", level:"o_level", unit:"Chemical Bonding", chapter:"Ionic Bonding", atom:"Ionic compounds have high melting/boiling points, conduct electricity when molten or dissolved (ions free to move), and are brittle.", difficulty:2, examWeight:"high", relatedAtoms:["chem_bond_001","chem_bond_002"] },
  { id:"chem_bond_004", subject:"chemistry", level:"o_level", unit:"Chemical Bonding", chapter:"Covalent Bonding", atom:"Covalent bonding: sharing of electron pairs between non-metal atoms, each atom achieving a full outer shell.", difficulty:2, examWeight:"high", relatedAtoms:["chem_bond_005","chem_bond_006"] },
  { id:"chem_bond_005", subject:"chemistry", level:"o_level", unit:"Chemical Bonding", chapter:"Covalent Bonding", atom:"H2O has 2 single covalent bonds (O shares one pair with each H). Oxygen has 2 lone pairs.", difficulty:2, examWeight:"high", relatedAtoms:["chem_bond_004"] },
  { id:"chem_bond_006", subject:"chemistry", level:"o_level", unit:"Chemical Bonding", chapter:"Covalent Bonding", atom:"CO2 has 2 double covalent bonds (C=O), linear shape. CH4 has 4 single bonds, tetrahedral shape.", difficulty:3, examWeight:"high", relatedAtoms:["chem_bond_004","chem_bond_005"] },
  { id:"chem_bond_007", subject:"chemistry", level:"o_level", unit:"Chemical Bonding", chapter:"Metallic Bonding", atom:"Metallic bonding: lattice of positive metal ions surrounded by a sea of delocalised electrons. Explains electrical conductivity and malleability.", difficulty:2, examWeight:"high", relatedAtoms:["chem_bond_008"] },
  { id:"chem_bond_008", subject:"chemistry", level:"o_level", unit:"Chemical Bonding", chapter:"Giant Structures", atom:"Giant ionic lattice (NaCl): strong electrostatic forces in all directions gives high melting point. Simple molecular (I2): weak van der Waals forces gives low melting point.", difficulty:3, examWeight:"high", relatedAtoms:["chem_bond_003","chem_bond_007"] },
  { id:"chem_bond_009", subject:"chemistry", level:"o_level", unit:"Chemical Bonding", chapter:"Giant Structures", atom:"Diamond: giant covalent structure, each C bonded to 4 others tetrahedrally. Very hard, very high melting point, does NOT conduct electricity.", difficulty:3, examWeight:"high", relatedAtoms:["chem_bond_008"] },
  { id:"chem_bond_010", subject:"chemistry", level:"o_level", unit:"Chemical Bonding", chapter:"Giant Structures", atom:"Graphite: each C bonded to 3 others in layers with one delocalised electron per C — conducts electricity. Layers slide — acts as lubricant.", difficulty:3, examWeight:"high", relatedAtoms:["chem_bond_009"] },
  { id:"chem_stoich_001", subject:"chemistry", level:"o_level", unit:"Stoichiometry", chapter:"Mole Concept", atom:"1 mole of any substance contains 6.02 x 10^23 particles (Avogadro's number).", difficulty:2, examWeight:"high", relatedAtoms:["chem_stoich_002"] },
  { id:"chem_stoich_002", subject:"chemistry", level:"o_level", unit:"Stoichiometry", chapter:"Mole Concept", atom:"Moles = mass (g) divided by molar mass (g/mol). Molar mass equals relative formula mass in grams.", difficulty:2, examWeight:"high", relatedAtoms:["chem_stoich_001","chem_stoich_003"] },
  { id:"chem_stoich_003", subject:"chemistry", level:"o_level", unit:"Stoichiometry", chapter:"Mole Concept", atom:"At STP: 1 mole of any gas occupies 22.4 dm3. At RTP (room temperature and pressure): 24 dm3.", difficulty:3, examWeight:"high", relatedAtoms:["chem_stoich_002"] },
  { id:"chem_stoich_004", subject:"chemistry", level:"o_level", unit:"Stoichiometry", chapter:"Empirical Formula", atom:"Empirical formula: simplest whole number ratio of atoms in a compound. Molecular formula: actual number of atoms.", difficulty:2, examWeight:"high", relatedAtoms:["chem_stoich_005"] },
  { id:"chem_stoich_005", subject:"chemistry", level:"o_level", unit:"Stoichiometry", chapter:"Empirical Formula", atom:"To find empirical formula: divide percentage composition by relative atomic mass, then divide by smallest value to get ratio.", difficulty:3, examWeight:"high", relatedAtoms:["chem_stoich_004"] },
  { id:"chem_stoich_006", subject:"chemistry", level:"o_level", unit:"Stoichiometry", chapter:"Concentration", atom:"Concentration (mol/dm3) = moles divided by volume (dm3). Also: concentration (g/dm3) = mass divided by volume.", difficulty:2, examWeight:"high", relatedAtoms:["chem_stoich_007"] },
  { id:"chem_stoich_007", subject:"chemistry", level:"o_level", unit:"Stoichiometry", chapter:"Titration Calculations", atom:"In titration: moles of acid = concentration x volume (dm3). Use mole ratio from equation to find moles of base.", difficulty:4, examWeight:"high", relatedAtoms:["chem_stoich_006"] },
  { id:"chem_stoich_008", subject:"chemistry", level:"o_level", unit:"Stoichiometry", chapter:"Percentage Yield", atom:"Percentage yield = (actual yield divided by theoretical yield) x 100. Less than 100% due to reversible reactions, loss during transfer, or impure reactants.", difficulty:3, examWeight:"high", relatedAtoms:["chem_stoich_009"] },
  { id:"chem_stoich_009", subject:"chemistry", level:"o_level", unit:"Stoichiometry", chapter:"Percentage Purity", atom:"Percentage purity = (mass of pure substance divided by total mass of sample) x 100.", difficulty:3, examWeight:"medium", relatedAtoms:["chem_stoich_008"] },
  { id:"chem_elec_001", subject:"chemistry", level:"o_level", unit:"Electrochemistry", chapter:"Electrolysis", atom:"Electrolysis: decomposition of an ionic compound (electrolyte) by passing direct current through it when molten or in solution.", difficulty:2, examWeight:"high", relatedAtoms:["chem_elec_002"] },
  { id:"chem_elec_002", subject:"chemistry", level:"o_level", unit:"Electrochemistry", chapter:"Electrolysis", atom:"Cathode (negative): cations attracted, gain electrons (reduction). Anode (positive): anions lose electrons (oxidation).", difficulty:2, examWeight:"high", relatedAtoms:["chem_elec_001","chem_elec_003"] },
  { id:"chem_elec_003", subject:"chemistry", level:"o_level", unit:"Electrochemistry", chapter:"Electrolysis", atom:"Electrolysis of dilute H2SO4: H2 gas at cathode, O2 gas at anode. Volume of H2 is twice volume of O2.", difficulty:3, examWeight:"high", relatedAtoms:["chem_elec_002"] },
  { id:"chem_elec_004", subject:"chemistry", level:"o_level", unit:"Electrochemistry", chapter:"Electrolysis", atom:"Electrolysis of concentrated NaCl (brine): H2 at cathode, Cl2 at anode, NaOH remains in solution. This is the industrial Chlor-alkali process.", difficulty:3, examWeight:"high", relatedAtoms:["chem_elec_003"] },
  { id:"chem_elec_005", subject:"chemistry", level:"o_level", unit:"Electrochemistry", chapter:"Electroplating", atom:"Electroplating: object to be plated is the cathode. Plating metal is the anode. Electrolyte contains ions of the plating metal.", difficulty:3, examWeight:"high", relatedAtoms:["chem_elec_002"] },
  { id:"chem_elec_006", subject:"chemistry", level:"o_level", unit:"Electrochemistry", chapter:"Electroplating", atom:"Copper purification by electrolysis: impure copper is the anode (dissolves), pure copper is the cathode (grows), CuSO4 is the electrolyte.", difficulty:3, examWeight:"high", relatedAtoms:["chem_elec_005"] },
  { id:"chem_energy_001", subject:"chemistry", level:"o_level", unit:"Energetics", chapter:"Exothermic and Endothermic", atom:"Exothermic reaction: heat energy released to surroundings. Temperature of reaction mixture rises. Delta H is negative.", difficulty:2, examWeight:"high", relatedAtoms:["chem_energy_002"] },
  { id:"chem_energy_002", subject:"chemistry", level:"o_level", unit:"Energetics", chapter:"Exothermic and Endothermic", atom:"Endothermic reaction: heat energy absorbed from surroundings. Temperature of reaction mixture falls. Delta H is positive.", difficulty:2, examWeight:"high", relatedAtoms:["chem_energy_001","chem_energy_003"] },
  { id:"chem_energy_003", subject:"chemistry", level:"o_level", unit:"Energetics", chapter:"Bond Energies", atom:"Breaking bonds requires energy (endothermic). Forming bonds releases energy (exothermic).", difficulty:2, examWeight:"high", relatedAtoms:["chem_energy_004"] },
  { id:"chem_energy_004", subject:"chemistry", level:"o_level", unit:"Energetics", chapter:"Bond Energies", atom:"Delta H = energy to break bonds minus energy released forming bonds. If forming bonds releases more than breaking requires: exothermic (Delta H negative).", difficulty:3, examWeight:"high", relatedAtoms:["chem_energy_003"] },
  { id:"chem_energy_005", subject:"chemistry", level:"o_level", unit:"Energetics", chapter:"Energy Diagrams", atom:"Activation energy: minimum energy needed for a reaction to occur. A catalyst lowers activation energy but does not change Delta H.", difficulty:3, examWeight:"high", relatedAtoms:["chem_energy_004","chem_rate_004"] },
  { id:"chem_rate_001", subject:"chemistry", level:"o_level", unit:"Rates of Reaction", chapter:"Factors Affecting Rate", atom:"Rate of reaction increases with: higher concentration, higher temperature, greater surface area, addition of catalyst, higher pressure for gases.", difficulty:2, examWeight:"high", relatedAtoms:["chem_rate_002","chem_rate_003","chem_rate_004"] },
  { id:"chem_rate_002", subject:"chemistry", level:"o_level", unit:"Rates of Reaction", chapter:"Collision Theory", atom:"Collision theory: reactions occur when particles collide with sufficient energy (at least the activation energy) and the correct orientation.", difficulty:2, examWeight:"high", relatedAtoms:["chem_rate_001"] },
  { id:"chem_rate_003", subject:"chemistry", level:"o_level", unit:"Rates of Reaction", chapter:"Collision Theory", atom:"Increasing temperature increases rate because particles move faster giving more frequent collisions AND more particles have energy equal to or greater than activation energy.", difficulty:3, examWeight:"high", relatedAtoms:["chem_rate_002"] },
  { id:"chem_rate_004", subject:"chemistry", level:"o_level", unit:"Rates of Reaction", chapter:"Catalysts", atom:"A catalyst increases reaction rate by providing an alternative pathway with lower activation energy. It is not consumed in the reaction.", difficulty:2, examWeight:"high", relatedAtoms:["chem_rate_002","chem_energy_005"] },
  { id:"chem_rate_005", subject:"chemistry", level:"o_level", unit:"Rates of Reaction", chapter:"Measuring Rate", atom:"Rate can be measured by: change in mass over time (when gas is produced), volume of gas collected over time, colour change, or turbidity when a precipitate forms.", difficulty:2, examWeight:"high", relatedAtoms:["chem_rate_001"] },
  { id:"chem_equil_001", subject:"chemistry", level:"o_level", unit:"Equilibrium", chapter:"Reversible Reactions", atom:"A reversible reaction can proceed in both directions. At equilibrium, rate of forward reaction equals rate of reverse reaction. Concentrations are constant but not equal.", difficulty:2, examWeight:"high", relatedAtoms:["chem_equil_002"] },
  { id:"chem_equil_002", subject:"chemistry", level:"o_level", unit:"Equilibrium", chapter:"Le Chatelier's Principle", atom:"Le Chatelier's Principle: if a system at equilibrium is disturbed, it shifts in the direction that opposes the change and restores equilibrium.", difficulty:3, examWeight:"high", relatedAtoms:["chem_equil_001","chem_equil_003"] },
  { id:"chem_equil_003", subject:"chemistry", level:"o_level", unit:"Equilibrium", chapter:"Le Chatelier's Principle", atom:"Increasing temperature shifts equilibrium in the endothermic direction. Decreasing temperature shifts it in the exothermic direction.", difficulty:3, examWeight:"high", relatedAtoms:["chem_equil_002"] },
  { id:"chem_equil_004", subject:"chemistry", level:"o_level", unit:"Equilibrium", chapter:"Le Chatelier's Principle", atom:"Increasing pressure shifts equilibrium toward the side with fewer moles of gas. No effect if equal moles of gas on both sides.", difficulty:3, examWeight:"high", relatedAtoms:["chem_equil_002"] },
  { id:"chem_equil_005", subject:"chemistry", level:"o_level", unit:"Equilibrium", chapter:"Haber Process", atom:"Haber Process: N2 + 3H2 = 2NH3. Conditions: 450 degrees C, 200 atm pressure, iron catalyst. A compromise between rate and yield.", difficulty:4, examWeight:"high", relatedAtoms:["chem_equil_002","chem_equil_004"] },
  { id:"chem_acid_001", subject:"chemistry", level:"o_level", unit:"Acids Bases Salts", chapter:"pH and Indicators", atom:"pH scale 0-14: pH less than 7 is acidic, pH 7 is neutral, pH greater than 7 is alkaline. Each unit represents a 10-times change in H+ concentration.", difficulty:1, examWeight:"high", relatedAtoms:["chem_acid_002"] },
  { id:"chem_acid_002", subject:"chemistry", level:"o_level", unit:"Acids Bases Salts", chapter:"Acids", atom:"Acids are proton donors. Strong acids fully dissociate (HCl, H2SO4, HNO3). Weak acids partially dissociate (ethanoic acid, carbonic acid).", difficulty:2, examWeight:"high", relatedAtoms:["chem_acid_001","chem_acid_003"] },
  { id:"chem_acid_003", subject:"chemistry", level:"o_level", unit:"Acids Bases Salts", chapter:"Bases", atom:"Bases are proton acceptors. Alkalis are soluble bases (NaOH, KOH, NH3 solution). All alkalis are bases but not all bases are alkalis.", difficulty:2, examWeight:"high", relatedAtoms:["chem_acid_002"] },
  { id:"chem_acid_004", subject:"chemistry", level:"o_level", unit:"Acids Bases Salts", chapter:"Reactions of Acids", atom:"Acid + metal gives salt + hydrogen. Acid + base gives salt + water. Acid + carbonate gives salt + water + carbon dioxide.", difficulty:2, examWeight:"high", relatedAtoms:["chem_acid_005"] },
  { id:"chem_acid_005", subject:"chemistry", level:"o_level", unit:"Acids Bases Salts", chapter:"Making Salts", atom:"Salt from insoluble base: add excess base to acid, filter, evaporate. Salt from alkali: use titration with no excess reactant.", difficulty:3, examWeight:"high", relatedAtoms:["chem_acid_004"] },
  { id:"chem_acid_006", subject:"chemistry", level:"o_level", unit:"Acids Bases Salts", chapter:"Solubility Rules", atom:"Solubility rules: all nitrates are soluble; all Na/K/NH4 salts are soluble; most chlorides soluble (except AgCl, PbCl2); most sulfates soluble (except BaSO4, PbSO4, CaSO4).", difficulty:3, examWeight:"high", relatedAtoms:["chem_acid_005"] },
  { id:"chem_per_001", subject:"chemistry", level:"o_level", unit:"Periodic Table", chapter:"Structure", atom:"Elements are arranged in order of increasing atomic number. Period = horizontal row. Group = vertical column. Elements in the same group have similar chemical properties.", difficulty:1, examWeight:"high", relatedAtoms:["chem_per_002"] },
  { id:"chem_per_002", subject:"chemistry", level:"o_level", unit:"Periodic Table", chapter:"Trends", atom:"Across a period (left to right): atomic radius decreases, ionisation energy increases, metallic character decreases.", difficulty:3, examWeight:"high", relatedAtoms:["chem_per_001","chem_per_003"] },
  { id:"chem_per_003", subject:"chemistry", level:"o_level", unit:"Periodic Table", chapter:"Trends", atom:"Down a group: atomic radius increases, ionisation energy decreases, metallic character increases.", difficulty:3, examWeight:"high", relatedAtoms:["chem_per_002"] },
  { id:"chem_per_004", subject:"chemistry", level:"o_level", unit:"Periodic Table", chapter:"Group I", atom:"Group I (alkali metals): 1 outer electron. Reactivity increases down the group. Reaction with water: 2Na + 2H2O gives 2NaOH + H2.", difficulty:2, examWeight:"high", relatedAtoms:["chem_per_005"] },
  { id:"chem_per_005", subject:"chemistry", level:"o_level", unit:"Periodic Table", chapter:"Group VII", atom:"Group VII (halogens): 7 outer electrons. Reactivity decreases down the group (F > Cl > Br > I). A more reactive halogen displaces a less reactive one from solution.", difficulty:2, examWeight:"high", relatedAtoms:["chem_per_004"] },
  { id:"chem_per_006", subject:"chemistry", level:"o_level", unit:"Periodic Table", chapter:"Group 0", atom:"Group 0 (noble gases): full outer shells make them chemically inert. Uses: Ar in lighting, He in balloons, Ne in lasers.", difficulty:1, examWeight:"medium", relatedAtoms:["chem_per_005"] },
  { id:"chem_per_007", subject:"chemistry", level:"o_level", unit:"Periodic Table", chapter:"Transition Metals", atom:"Transition metals: variable oxidation states, form coloured compounds (Fe2+ green, Fe3+ orange, Cu2+ blue), act as catalysts.", difficulty:3, examWeight:"high", relatedAtoms:["chem_per_002"] },
  { id:"chem_met_001", subject:"chemistry", level:"o_level", unit:"Metals", chapter:"Reactivity Series", atom:"Reactivity series (most to least reactive): K, Na, Ca, Mg, Al, Zn, Fe, Ni, Sn, Pb, H, Cu, Ag, Au.", difficulty:2, examWeight:"high", relatedAtoms:["chem_met_002"] },
  { id:"chem_met_002", subject:"chemistry", level:"o_level", unit:"Metals", chapter:"Reactivity Series", atom:"More reactive metal displaces less reactive from solution. Mg + CuSO4 gives MgSO4 + Cu. Cu with MgSO4 gives no reaction.", difficulty:2, examWeight:"high", relatedAtoms:["chem_met_001"] },
  { id:"chem_met_003", subject:"chemistry", level:"o_level", unit:"Metals", chapter:"Extraction", atom:"Metals above carbon in reactivity: extracted by electrolysis (Al, Na). Metals below carbon: extracted by reduction with carbon (Fe, Zn, Cu).", difficulty:3, examWeight:"high", relatedAtoms:["chem_met_001"] },
  { id:"chem_met_004", subject:"chemistry", level:"o_level", unit:"Metals", chapter:"Iron and Steel", atom:"Blast furnace: iron ore (Fe2O3) + coke (C) + limestone (CaCO3). Limestone removes acidic impurities as slag. Product is brittle cast iron.", difficulty:3, examWeight:"high", relatedAtoms:["chem_met_003"] },
  { id:"chem_met_005", subject:"chemistry", level:"o_level", unit:"Metals", chapter:"Aluminium", atom:"Aluminium extracted by electrolysis of molten aluminium oxide dissolved in cryolite. Al3+ ions are reduced at the cathode.", difficulty:3, examWeight:"high", relatedAtoms:["chem_met_003","chem_elec_001"] },
  { id:"chem_met_006", subject:"chemistry", level:"o_level", unit:"Metals", chapter:"Corrosion", atom:"Rusting: iron + oxygen + water gives iron(III) oxide. Both O2 and H2O are required. Prevented by: galvanising (zinc coat), painting, alloying.", difficulty:2, examWeight:"high", relatedAtoms:["chem_met_002"] },
  { id:"chem_org_001", subject:"chemistry", level:"o_level", unit:"Organic Chemistry", chapter:"Alkanes", atom:"Alkanes: general formula CnH(2n+2). Saturated hydrocarbons with only single C-C bonds. Non-polar and insoluble in water.", difficulty:2, examWeight:"high", relatedAtoms:["chem_org_002","chem_org_003"] },
  { id:"chem_org_002", subject:"chemistry", level:"o_level", unit:"Organic Chemistry", chapter:"Alkanes", atom:"Complete combustion of methane: CH4 + 2O2 gives CO2 + 2H2O. Incomplete combustion produces carbon monoxide and carbon (soot).", difficulty:2, examWeight:"high", relatedAtoms:["chem_org_001"] },
  { id:"chem_org_003", subject:"chemistry", level:"o_level", unit:"Organic Chemistry", chapter:"Alkanes", atom:"Alkanes undergo substitution with halogens in UV light: CH4 + Cl2 gives CH3Cl + HCl. UV light initiates the reaction.", difficulty:3, examWeight:"high", relatedAtoms:["chem_org_001"] },
  { id:"chem_org_004", subject:"chemistry", level:"o_level", unit:"Organic Chemistry", chapter:"Alkenes", atom:"Alkenes: general formula CnH(2n). Unsaturated hydrocarbons containing a C=C double bond. More reactive than alkanes.", difficulty:2, examWeight:"high", relatedAtoms:["chem_org_005","chem_org_006"] },
  { id:"chem_org_005", subject:"chemistry", level:"o_level", unit:"Organic Chemistry", chapter:"Alkenes", atom:"Alkenes undergo addition reactions: C2H4 + H2 gives C2H6 (hydrogenation); C2H4 + Br2 gives C2H4Br2 (decolourises bromine water — test for alkene).", difficulty:3, examWeight:"high", relatedAtoms:["chem_org_004"] },
  { id:"chem_org_006", subject:"chemistry", level:"o_level", unit:"Organic Chemistry", chapter:"Alkenes", atom:"Alkenes undergo addition polymerisation: n molecules of CH2=CH2 give the polymer polyethene. Requires high pressure and a catalyst.", difficulty:3, examWeight:"high", relatedAtoms:["chem_org_004","chem_org_007"] },
  { id:"chem_org_007", subject:"chemistry", level:"o_level", unit:"Organic Chemistry", chapter:"Polymers", atom:"Addition polymers: formed from alkenes. Condensation polymers: formed from two different monomers with elimination of a small molecule (H2O or HCl).", difficulty:3, examWeight:"high", relatedAtoms:["chem_org_006"] },
  { id:"chem_org_008", subject:"chemistry", level:"o_level", unit:"Organic Chemistry", chapter:"Alcohols", atom:"Alcohols contain the -OH functional group. Ethanol (C2H5OH) is made by: fermentation of sugars with yeast at 37 degrees C (anaerobic) or hydration of ethene.", difficulty:2, examWeight:"high", relatedAtoms:["chem_org_009"] },
  { id:"chem_org_009", subject:"chemistry", level:"o_level", unit:"Organic Chemistry", chapter:"Alcohols", atom:"Ethanol reactions: combustion (C2H5OH + 3O2 gives 2CO2 + 3H2O); oxidation gives ethanoic acid; dehydration (heated Al2O3 catalyst) gives ethene + water.", difficulty:3, examWeight:"high", relatedAtoms:["chem_org_008"] },
  { id:"chem_org_010", subject:"chemistry", level:"o_level", unit:"Organic Chemistry", chapter:"Carboxylic Acids", atom:"Carboxylic acids contain the -COOH group. Ethanoic acid (CH3COOH) is a weak acid. Reacts with alcohols to form esters in esterification (acid catalyst + heat).", difficulty:3, examWeight:"high", relatedAtoms:["chem_org_009"] },
  { id:"chem_org_011", subject:"chemistry", level:"o_level", unit:"Organic Chemistry", chapter:"Nucleophilic Substitution", atom:"Halogenoalkanes undergo nucleophilic substitution: the halogen is replaced by a nucleophile. OH- replaces Cl in CH3CH2Cl to give CH3CH2OH + Cl-.", difficulty:4, examWeight:"high", relatedAtoms:["chem_org_003","chem_org_008"] },

  // ═══ PHYSICS O LEVEL — 40 atoms ══════════════════════════
  { id:"phys_meas_001", subject:"physics", level:"o_level", unit:"Measurement", chapter:"SI Units", atom:"Base SI units: metre (m) for length, kilogram (kg) for mass, second (s) for time, ampere (A) for current, kelvin (K) for temperature.", difficulty:1, examWeight:"high", relatedAtoms:["phys_meas_002"] },
  { id:"phys_meas_002", subject:"physics", level:"o_level", unit:"Measurement", chapter:"Scalars and Vectors", atom:"Scalar: magnitude only (speed, distance, mass, time, energy). Vector: magnitude AND direction (velocity, displacement, force, acceleration, momentum).", difficulty:2, examWeight:"high", relatedAtoms:["phys_mot_001"] },
  { id:"phys_mot_001", subject:"physics", level:"o_level", unit:"Motion", chapter:"Speed and Velocity", atom:"Speed = distance divided by time. Velocity = displacement divided by time. Acceleration = change in velocity divided by time. All require correct units.", difficulty:1, examWeight:"high", relatedAtoms:["phys_mot_002"] },
  { id:"phys_mot_002", subject:"physics", level:"o_level", unit:"Motion", chapter:"Equations of Motion", atom:"SUVAT equations: v=u+at; s=ut+0.5at2; v2=u2+2as; s=0.5(u+v)t. Only valid for uniform (constant) acceleration.", difficulty:3, examWeight:"high", relatedAtoms:["phys_mot_001","phys_mot_003"] },
  { id:"phys_mot_003", subject:"physics", level:"o_level", unit:"Motion", chapter:"Distance-Time Graphs", atom:"Distance-time graph: gradient = speed. Horizontal line = stationary. Curved line = changing speed (acceleration).", difficulty:2, examWeight:"high", relatedAtoms:["phys_mot_004"] },
  { id:"phys_mot_004", subject:"physics", level:"o_level", unit:"Motion", chapter:"Speed-Time Graphs", atom:"Speed-time graph: gradient = acceleration. Area under graph = distance travelled. Horizontal line = constant speed.", difficulty:2, examWeight:"high", relatedAtoms:["phys_mot_003"] },
  { id:"phys_mot_005", subject:"physics", level:"o_level", unit:"Motion", chapter:"Free Fall", atom:"In free fall (no air resistance), all objects accelerate at g = 10 m/s2 regardless of mass. Air resistance reduces this acceleration.", difficulty:2, examWeight:"high", relatedAtoms:["phys_mot_002"] },
  { id:"phys_force_001", subject:"physics", level:"o_level", unit:"Forces", chapter:"Newton's Laws", atom:"Newton's 1st Law: an object stays at rest or moves at constant velocity unless acted on by a resultant force.", difficulty:2, examWeight:"high", relatedAtoms:["phys_force_002"] },
  { id:"phys_force_002", subject:"physics", level:"o_level", unit:"Forces", chapter:"Newton's Laws", atom:"Newton's 2nd Law: F = ma. Resultant force (N) = mass (kg) x acceleration (m/s2). Force and acceleration are in the same direction.", difficulty:2, examWeight:"high", relatedAtoms:["phys_force_001","phys_force_003"] },
  { id:"phys_force_003", subject:"physics", level:"o_level", unit:"Forces", chapter:"Newton's Laws", atom:"Newton's 3rd Law: for every action there is an equal and opposite reaction. The two forces act on different objects.", difficulty:2, examWeight:"high", relatedAtoms:["phys_force_002"] },
  { id:"phys_force_004", subject:"physics", level:"o_level", unit:"Forces", chapter:"Momentum", atom:"Momentum = mass x velocity (p = mv). Unit: kg m/s. Vector quantity. Law of conservation: total momentum before = total after in a closed system.", difficulty:3, examWeight:"high", relatedAtoms:["phys_force_005"] },
  { id:"phys_force_005", subject:"physics", level:"o_level", unit:"Forces", chapter:"Momentum", atom:"Impulse = force x time = change in momentum (F x t = m(v-u)). Larger time for same impulse means smaller force — explains car crumple zones and airbags.", difficulty:3, examWeight:"high", relatedAtoms:["phys_force_004"] },
  { id:"phys_force_006", subject:"physics", level:"o_level", unit:"Forces", chapter:"Turning Effect", atom:"Moment of a force = force x perpendicular distance from pivot. Unit: Nm. Principle of moments: sum of clockwise moments = sum of anticlockwise moments at equilibrium.", difficulty:2, examWeight:"high", relatedAtoms:["phys_force_007"] },
  { id:"phys_force_007", subject:"physics", level:"o_level", unit:"Forces", chapter:"Centre of Gravity", atom:"Centre of gravity is the point where the entire weight of an object appears to act. An object topples if the line of action of its weight falls outside its base.", difficulty:2, examWeight:"high", relatedAtoms:["phys_force_006"] },
  { id:"phys_energy_001", subject:"physics", level:"o_level", unit:"Energy", chapter:"Forms of Energy", atom:"Energy forms: kinetic (0.5mv2), gravitational PE (mgh), elastic PE, thermal, chemical, nuclear, electrical, light, sound.", difficulty:1, examWeight:"high", relatedAtoms:["phys_energy_002"] },
  { id:"phys_energy_002", subject:"physics", level:"o_level", unit:"Energy", chapter:"Conservation of Energy", atom:"Conservation of energy: energy cannot be created or destroyed, only transferred between forms. Total energy in a closed system remains constant.", difficulty:1, examWeight:"high", relatedAtoms:["phys_energy_003"] },
  { id:"phys_energy_003", subject:"physics", level:"o_level", unit:"Energy", chapter:"Efficiency", atom:"Efficiency = (useful energy output divided by total energy input) x 100%. Always less than 100% — some energy is always wasted as heat.", difficulty:2, examWeight:"high", relatedAtoms:["phys_energy_002"] },
  { id:"phys_energy_004", subject:"physics", level:"o_level", unit:"Energy", chapter:"Power", atom:"Power = energy transferred divided by time = work done divided by time. P = E/t = W/t. Unit: watt (W) = J/s.", difficulty:2, examWeight:"high", relatedAtoms:["phys_energy_003"] },
  { id:"phys_therm_001", subject:"physics", level:"o_level", unit:"Thermal Physics", chapter:"Temperature and Heat", atom:"Temperature measures average kinetic energy of particles. Heat is energy transferred due to a temperature difference. These are different concepts — a common exam error.", difficulty:2, examWeight:"high", relatedAtoms:["phys_therm_002"] },
  { id:"phys_therm_002", subject:"physics", level:"o_level", unit:"Thermal Physics", chapter:"Specific Heat Capacity", atom:"Q = mcDeltaT. Specific heat capacity (c) = energy needed to raise 1 kg by 1 degree C. Water has high SHC (4200 J/kgC) making it an effective coolant.", difficulty:3, examWeight:"high", relatedAtoms:["phys_therm_001"] },
  { id:"phys_therm_003", subject:"physics", level:"o_level", unit:"Thermal Physics", chapter:"Heat Transfer", atom:"Conduction: vibrating particles transfer energy to neighbours. Best in solids. Metals are good conductors because of free electrons.", difficulty:2, examWeight:"high", relatedAtoms:["phys_therm_004"] },
  { id:"phys_therm_004", subject:"physics", level:"o_level", unit:"Thermal Physics", chapter:"Heat Transfer", atom:"Convection: bulk movement of fluid. Hot fluid rises (less dense), cool fluid sinks (more dense). Only occurs in fluids (liquids and gases).", difficulty:2, examWeight:"high", relatedAtoms:["phys_therm_003","phys_therm_005"] },
  { id:"phys_therm_005", subject:"physics", level:"o_level", unit:"Thermal Physics", chapter:"Heat Transfer", atom:"Radiation: transfer of energy by electromagnetic (infrared) waves. No medium needed. Dark/matt surfaces absorb and emit best. Shiny surfaces reflect best.", difficulty:2, examWeight:"high", relatedAtoms:["phys_therm_004"] },
  { id:"phys_wave_001", subject:"physics", level:"o_level", unit:"Waves", chapter:"Wave Properties", atom:"Wave equation: v = f x lambda. Wave speed (m/s) = frequency (Hz) x wavelength (m). This equation applies to all types of wave.", difficulty:2, examWeight:"high", relatedAtoms:["phys_wave_002"] },
  { id:"phys_wave_002", subject:"physics", level:"o_level", unit:"Waves", chapter:"Wave Types", atom:"Transverse waves: oscillation perpendicular to wave direction (light, water waves). Longitudinal waves: oscillation parallel to direction (sound).", difficulty:2, examWeight:"high", relatedAtoms:["phys_wave_001","phys_wave_003"] },
  { id:"phys_wave_003", subject:"physics", level:"o_level", unit:"Waves", chapter:"Reflection", atom:"Law of reflection: angle of incidence equals angle of reflection. Both angles are measured from the normal to the surface.", difficulty:1, examWeight:"high", relatedAtoms:["phys_wave_004"] },
  { id:"phys_wave_004", subject:"physics", level:"o_level", unit:"Waves", chapter:"Refraction", atom:"Refraction: wave changes speed when entering a new medium, causing change in direction (unless hitting at 90 degrees). Light slows down in a denser medium.", difficulty:2, examWeight:"high", relatedAtoms:["phys_wave_003","phys_wave_005"] },
  { id:"phys_wave_005", subject:"physics", level:"o_level", unit:"Waves", chapter:"Total Internal Reflection", atom:"Total internal reflection occurs when light travels from a dense to a less dense medium at an angle greater than or equal to the critical angle. Used in optical fibres.", difficulty:3, examWeight:"high", relatedAtoms:["phys_wave_004"] },
  { id:"phys_wave_006", subject:"physics", level:"o_level", unit:"Waves", chapter:"EM Spectrum", atom:"EM spectrum in order of increasing frequency: radio, microwave, infrared, visible, ultraviolet, X-rays, gamma rays. All travel at 3 x 10^8 m/s in a vacuum.", difficulty:2, examWeight:"high", relatedAtoms:["phys_wave_001"] },
  { id:"phys_elec_001", subject:"physics", level:"o_level", unit:"Electricity", chapter:"Current and Charge", atom:"Electric current = rate of flow of charge. I = Q/t. Charge (C) = current (A) x time (s). Conventional current flows from positive to negative.", difficulty:2, examWeight:"high", relatedAtoms:["phys_elec_002"] },
  { id:"phys_elec_002", subject:"physics", level:"o_level", unit:"Electricity", chapter:"Ohm's Law", atom:"Ohm's Law: V = IR. Voltage (V) = current (A) x resistance (Ohm). An ohmic conductor has current proportional to voltage at constant temperature.", difficulty:2, examWeight:"high", relatedAtoms:["phys_elec_001","phys_elec_003"] },
  { id:"phys_elec_003", subject:"physics", level:"o_level", unit:"Electricity", chapter:"Series and Parallel", atom:"Series circuit: same current through all components. Voltages add up. Total resistance = R1 + R2 + ...", difficulty:2, examWeight:"high", relatedAtoms:["phys_elec_004"] },
  { id:"phys_elec_004", subject:"physics", level:"o_level", unit:"Electricity", chapter:"Series and Parallel", atom:"Parallel circuit: same voltage across all branches. Currents add up. 1/R_total = 1/R1 + 1/R2 + ...", difficulty:3, examWeight:"high", relatedAtoms:["phys_elec_003"] },
  { id:"phys_elec_005", subject:"physics", level:"o_level", unit:"Electricity", chapter:"Power", atom:"Electrical power: P = VI = I2R = V2/R. Energy transferred: E = Pt = VIt. Power unit is watt (W).", difficulty:3, examWeight:"high", relatedAtoms:["phys_elec_002"] },
  { id:"phys_elec_006", subject:"physics", level:"o_level", unit:"Electricity", chapter:"Electromagnetism", atom:"A current-carrying conductor in a magnetic field experiences a force (motor effect). F = BIL. Direction given by Fleming's left-hand rule.", difficulty:3, examWeight:"high", relatedAtoms:["phys_elec_007"] },
  { id:"phys_elec_007", subject:"physics", level:"o_level", unit:"Electricity", chapter:"Electromagnetic Induction", atom:"A conductor moving in a magnetic field generates an EMF (generator effect). Fleming's right-hand rule gives direction of induced current.", difficulty:3, examWeight:"high", relatedAtoms:["phys_elec_006"] },
  { id:"phys_elec_008", subject:"physics", level:"o_level", unit:"Electricity", chapter:"Transformers", atom:"Transformer: Vp/Vs = Np/Ns = Is/Ip. Step-up transformer: more turns on secondary. Step-down: fewer turns on secondary. Ideal transformer: VpIp = VsIs.", difficulty:3, examWeight:"high", relatedAtoms:["phys_elec_007"] },
  { id:"phys_atomic_001", subject:"physics", level:"o_level", unit:"Atomic Physics", chapter:"Radioactivity", atom:"Three types of radiation: alpha (2 protons + 2 neutrons, stopped by paper), beta (fast electron, stopped by 3mm aluminium), gamma (EM wave, reduced by thick lead).", difficulty:2, examWeight:"high", relatedAtoms:["phys_atomic_002"] },
  { id:"phys_atomic_002", subject:"physics", level:"o_level", unit:"Atomic Physics", chapter:"Radioactivity", atom:"Half-life: time for half the radioactive nuclei in a sample to decay. After n half-lives: remaining amount = original x (0.5)^n.", difficulty:3, examWeight:"high", relatedAtoms:["phys_atomic_001"] },
  { id:"phys_atomic_003", subject:"physics", level:"o_level", unit:"Atomic Physics", chapter:"Nuclear Equations", atom:"Alpha decay: mass number decreases by 4, atomic number decreases by 2. Beta decay: mass number unchanged, atomic number increases by 1.", difficulty:3, examWeight:"high", relatedAtoms:["phys_atomic_001"] },

  // ═══ BIOLOGY O LEVEL — 37 atoms ══════════════════════════
  { id:"bio_cell_001", subject:"biology", level:"o_level", unit:"Cell Biology", chapter:"Cell Structure", atom:"Plant cells have: cell wall (cellulose), cell membrane, cytoplasm, nucleus, vacuole, chloroplasts. Animal cells lack cell wall, large vacuole and chloroplasts.", difficulty:1, examWeight:"high", relatedAtoms:["bio_cell_002"] },
  { id:"bio_cell_002", subject:"biology", level:"o_level", unit:"Cell Biology", chapter:"Cell Organelles", atom:"Nucleus: contains DNA and controls cell activity. Mitochondria: site of aerobic respiration (ATP production). Ribosome: site of protein synthesis.", difficulty:2, examWeight:"high", relatedAtoms:["bio_cell_001","bio_cell_003"] },
  { id:"bio_cell_003", subject:"biology", level:"o_level", unit:"Cell Biology", chapter:"Cell Types", atom:"Prokaryotic cells (bacteria): no nucleus, no membrane-bound organelles, smaller size, circular DNA. Eukaryotic cells: have a nucleus and membrane-bound organelles.", difficulty:2, examWeight:"high", relatedAtoms:["bio_cell_002"] },
  { id:"bio_cell_004", subject:"biology", level:"o_level", unit:"Cell Biology", chapter:"Diffusion", atom:"Diffusion: net movement of molecules from high to low concentration. Passive process (no energy needed). Rate increased by larger surface area, shorter diffusion distance, steeper gradient.", difficulty:2, examWeight:"high", relatedAtoms:["bio_cell_005"] },
  { id:"bio_cell_005", subject:"biology", level:"o_level", unit:"Cell Biology", chapter:"Osmosis", atom:"Osmosis: net movement of WATER molecules from high water potential (dilute solution) to low water potential (concentrated solution) through a partially permeable membrane.", difficulty:2, examWeight:"high", relatedAtoms:["bio_cell_004","bio_cell_006"] },
  { id:"bio_cell_006", subject:"biology", level:"o_level", unit:"Cell Biology", chapter:"Active Transport", atom:"Active transport: movement of molecules against the concentration gradient using energy (ATP) and carrier proteins. Required for mineral ion absorption in root hair cells.", difficulty:2, examWeight:"high", relatedAtoms:["bio_cell_005"] },
  { id:"bio_cell_007", subject:"biology", level:"o_level", unit:"Cell Biology", chapter:"Enzymes", atom:"Enzymes are biological catalysts. They are proteins with a specific active site shape that lowers activation energy without being consumed in the reaction.", difficulty:2, examWeight:"high", relatedAtoms:["bio_cell_008"] },
  { id:"bio_cell_008", subject:"biology", level:"o_level", unit:"Cell Biology", chapter:"Enzymes", atom:"Lock and key hypothesis: the substrate fits exactly into the enzyme active site (complementary shapes). An enzyme-substrate complex forms, then products are released.", difficulty:2, examWeight:"high", relatedAtoms:["bio_cell_007","bio_cell_009"] },
  { id:"bio_cell_009", subject:"biology", level:"o_level", unit:"Cell Biology", chapter:"Enzymes", atom:"High temperature denatures enzymes — permanently changes the active site shape. Low temperature slows reaction (less kinetic energy) but does NOT denature the enzyme.", difficulty:2, examWeight:"high", relatedAtoms:["bio_cell_008"] },
  { id:"bio_cell_010", subject:"biology", level:"o_level", unit:"Cell Biology", chapter:"Enzymes", atom:"pH affects enzyme activity. Each enzyme has an optimum pH. Moving away from the optimum distorts the active site shape, reducing activity or causing denaturation.", difficulty:2, examWeight:"high", relatedAtoms:["bio_cell_009"] },
  { id:"bio_nutr_001", subject:"biology", level:"o_level", unit:"Nutrition", chapter:"Photosynthesis", atom:"Photosynthesis equation: 6CO2 + 6H2O + light energy gives C6H12O6 + 6O2. Occurs in chloroplasts. Chlorophyll absorbs light energy.", difficulty:2, examWeight:"high", relatedAtoms:["bio_nutr_002"] },
  { id:"bio_nutr_002", subject:"biology", level:"o_level", unit:"Nutrition", chapter:"Limiting Factors", atom:"Factors limiting photosynthesis: light intensity, CO2 concentration, temperature. The factor in shortest supply at any point is the limiting factor.", difficulty:3, examWeight:"high", relatedAtoms:["bio_nutr_001"] },
  { id:"bio_nutr_003", subject:"biology", level:"o_level", unit:"Nutrition", chapter:"Testing for Starch", atom:"Testing a leaf for starch: boil in water to kill cells, boil in ethanol to remove chlorophyll, wash in water, add iodine. Blue-black = starch present.", difficulty:2, examWeight:"high", relatedAtoms:["bio_nutr_001"] },
  { id:"bio_nutr_004", subject:"biology", level:"o_level", unit:"Nutrition", chapter:"Human Digestion", atom:"Digestion is physical (chewing, peristalsis) and chemical (enzymes). Amylase: starch to maltose. Protease: proteins to amino acids. Lipase: fats to fatty acids + glycerol.", difficulty:2, examWeight:"high", relatedAtoms:["bio_nutr_005"] },
  { id:"bio_nutr_005", subject:"biology", level:"o_level", unit:"Nutrition", chapter:"Absorption", atom:"Villi increase surface area for absorption in the small intestine. Key features: large surface area, thin epithelium (one cell thick), rich blood supply, lacteals for fat absorption.", difficulty:3, examWeight:"high", relatedAtoms:["bio_nutr_004"] },
  { id:"bio_nutr_006", subject:"biology", level:"o_level", unit:"Nutrition", chapter:"Food Tests", atom:"Food tests: Benedict's reagent for reducing sugars (brick red precipitate). Iodine for starch (blue-black). Biuret for protein (purple). Ethanol emulsion test for fats (milky white).", difficulty:2, examWeight:"high", relatedAtoms:["bio_nutr_004"] },
  { id:"bio_trans_001", subject:"biology", level:"o_level", unit:"Transport", chapter:"Blood Components", atom:"Blood: red blood cells (haemoglobin, no nucleus, biconcave disc shape — carry O2), white blood cells (immunity), platelets (clotting), plasma (carries nutrients, CO2, hormones, urea).", difficulty:2, examWeight:"high", relatedAtoms:["bio_trans_002"] },
  { id:"bio_trans_002", subject:"biology", level:"o_level", unit:"Transport", chapter:"Heart", atom:"Right side of heart pumps deoxygenated blood to lungs (pulmonary circuit). Left side pumps oxygenated blood to body (systemic circuit). Left ventricle wall is thicker — needs more pressure.", difficulty:2, examWeight:"high", relatedAtoms:["bio_trans_001","bio_trans_003"] },
  { id:"bio_trans_003", subject:"biology", level:"o_level", unit:"Transport", chapter:"Blood Vessels", atom:"Arteries: thick muscular walls, carry blood AWAY from heart at high pressure. Veins: thin walls with valves, carry blood TO heart at low pressure. Capillaries: one cell thick, exchange site.", difficulty:2, examWeight:"high", relatedAtoms:["bio_trans_002"] },
  { id:"bio_trans_004", subject:"biology", level:"o_level", unit:"Transport", chapter:"Xylem and Phloem", atom:"Xylem: transports water and minerals upward from roots to leaves (transpiration stream). Dead cells with no cell contents and lignified walls.", difficulty:2, examWeight:"high", relatedAtoms:["bio_trans_005"] },
  { id:"bio_trans_005", subject:"biology", level:"o_level", unit:"Transport", chapter:"Xylem and Phloem", atom:"Phloem: transports sucrose and amino acids both up and down (translocation). Living cells including sieve tube elements and companion cells.", difficulty:2, examWeight:"high", relatedAtoms:["bio_trans_004"] },
  { id:"bio_trans_006", subject:"biology", level:"o_level", unit:"Transport", chapter:"Transpiration", atom:"Transpiration: loss of water vapour from leaves via stomata. Rate increases with: higher temperature, lower humidity, wind, and light (stomata open). Measured using a potometer.", difficulty:3, examWeight:"high", relatedAtoms:["bio_trans_004"] },
  { id:"bio_resp_001", subject:"biology", level:"o_level", unit:"Respiration", chapter:"Aerobic Respiration", atom:"Aerobic respiration: C6H12O6 + 6O2 gives 6CO2 + 6H2O + energy (ATP). Occurs in mitochondria. Produces a large amount of ATP.", difficulty:2, examWeight:"high", relatedAtoms:["bio_resp_002"] },
  { id:"bio_resp_002", subject:"biology", level:"o_level", unit:"Respiration", chapter:"Anaerobic Respiration", atom:"Anaerobic respiration in animals: glucose gives lactic acid + small amount of ATP. In yeast and plants: glucose gives ethanol + CO2 + ATP (fermentation).", difficulty:2, examWeight:"high", relatedAtoms:["bio_resp_001"] },
  { id:"bio_resp_003", subject:"biology", level:"o_level", unit:"Respiration", chapter:"Gas Exchange", atom:"Alveoli in lungs are adapted for gas exchange: large surface area, very thin walls (one cell thick), moist surface, rich blood supply — all maximise diffusion rate.", difficulty:2, examWeight:"high", relatedAtoms:["bio_resp_001"] },
  { id:"bio_nerv_001", subject:"biology", level:"o_level", unit:"Coordination", chapter:"Nervous System", atom:"Neurone types: sensory (receptor to CNS), motor (CNS to effector), relay (within CNS). Impulse travels along axon. Synapse: gap between neurones, crossed by neurotransmitters.", difficulty:2, examWeight:"high", relatedAtoms:["bio_nerv_002"] },
  { id:"bio_nerv_002", subject:"biology", level:"o_level", unit:"Coordination", chapter:"Reflex Arc", atom:"Reflex arc: stimulus, receptor, sensory neurone, relay neurone (spinal cord), motor neurone, effector. Bypasses the brain for speed.", difficulty:2, examWeight:"high", relatedAtoms:["bio_nerv_001"] },
  { id:"bio_nerv_003", subject:"biology", level:"o_level", unit:"Coordination", chapter:"Hormones", atom:"Hormones are chemical messengers transported in the blood. Insulin (pancreas) lowers blood glucose. Glucagon raises blood glucose. Adrenaline triggers the fight-or-flight response.", difficulty:2, examWeight:"high", relatedAtoms:["bio_nerv_001"] },
  { id:"bio_gen_001", subject:"biology", level:"o_level", unit:"Genetics", chapter:"DNA", atom:"DNA is a double helix made of nucleotides. Each nucleotide contains: phosphate + deoxyribose sugar + a base (A, T, G, or C). A pairs with T; C pairs with G (complementary base pairing).", difficulty:2, examWeight:"high", relatedAtoms:["bio_gen_002"] },
  { id:"bio_gen_002", subject:"biology", level:"o_level", unit:"Genetics", chapter:"Cell Division", atom:"Mitosis: produces 2 identical diploid daughter cells. Used for growth and repair. Meiosis: produces 4 genetically different haploid gametes. Used for sexual reproduction.", difficulty:2, examWeight:"high", relatedAtoms:["bio_gen_001","bio_gen_003"] },
  { id:"bio_gen_003", subject:"biology", level:"o_level", unit:"Genetics", chapter:"Inheritance", atom:"Dominant allele: always expressed when present. Recessive allele: only expressed when homozygous (rr). A heterozygous individual (Rr) shows the dominant phenotype.", difficulty:2, examWeight:"high", relatedAtoms:["bio_gen_002","bio_gen_004"] },
  { id:"bio_gen_004", subject:"biology", level:"o_level", unit:"Genetics", chapter:"Monohybrid Cross", atom:"Monohybrid cross Tt x Tt gives genotype ratio 1TT:2Tt:1tt and phenotype ratio 3 dominant:1 recessive (if T is dominant). Punnett squares are used to predict outcomes.", difficulty:3, examWeight:"high", relatedAtoms:["bio_gen_003"] },
  { id:"bio_gen_005", subject:"biology", level:"o_level", unit:"Genetics", chapter:"Variation", atom:"Continuous variation (height, mass): range of values, polygenic. Discontinuous variation (blood group, eye colour): distinct categories. Caused by genes and/or environment.", difficulty:2, examWeight:"high", relatedAtoms:["bio_gen_003"] },
  { id:"bio_gen_006", subject:"biology", level:"o_level", unit:"Genetics", chapter:"Natural Selection", atom:"Natural selection: variation exists, some individuals are better adapted, they survive and reproduce, passing on advantageous alleles. The mechanism for evolution (Darwin).", difficulty:3, examWeight:"high", relatedAtoms:["bio_gen_005"] },
  { id:"bio_ecol_001", subject:"biology", level:"o_level", unit:"Ecology", chapter:"Food Chains", atom:"Food chain: producer, primary consumer, secondary consumer, tertiary consumer. Arrow shows direction of energy flow. Only approximately 10% of energy is transferred at each trophic level.", difficulty:1, examWeight:"high", relatedAtoms:["bio_ecol_002"] },
  { id:"bio_ecol_002", subject:"biology", level:"o_level", unit:"Ecology", chapter:"Nutrient Cycles", atom:"Carbon cycle: CO2 removed by photosynthesis, returned by respiration, combustion and decomposition. Nitrogen cycle: N2 fixed by bacteria, absorbed by plants, returned by decomposers.", difficulty:3, examWeight:"high", relatedAtoms:["bio_ecol_001"] },
  { id:"bio_ecol_003", subject:"biology", level:"o_level", unit:"Ecology", chapter:"Human Impact", atom:"Deforestation effects: less CO2 absorbed, soil erosion, loss of biodiversity, increased flooding, reduced transpiration, contributing to climate change.", difficulty:2, examWeight:"high", relatedAtoms:["bio_ecol_002"] },

  // ═══ MATHEMATICS O LEVEL — 29 atoms ═════════════════════
  { id:"math_num_001", subject:"mathematics", level:"o_level", unit:"Number", chapter:"Types of Number", atom:"Integers: whole numbers including negatives and zero. Rational numbers: expressible as p/q. Irrational: cannot be expressed as p/q (pi, root 2). Real numbers include both.", difficulty:1, examWeight:"high", relatedAtoms:["math_num_002"] },
  { id:"math_num_002", subject:"mathematics", level:"o_level", unit:"Number", chapter:"HCF and LCM", atom:"HCF (Highest Common Factor): largest number dividing exactly into all given numbers. LCM (Lowest Common Multiple): smallest number divisible by all given numbers.", difficulty:1, examWeight:"high", relatedAtoms:["math_num_001"] },
  { id:"math_num_003", subject:"mathematics", level:"o_level", unit:"Number", chapter:"Standard Form", atom:"Standard form: A x 10^n where 1 is less than or equal to A and A is less than 10, and n is an integer. 3200 = 3.2 x 10^3. 0.0045 = 4.5 x 10^-3.", difficulty:2, examWeight:"high", relatedAtoms:["math_num_004"] },
  { id:"math_num_004", subject:"mathematics", level:"o_level", unit:"Number", chapter:"Percentages", atom:"Percentage increase/decrease = (change divided by original) x 100. Reverse percentage: to find original after n% increase, divide by (1 + n/100).", difficulty:2, examWeight:"high", relatedAtoms:["math_num_005"] },
  { id:"math_num_005", subject:"mathematics", level:"o_level", unit:"Number", chapter:"Ratio and Proportion", atom:"Direct proportion: y = kx (graph is straight line through origin). Inverse proportion: y = k/x. As x increases, y decreases.", difficulty:2, examWeight:"high", relatedAtoms:["math_num_004"] },
  { id:"math_alg_001", subject:"mathematics", level:"o_level", unit:"Algebra", chapter:"Expanding and Factorising", atom:"Expanding: a(b+c) = ab+ac. (a+b)(c+d) = ac+ad+bc+bd. Difference of two squares: a2-b2 = (a+b)(a-b). Useful identity to recognise.", difficulty:2, examWeight:"high", relatedAtoms:["math_alg_002"] },
  { id:"math_alg_002", subject:"mathematics", level:"o_level", unit:"Algebra", chapter:"Factorising Quadratics", atom:"To factorise ax2+bx+c: find two numbers that multiply to ac and add to b, then group and factorise.", difficulty:3, examWeight:"high", relatedAtoms:["math_alg_001","math_alg_003"] },
  { id:"math_alg_003", subject:"mathematics", level:"o_level", unit:"Algebra", chapter:"Quadratic Formula", atom:"Quadratic formula: x = (-b plus or minus root(b2-4ac)) divided by 2a. Discriminant b2-4ac: greater than 0 gives two real roots; equals 0 gives one repeated root; less than 0 gives no real roots.", difficulty:3, examWeight:"high", relatedAtoms:["math_alg_002","math_alg_004"] },
  { id:"math_alg_004", subject:"mathematics", level:"o_level", unit:"Algebra", chapter:"Simultaneous Equations", atom:"Simultaneous equations solved by substitution or elimination. Two equations, two unknowns. Always check the answer by substituting back into both equations.", difficulty:3, examWeight:"high", relatedAtoms:["math_alg_003"] },
  { id:"math_alg_005", subject:"mathematics", level:"o_level", unit:"Algebra", chapter:"Inequalities", atom:"Solving inequalities is the same as equations EXCEPT: multiplying or dividing by a negative number reverses the inequality sign. Solution shown on a number line.", difficulty:2, examWeight:"high", relatedAtoms:["math_alg_004"] },
  { id:"math_alg_006", subject:"mathematics", level:"o_level", unit:"Algebra", chapter:"Sequences", atom:"nth term of arithmetic sequence: a + (n-1)d where a = first term and d = common difference. Sum of n terms: n/2 x (2a + (n-1)d).", difficulty:3, examWeight:"high", relatedAtoms:["math_alg_005"] },
  { id:"math_alg_007", subject:"mathematics", level:"o_level", unit:"Algebra", chapter:"Indices", atom:"Laws of indices: a^m x a^n = a^(m+n); a^m divided by a^n = a^(m-n); (a^m)^n = a^mn; a^0 = 1; a^(-n) = 1/a^n; a^(1/n) = nth root of a.", difficulty:2, examWeight:"high", relatedAtoms:["math_num_003"] },
  { id:"math_geom_001", subject:"mathematics", level:"o_level", unit:"Geometry", chapter:"Angle Properties", atom:"Angles in a triangle sum to 180 degrees. Angles in a quadrilateral sum to 360 degrees. Angles on a straight line sum to 180 degrees. Vertically opposite angles are equal.", difficulty:1, examWeight:"high", relatedAtoms:["math_geom_002"] },
  { id:"math_geom_002", subject:"mathematics", level:"o_level", unit:"Geometry", chapter:"Parallel Lines", atom:"Parallel lines cut by a transversal: alternate angles are equal (Z-angles); co-interior angles sum to 180 degrees (C-angles); corresponding angles are equal (F-angles).", difficulty:2, examWeight:"high", relatedAtoms:["math_geom_001"] },
  { id:"math_geom_003", subject:"mathematics", level:"o_level", unit:"Geometry", chapter:"Circle Theorems", atom:"Circle theorems: angle at centre = 2 x angle at circumference (same arc). Angles in the same segment are equal. Angle in a semicircle = 90 degrees.", difficulty:3, examWeight:"high", relatedAtoms:["math_geom_004"] },
  { id:"math_geom_004", subject:"mathematics", level:"o_level", unit:"Geometry", chapter:"Circle Theorems", atom:"Opposite angles of a cyclic quadrilateral add to 180 degrees. Tangent is perpendicular to radius at point of contact. Two tangents from an external point are equal in length.", difficulty:3, examWeight:"high", relatedAtoms:["math_geom_003"] },
  { id:"math_geom_005", subject:"mathematics", level:"o_level", unit:"Geometry", chapter:"Pythagoras", atom:"Pythagoras theorem: a2 + b2 = c2 where c is the hypotenuse. Used to find the missing side of a right-angled triangle.", difficulty:1, examWeight:"high", relatedAtoms:["math_trig_001"] },
  { id:"math_trig_001", subject:"mathematics", level:"o_level", unit:"Trigonometry", chapter:"SOH CAH TOA", atom:"sin(theta) = opposite/hypotenuse. cos(theta) = adjacent/hypotenuse. tan(theta) = opposite/adjacent. SOH-CAH-TOA applies only to right-angled triangles.", difficulty:2, examWeight:"high", relatedAtoms:["math_trig_002"] },
  { id:"math_trig_002", subject:"mathematics", level:"o_level", unit:"Trigonometry", chapter:"Sine Rule", atom:"Sine rule: a/sinA = b/sinB = c/sinC. Used when two angles and one side are known, or two sides and a non-included angle are known.", difficulty:3, examWeight:"high", relatedAtoms:["math_trig_001","math_trig_003"] },
  { id:"math_trig_003", subject:"mathematics", level:"o_level", unit:"Trigonometry", chapter:"Cosine Rule", atom:"Cosine rule: a2 = b2 + c2 - 2bc x cosA. Used when two sides and the included angle are known, or when all three sides are known.", difficulty:3, examWeight:"high", relatedAtoms:["math_trig_002"] },
  { id:"math_trig_004", subject:"mathematics", level:"o_level", unit:"Trigonometry", chapter:"Bearings", atom:"Bearings: measured clockwise from north, always written as three figures (045 not 45). Back bearing = bearing + 180 (if less than 180) or bearing - 180 (if greater than 180).", difficulty:2, examWeight:"high", relatedAtoms:["math_trig_001"] },
  { id:"math_stat_001", subject:"mathematics", level:"o_level", unit:"Statistics", chapter:"Averages", atom:"Mean = sum divided by count. Median = middle value when data is ordered. Mode = most frequent value. Range = maximum minus minimum.", difficulty:1, examWeight:"high", relatedAtoms:["math_stat_002"] },
  { id:"math_stat_002", subject:"mathematics", level:"o_level", unit:"Statistics", chapter:"Cumulative Frequency", atom:"Cumulative frequency curve (ogive): median at 50th percentile, lower quartile at 25th, upper quartile at 75th percentile. IQR = upper quartile minus lower quartile.", difficulty:3, examWeight:"high", relatedAtoms:["math_stat_001"] },
  { id:"math_stat_003", subject:"mathematics", level:"o_level", unit:"Statistics", chapter:"Probability", atom:"Probability of an event = number of favourable outcomes divided by total outcomes. P(A') = 1 - P(A). All probabilities lie between 0 and 1.", difficulty:2, examWeight:"high", relatedAtoms:["math_stat_004"] },
  { id:"math_stat_004", subject:"mathematics", level:"o_level", unit:"Statistics", chapter:"Combined Probability", atom:"Independent events: P(A and B) = P(A) x P(B). Mutually exclusive events: P(A or B) = P(A) + P(B). Tree diagrams are used to calculate combined event probabilities.", difficulty:3, examWeight:"high", relatedAtoms:["math_stat_003"] },
  { id:"math_mat_001", subject:"mathematics", level:"o_level", unit:"Matrices", chapter:"Matrix Operations", atom:"Matrix addition/subtraction: add/subtract corresponding elements (same order required). Multiplication: row times column. Matrix multiplication is NOT commutative (AB is not equal to BA).", difficulty:3, examWeight:"high", relatedAtoms:["math_mat_002"] },
  { id:"math_mat_002", subject:"mathematics", level:"o_level", unit:"Matrices", chapter:"Transformation Matrices", atom:"Transformation matrices: reflection in y-axis is (-1,0/0,1); rotation 90 degrees anticlockwise is (0,-1/1,0); enlargement scale factor k is (k,0/0,k).", difficulty:4, examWeight:"high", relatedAtoms:["math_mat_001"] },
  { id:"math_vec_001", subject:"mathematics", level:"o_level", unit:"Vectors", chapter:"Vector Operations", atom:"Vector AB = position of B minus position of A. Magnitude of vector a = root(x2+y2). Adding vectors: tip-to-tail method. Multiplying by scalar k changes magnitude but not direction.", difficulty:3, examWeight:"high", relatedAtoms:["math_vec_002"] },
  { id:"math_vec_002", subject:"mathematics", level:"o_level", unit:"Vectors", chapter:"Parallel and Collinear", atom:"If AB = k x CD then AB is parallel to CD with magnitude k times |CD|. Points are collinear if AB = k x AC (same direction through a common point A).", difficulty:4, examWeight:"high", relatedAtoms:["math_vec_001"] },

  // ═══ ECONOMICS A LEVEL — 22 atoms ════════════════════════
  { id:"econ_basic_001", subject:"economics", level:"a_level", unit:"Basic Economic Ideas", chapter:"Scarcity and Choice", atom:"The economic problem: unlimited wants but scarce resources mean choices must be made. Every choice involves an opportunity cost.", difficulty:1, examWeight:"high", relatedAtoms:["econ_basic_002"] },
  { id:"econ_basic_002", subject:"economics", level:"a_level", unit:"Basic Economic Ideas", chapter:"Opportunity Cost", atom:"Opportunity cost: the value of the next best alternative forgone when a choice is made. Applies to consumers, firms and governments alike.", difficulty:1, examWeight:"high", relatedAtoms:["econ_basic_001","econ_basic_003"] },
  { id:"econ_basic_003", subject:"economics", level:"a_level", unit:"Basic Economic Ideas", chapter:"Production Possibility Curves", atom:"PPC shows maximum combinations of two goods producible with given resources. Points inside curve = inefficient. On curve = productively efficient. Outside = currently unattainable.", difficulty:2, examWeight:"high", relatedAtoms:["econ_basic_002"] },
  { id:"econ_basic_004", subject:"economics", level:"a_level", unit:"Basic Economic Ideas", chapter:"Economic Systems", atom:"Free market: resources allocated by price mechanism. Command economy: government plans allocation. Mixed economy: both operate. Market failure justifies government intervention.", difficulty:2, examWeight:"high", relatedAtoms:["econ_basic_001"] },
  { id:"econ_price_001", subject:"economics", level:"a_level", unit:"Price System", chapter:"Demand", atom:"Law of demand: as price rises, quantity demanded falls (ceteris paribus). Demand curve slopes downward. Movement along curve = price change. Shift of curve = non-price factor change.", difficulty:2, examWeight:"high", relatedAtoms:["econ_price_002"] },
  { id:"econ_price_002", subject:"economics", level:"a_level", unit:"Price System", chapter:"Demand Shifters", atom:"Demand shifts right with: higher income (normal good), higher price of substitute, lower price of complement, increased population, change in tastes. Left for inferior goods when income rises.", difficulty:2, examWeight:"high", relatedAtoms:["econ_price_001","econ_price_003"] },
  { id:"econ_price_003", subject:"economics", level:"a_level", unit:"Price System", chapter:"Supply", atom:"Law of supply: as price rises, quantity supplied rises (ceteris paribus). Supply shifts right with: lower costs, better technology, subsidies, favourable weather for agricultural goods.", difficulty:2, examWeight:"high", relatedAtoms:["econ_price_002","econ_price_004"] },
  { id:"econ_price_004", subject:"economics", level:"a_level", unit:"Price System", chapter:"Equilibrium", atom:"Market equilibrium: quantity demanded equals quantity supplied. Price above equilibrium creates a surplus. Price below equilibrium creates a shortage. Price adjusts to restore equilibrium.", difficulty:2, examWeight:"high", relatedAtoms:["econ_price_003"] },
  { id:"econ_price_005", subject:"economics", level:"a_level", unit:"Price System", chapter:"PED", atom:"Price elasticity of demand (PED) = % change in Qd divided by % change in price. PED greater than 1 = elastic (total revenue falls when price rises). PED less than 1 = inelastic (TR rises when price rises).", difficulty:3, examWeight:"high", relatedAtoms:["econ_price_006"] },
  { id:"econ_price_006", subject:"economics", level:"a_level", unit:"Price System", chapter:"Elasticity Determinants", atom:"Factors affecting PED: availability of substitutes (more substitutes = more elastic), necessity vs luxury, proportion of income spent, time period (more elastic in the long run).", difficulty:3, examWeight:"high", relatedAtoms:["econ_price_005"] },
  { id:"econ_price_007", subject:"economics", level:"a_level", unit:"Price System", chapter:"Other Elasticities", atom:"YED: positive = normal good, negative = inferior good, greater than 1 = luxury. Cross-elasticity: positive = substitutes, negative = complements. PES = % change in Qs divided by % change in price.", difficulty:3, examWeight:"high", relatedAtoms:["econ_price_006"] },
  { id:"econ_mkt_001", subject:"economics", level:"a_level", unit:"Market Structures", chapter:"Perfect Competition", atom:"Perfect competition: many buyers and sellers, homogeneous product, perfect information, free entry/exit. Firms are price takers. Long-run equilibrium: normal profit only. P = MC = AC.", difficulty:3, examWeight:"high", relatedAtoms:["econ_mkt_002"] },
  { id:"econ_mkt_002", subject:"economics", level:"a_level", unit:"Market Structures", chapter:"Monopoly", atom:"Monopoly: single seller, high barriers to entry, price maker. Profit maximises where MR = MC. Price greater than MC creates allocative inefficiency. May benefit from economies of scale.", difficulty:3, examWeight:"high", relatedAtoms:["econ_mkt_001","econ_mkt_003"] },
  { id:"econ_mkt_003", subject:"economics", level:"a_level", unit:"Market Structures", chapter:"Oligopoly", atom:"Oligopoly: few dominant firms, interdependence, barriers to entry, product differentiation. Firms may collude (cartel) or compete. Kinked demand curve model explains price rigidity.", difficulty:4, examWeight:"high", relatedAtoms:["econ_mkt_002"] },
  { id:"econ_macro_001", subject:"economics", level:"a_level", unit:"Macroeconomics", chapter:"Objectives", atom:"Four main macroeconomic objectives: economic growth (rising real GDP), low inflation, low unemployment, balance of payments equilibrium. These objectives often conflict.", difficulty:2, examWeight:"high", relatedAtoms:["econ_macro_002"] },
  { id:"econ_macro_002", subject:"economics", level:"a_level", unit:"Macroeconomics", chapter:"National Income", atom:"GDP = C + I + G + (X-M). GDP measures total value of output in a year. Real GDP adjusts for inflation. GDP per capita = GDP divided by population.", difficulty:2, examWeight:"high", relatedAtoms:["econ_macro_001","econ_macro_003"] },
  { id:"econ_macro_003", subject:"economics", level:"a_level", unit:"Macroeconomics", chapter:"Inflation", atom:"Demand-pull inflation: excess aggregate demand (too much money chasing too few goods). Cost-push inflation: rising costs of production (e.g. oil price rise). Both measured by CPI.", difficulty:3, examWeight:"high", relatedAtoms:["econ_macro_002","econ_macro_004"] },
  { id:"econ_macro_004", subject:"economics", level:"a_level", unit:"Macroeconomics", chapter:"Unemployment", atom:"Types of unemployment: structural (skills mismatch), cyclical (lack of aggregate demand), frictional (between jobs), seasonal. Measured by claimant count or Labour Force Survey.", difficulty:3, examWeight:"high", relatedAtoms:["econ_macro_003"] },
  { id:"econ_macro_005", subject:"economics", level:"a_level", unit:"Macroeconomics", chapter:"Fiscal Policy", atom:"Fiscal policy: government spending and taxation. Expansionary (increase spending / cut taxes): boosts AD. Contractionary (cut spending / raise taxes): reduces AD. Affects the budget deficit.", difficulty:3, examWeight:"high", relatedAtoms:["econ_macro_006"] },
  { id:"econ_macro_006", subject:"economics", level:"a_level", unit:"Macroeconomics", chapter:"Monetary Policy", atom:"Monetary policy: central bank controls money supply and interest rates. Lower interest rates reduce cost of borrowing, increase spending, raise AD — stimulates growth but risks inflation.", difficulty:3, examWeight:"high", relatedAtoms:["econ_macro_005"] },
  { id:"econ_macro_007", subject:"economics", level:"a_level", unit:"Macroeconomics", chapter:"International Trade", atom:"Comparative advantage: countries should specialise in goods they produce at lower opportunity cost. Basis for mutual gains from trade even when one country is absolutely better at everything.", difficulty:3, examWeight:"high", relatedAtoms:["econ_macro_008"] },
  { id:"econ_macro_008", subject:"economics", level:"a_level", unit:"Macroeconomics", chapter:"Balance of Payments", atom:"Balance of payments: current account (trade in goods/services, income, transfers) + financial account + capital account = 0. Current account deficit means imports exceed exports.", difficulty:3, examWeight:"high", relatedAtoms:["econ_macro_007"] },

  // ═══ ENGLISH O LEVEL — 16 atoms ══════════════════════════
  { id:"eng_read_001", subject:"english", level:"o_level", unit:"Reading", chapter:"Evidence Finding", atom:"Finding evidence: locate specific words or phrases that answer the question. Quote directly. Use quotation marks. Never paraphrase when asked to find evidence.", difficulty:1, examWeight:"high", relatedAtoms:["eng_read_002"] },
  { id:"eng_read_002", subject:"english", level:"o_level", unit:"Reading", chapter:"Inference", atom:"Inference: reading between the lines. Evidence leads to implication. 'The character clenched his fists' implies anger. Must always be supported by textual evidence.", difficulty:2, examWeight:"high", relatedAtoms:["eng_read_001","eng_read_003"] },
  { id:"eng_read_003", subject:"english", level:"o_level", unit:"Reading", chapter:"Language Analysis", atom:"Analysing language: identify the technique, quote it, explain its effect on the reader. The effect on the reader is the most important and most commonly missed part.", difficulty:3, examWeight:"high", relatedAtoms:["eng_read_002","eng_read_004"] },
  { id:"eng_read_004", subject:"english", level:"o_level", unit:"Reading", chapter:"Figurative Language", atom:"Simile: comparing using like or as. Metaphor: describing something as if it IS something else. Personification: giving human qualities to non-human things.", difficulty:2, examWeight:"high", relatedAtoms:["eng_read_003"] },
  { id:"eng_read_005", subject:"english", level:"o_level", unit:"Reading", chapter:"Language Techniques", atom:"Alliteration: repetition of consonant sounds. Onomatopoeia: word sounds like its meaning (crash, buzz). Repetition: for emphasis. Rhetorical question: engages reader, no answer needed.", difficulty:2, examWeight:"high", relatedAtoms:["eng_read_004"] },
  { id:"eng_dir_001", subject:"english", level:"o_level", unit:"Directed Writing", chapter:"Format", atom:"Different formats require specific conventions: formal letter (address, date, Dear Sir/Madam, Yours faithfully); informal letter (Dear [name], Lots of love); report (headings, numbered sections).", difficulty:2, examWeight:"high", relatedAtoms:["eng_dir_002"] },
  { id:"eng_dir_002", subject:"english", level:"o_level", unit:"Directed Writing", chapter:"Register", atom:"Register must match audience and purpose. Formal register: no contractions, no slang, no first person (in reports). Informal register: conversational language is appropriate.", difficulty:2, examWeight:"high", relatedAtoms:["eng_dir_001","eng_dir_003"] },
  { id:"eng_dir_003", subject:"english", level:"o_level", unit:"Directed Writing", chapter:"Content Points", atom:"Directed writing: include ALL content points listed in the question. Examiners mark a checklist. A missing point always loses marks. Use the passage for content but rewrite in your own words.", difficulty:3, examWeight:"high", relatedAtoms:["eng_dir_002"] },
  { id:"eng_sum_001", subject:"english", level:"o_level", unit:"Summary Writing", chapter:"Summary Skills", atom:"Summary: select ONLY points relevant to the specific question. Do not include examples, extended explanations or quotations. Use own words throughout.", difficulty:2, examWeight:"high", relatedAtoms:["eng_sum_002"] },
  { id:"eng_sum_002", subject:"english", level:"o_level", unit:"Summary Writing", chapter:"Structure", atom:"Summary structure: one continuous paragraph. Count your points as you write them — usually 8 to 10 are needed. Do not use bullet points. Stay within the word limit.", difficulty:2, examWeight:"high", relatedAtoms:["eng_sum_001"] },
  { id:"eng_sum_003", subject:"english", level:"o_level", unit:"Summary Writing", chapter:"Own Words", atom:"Using your own words: avoid lifting phrases directly from the passage. Substitute synonyms and change sentence structure. Examiners check specifically for direct lifting.", difficulty:3, examWeight:"high", relatedAtoms:["eng_sum_002"] },
  { id:"eng_comp_001", subject:"english", level:"o_level", unit:"Composition", chapter:"Planning", atom:"Always plan before writing. Spend 5 minutes: note the central idea, plan 4 to 5 paragraphs, decide on opening and ending. Examiners reward structured, well-organised writing.", difficulty:2, examWeight:"high", relatedAtoms:["eng_comp_002"] },
  { id:"eng_comp_002", subject:"english", level:"o_level", unit:"Composition", chapter:"Opening and Ending", atom:"Strong opening: start in action (in medias res), rhetorical question, vivid image, surprising statement. Strong ending: circular (echoes opening), resolution, final lasting image.", difficulty:3, examWeight:"high", relatedAtoms:["eng_comp_001","eng_comp_003"] },
  { id:"eng_comp_003", subject:"english", level:"o_level", unit:"Composition", chapter:"Paragraphing", atom:"Each paragraph develops one main idea. Topic sentence at the start, developed with detail, example and effect. PEED structure: Point, Evidence, Explain, Develop.", difficulty:2, examWeight:"high", relatedAtoms:["eng_comp_002"] },
  { id:"eng_comp_004", subject:"english", level:"o_level", unit:"Composition", chapter:"Narrative Techniques", atom:"Show, do not tell: instead of she was angry, write her hands shook as she slammed the door. Use sensory detail: sight, sound, smell, touch, taste. Vary sentence length for effect.", difficulty:3, examWeight:"high", relatedAtoms:["eng_comp_003"] },
  { id:"eng_comp_005", subject:"english", level:"o_level", unit:"Composition", chapter:"Descriptive Writing", atom:"Descriptive writing: no plot required. Focus on atmosphere, setting and character. Use figurative language. Structure: zoom in from wide view to specific detail, or contrast before and after.", difficulty:3, examWeight:"high", relatedAtoms:["eng_comp_004"] },
];

// ── QUERY FUNCTIONS ──────────────────────────────────────────

const getAtomsBySubject = (subject) =>
  STARKY_ATOMS.filter(a => a.subject === subject);

const getAtomsByUnit = (subject, unit) =>
  STARKY_ATOMS.filter(a => a.subject === subject && a.unit === unit);

const getAtomsByDifficulty = (subject, difficulty) =>
  STARKY_ATOMS.filter(a => a.subject === subject && a.difficulty === difficulty);

const getHighWeightAtoms = (subject) =>
  STARKY_ATOMS.filter(a => a.subject === subject && a.examWeight === "high");

const getAtomById = (id) =>
  STARKY_ATOMS.find(a => a.id === id);

const getRelatedAtoms = (id) => {
  const atom = getAtomById(id);
  if (!atom) return [];
  return atom.relatedAtoms.map(rid => getAtomById(rid)).filter(Boolean);
};

const ATOM_COUNTS = {
  chemistry:   STARKY_ATOMS.filter(a => a.subject === "chemistry").length,
  physics:     STARKY_ATOMS.filter(a => a.subject === "physics").length,
  biology:     STARKY_ATOMS.filter(a => a.subject === "biology").length,
  mathematics: STARKY_ATOMS.filter(a => a.subject === "mathematics").length,
  economics:   STARKY_ATOMS.filter(a => a.subject === "economics").length,
  english:     STARKY_ATOMS.filter(a => a.subject === "english").length,
  total:       STARKY_ATOMS.length,
};

// Subjects available for Starky Atoms page display
const ATOMS_SUBJECTS = [
  { id: "chemistry",   label: "Chemistry",   level: "O Level", totalAtoms: ATOM_COUNTS.chemistry,   color: "#C9A84C", icon: "⚗️"  },
  { id: "physics",     label: "Physics",     level: "O Level", totalAtoms: ATOM_COUNTS.physics,     color: "#4C7BC9", icon: "⚡"  },
  { id: "biology",     label: "Biology",     level: "O Level", totalAtoms: ATOM_COUNTS.biology,     color: "#4CC97B", icon: "🧬"  },
  { id: "mathematics", label: "Mathematics", level: "O Level", totalAtoms: ATOM_COUNTS.mathematics, color: "#C94C4C", icon: "📐"  },
  { id: "economics",   label: "Economics",   level: "A Level", totalAtoms: ATOM_COUNTS.economics,   color: "#9B4CC9", icon: "📊"  },
  { id: "english",     label: "English",     level: "O Level", totalAtoms: ATOM_COUNTS.english,     color: "#C94C8B", icon: "✍️"  },
];

// Expansion roadmap for display on the Atoms page
const ATOMS_EXPANSION_PLAN = [
  { phase: "v1 — Live Now",    subjects: ["Chemistry","Physics","Biology","Mathematics","Economics","English"], atoms: 233 },
  { phase: "v2 — May 2026",    subjects: ["History","Computer Science","Accounting","Urdu"], atoms: 600 },
  { phase: "v3 — Sep 2026",    subjects: ["Full O Level suite + Pakistan Studies + Islamiyat"], atoms: 1200 },
  { phase: "v4 — 2027",        subjects: ["All Cambridge O and A Level subjects"], atoms: 5000 },
  { phase: "Target — 2027",    subjects: ["Complete Cambridge atom map"], atoms: 15000 },
];

module.exports = {
  STARKY_ATOMS,
  getAtomsBySubject,
  getAtomsByUnit,
  getAtomsByDifficulty,
  getHighWeightAtoms,
  getAtomById,
  getRelatedAtoms,
  ATOM_COUNTS,
  ATOMS_SUBJECTS,
  ATOMS_EXPANSION_PLAN,
};
