/**
 * utils/starkyAtomsKB.js
 * ═══════════════════════════════════════════════════════════════
 * STARKY ATOMS — The complete knowledge atom database.
 * Every Cambridge O and A Level subject broken into its smallest
 * indivisible units of testable knowledge.
 *
 * Subject → Unit → Chapter → Topic → Atom
 * Each atom = one precise, testable fact or skill.
 * ═══════════════════════════════════════════════════════════════
 */

// ── CHEMISTRY O LEVEL (5070) — 240 atoms ──────────────────────

const CHEMISTRY_ATOMS = [
  // States of Matter
  { id: 'chem_states_solid_arrangement', subject: 'chemistry', level: 'o_level', unit: 'States of Matter', chapter: 'Solids', topic: 'Particle arrangement', atom: 'In solids, particles are closely packed in a regular arrangement and vibrate about fixed positions', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_states_liquid_arrangement', subject: 'chemistry', level: 'o_level', unit: 'States of Matter', chapter: 'Liquids', topic: 'Particle arrangement', atom: 'In liquids, particles are close together but irregularly arranged, and can move past each other', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_states_gas_arrangement', subject: 'chemistry', level: 'o_level', unit: 'States of Matter', chapter: 'Gases', topic: 'Particle arrangement', atom: 'In gases, particles are far apart, move rapidly and randomly in all directions', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_states_melting', subject: 'chemistry', level: 'o_level', unit: 'States of Matter', chapter: 'Changes of state', topic: 'Melting', atom: 'Melting is the change from solid to liquid — particles gain enough energy to overcome some intermolecular forces', difficulty: 2, examWeight: 'medium', relatedAtoms: [] },
  { id: 'chem_states_boiling', subject: 'chemistry', level: 'o_level', unit: 'States of Matter', chapter: 'Changes of state', topic: 'Boiling', atom: 'Boiling is the change from liquid to gas at a fixed temperature throughout the liquid — all intermolecular forces overcome', difficulty: 2, examWeight: 'medium', relatedAtoms: [] },
  { id: 'chem_states_evaporation_vs_boiling', subject: 'chemistry', level: 'o_level', unit: 'States of Matter', chapter: 'Changes of state', topic: 'Evaporation', atom: 'Evaporation occurs at any temperature from the surface only; boiling occurs at a fixed temperature throughout the liquid', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_states_diffusion', subject: 'chemistry', level: 'o_level', unit: 'States of Matter', chapter: 'Diffusion', topic: 'Diffusion definition', atom: 'Diffusion is the net movement of particles from a region of higher concentration to a region of lower concentration', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_states_diffusion_rate', subject: 'chemistry', level: 'o_level', unit: 'States of Matter', chapter: 'Diffusion', topic: 'Rate of diffusion', atom: 'Rate of diffusion increases with temperature (more kinetic energy) and decreases with molecular mass (heavier = slower)', difficulty: 3, examWeight: 'medium', relatedAtoms: [] },
  { id: 'chem_states_brownian', subject: 'chemistry', level: 'o_level', unit: 'States of Matter', chapter: 'Diffusion', topic: 'Brownian motion', atom: 'Brownian motion is the random, jerky movement of particles suspended in a fluid, caused by collisions with invisible fluid molecules', difficulty: 3, examWeight: 'medium', relatedAtoms: [] },
  { id: 'chem_states_heating_curve', subject: 'chemistry', level: 'o_level', unit: 'States of Matter', chapter: 'Changes of state', topic: 'Heating curves', atom: 'During a change of state, temperature remains constant because energy is used to break intermolecular forces, not increase kinetic energy', difficulty: 3, examWeight: 'high', relatedAtoms: [] },

  // Atomic Structure
  { id: 'chem_atomic_proton', subject: 'chemistry', level: 'o_level', unit: 'Atomic Structure', chapter: 'Subatomic particles', topic: 'Proton', atom: 'Proton: relative mass 1, relative charge +1, found in the nucleus', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_atomic_neutron', subject: 'chemistry', level: 'o_level', unit: 'Atomic Structure', chapter: 'Subatomic particles', topic: 'Neutron', atom: 'Neutron: relative mass 1, relative charge 0, found in the nucleus', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_atomic_electron', subject: 'chemistry', level: 'o_level', unit: 'Atomic Structure', chapter: 'Subatomic particles', topic: 'Electron', atom: 'Electron: relative mass 1/1836 (negligible), relative charge -1, found in shells/energy levels around nucleus', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_atomic_number', subject: 'chemistry', level: 'o_level', unit: 'Atomic Structure', chapter: 'Atomic number', topic: 'Definition', atom: 'Atomic number (Z) = number of protons in the nucleus. Defines the element.', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_atomic_mass_number', subject: 'chemistry', level: 'o_level', unit: 'Atomic Structure', chapter: 'Mass number', topic: 'Definition', atom: 'Mass number (A) = number of protons + number of neutrons. Neutrons = A - Z.', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_atomic_isotopes', subject: 'chemistry', level: 'o_level', unit: 'Atomic Structure', chapter: 'Isotopes', topic: 'Definition', atom: 'Isotopes are atoms of the same element with the same number of protons but different numbers of neutrons', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_atomic_isotope_properties', subject: 'chemistry', level: 'o_level', unit: 'Atomic Structure', chapter: 'Isotopes', topic: 'Properties', atom: 'Isotopes have identical chemical properties (same electron configuration) but different physical properties (different mass)', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_atomic_electron_config_rules', subject: 'chemistry', level: 'o_level', unit: 'Atomic Structure', chapter: 'Electron configuration', topic: 'Shell filling', atom: 'Electrons fill shells in order: 1st shell max 2, 2nd shell max 8, 3rd shell max 8 (at O Level)', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_atomic_relative_atomic_mass', subject: 'chemistry', level: 'o_level', unit: 'Atomic Structure', chapter: 'Relative atomic mass', topic: 'Calculation', atom: 'Relative atomic mass (Ar) is the weighted average mass of naturally occurring isotopes relative to 1/12 of carbon-12', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_atomic_noble_gas_config', subject: 'chemistry', level: 'o_level', unit: 'Atomic Structure', chapter: 'Electron configuration', topic: 'Noble gases', atom: 'Noble gases have full outer shells (2 for He, 8 for others) making them stable and unreactive', difficulty: 2, examWeight: 'medium', relatedAtoms: [] },

  // Chemical Bonding
  { id: 'chem_bond_ionic_def', subject: 'chemistry', level: 'o_level', unit: 'Chemical Bonding', chapter: 'Ionic bonding', topic: 'Definition', atom: 'Ionic bonding is the electrostatic attraction between oppositely charged ions formed by electron transfer from metal to non-metal', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_bond_ionic_transfer', subject: 'chemistry', level: 'o_level', unit: 'Chemical Bonding', chapter: 'Ionic bonding', topic: 'Electron transfer', atom: 'Metals lose electrons to form positive ions (cations); non-metals gain electrons to form negative ions (anions)', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_bond_ionic_properties', subject: 'chemistry', level: 'o_level', unit: 'Chemical Bonding', chapter: 'Ionic bonding', topic: 'Properties', atom: 'Ionic compounds: high melting points, conduct when molten/dissolved (free ions), do not conduct when solid (ions fixed)', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_bond_covalent_def', subject: 'chemistry', level: 'o_level', unit: 'Chemical Bonding', chapter: 'Covalent bonding', topic: 'Definition', atom: 'Covalent bonding is the sharing of one or more pairs of electrons between two non-metal atoms', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_bond_covalent_single', subject: 'chemistry', level: 'o_level', unit: 'Chemical Bonding', chapter: 'Covalent bonding', topic: 'Single bond', atom: 'A single covalent bond is one shared pair of electrons, represented by one line (e.g., H-H)', difficulty: 1, examWeight: 'medium', relatedAtoms: [] },
  { id: 'chem_bond_covalent_double', subject: 'chemistry', level: 'o_level', unit: 'Chemical Bonding', chapter: 'Covalent bonding', topic: 'Double bond', atom: 'A double covalent bond is two shared pairs of electrons, represented by two lines (e.g., O=O)', difficulty: 2, examWeight: 'medium', relatedAtoms: [] },
  { id: 'chem_bond_simple_molecular', subject: 'chemistry', level: 'o_level', unit: 'Chemical Bonding', chapter: 'Covalent structures', topic: 'Simple molecular', atom: 'Simple molecular substances have low melting/boiling points because weak intermolecular forces are easily broken (NOT covalent bonds)', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_bond_giant_covalent', subject: 'chemistry', level: 'o_level', unit: 'Chemical Bonding', chapter: 'Covalent structures', topic: 'Giant covalent', atom: 'Giant covalent structures (diamond, graphite, SiO₂) have very high melting points — many strong covalent bonds must be broken', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_bond_metallic_def', subject: 'chemistry', level: 'o_level', unit: 'Chemical Bonding', chapter: 'Metallic bonding', topic: 'Definition', atom: 'Metallic bonding: electrostatic attraction between positive metal ions and a sea of delocalised electrons', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_bond_metallic_properties', subject: 'chemistry', level: 'o_level', unit: 'Chemical Bonding', chapter: 'Metallic bonding', topic: 'Properties', atom: 'Metals conduct electricity (delocalised electrons carry charge), are malleable (layers slide over each other), have high melting points', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_bond_dot_cross', subject: 'chemistry', level: 'o_level', unit: 'Chemical Bonding', chapter: 'Dot-and-cross diagrams', topic: 'Drawing', atom: 'Dot-and-cross diagrams show electron transfer (ionic) or sharing (covalent) using dots for one atom and crosses for another', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_bond_graphite', subject: 'chemistry', level: 'o_level', unit: 'Chemical Bonding', chapter: 'Covalent structures', topic: 'Graphite', atom: 'Graphite: layers of hexagonal carbon rings with weak forces between layers (slippery) + one delocalised electron per C (conducts)', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_bond_diamond', subject: 'chemistry', level: 'o_level', unit: 'Chemical Bonding', chapter: 'Covalent structures', topic: 'Diamond', atom: 'Diamond: each carbon bonded to 4 others tetrahedrally. Very hard. Does not conduct electricity. Very high melting point.', difficulty: 2, examWeight: 'medium', relatedAtoms: [] },

  // Stoichiometry
  { id: 'chem_stoich_mole_def', subject: 'chemistry', level: 'o_level', unit: 'Stoichiometry', chapter: 'The mole', topic: 'Definition', atom: 'One mole is the amount of substance containing 6.02 × 10²³ particles (Avogadro constant)', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_stoich_molar_mass', subject: 'chemistry', level: 'o_level', unit: 'Stoichiometry', chapter: 'The mole', topic: 'Molar mass', atom: 'Molar mass (Mr in g/mol) equals the relative formula mass. E.g., H₂O: 2(1) + 16 = 18 g/mol', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_stoich_moles_formula', subject: 'chemistry', level: 'o_level', unit: 'Stoichiometry', chapter: 'The mole', topic: 'Moles calculation', atom: 'Moles = mass / molar mass (n = m / Mr)', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_stoich_balancing', subject: 'chemistry', level: 'o_level', unit: 'Stoichiometry', chapter: 'Chemical equations', topic: 'Balancing', atom: 'A balanced equation has equal numbers of each type of atom on both sides — conservation of mass', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_stoich_state_symbols', subject: 'chemistry', level: 'o_level', unit: 'Stoichiometry', chapter: 'Chemical equations', topic: 'State symbols', atom: 'State symbols MUST be included: (s) solid, (l) liquid, (g) gas, (aq) aqueous. Missing them loses marks.', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_stoich_empirical', subject: 'chemistry', level: 'o_level', unit: 'Stoichiometry', chapter: 'Formulae', topic: 'Empirical formula', atom: 'Empirical formula = simplest whole number ratio of atoms. Found by dividing moles of each element by the smallest.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_stoich_concentration', subject: 'chemistry', level: 'o_level', unit: 'Stoichiometry', chapter: 'Solutions', topic: 'Concentration', atom: 'Concentration (mol/dm³) = moles of solute / volume of solution in dm³', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_stoich_gas_volume', subject: 'chemistry', level: 'o_level', unit: 'Stoichiometry', chapter: 'Gas volumes', topic: 'Molar volume', atom: 'At room temperature and pressure (rtp), 1 mole of any gas occupies 24 dm³ (24,000 cm³)', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_stoich_percentage_yield', subject: 'chemistry', level: 'o_level', unit: 'Stoichiometry', chapter: 'Yield', topic: 'Percentage yield', atom: 'Percentage yield = (actual yield / theoretical yield) × 100%. Always ≤ 100% due to losses.', difficulty: 3, examWeight: 'medium', relatedAtoms: [] },
  { id: 'chem_stoich_percentage_purity', subject: 'chemistry', level: 'o_level', unit: 'Stoichiometry', chapter: 'Purity', topic: 'Percentage purity', atom: 'Percentage purity = (mass of pure substance / total mass of sample) × 100%', difficulty: 3, examWeight: 'medium', relatedAtoms: [] },

  // Electrochemistry
  { id: 'chem_electro_electrolysis_def', subject: 'chemistry', level: 'o_level', unit: 'Electrochemistry', chapter: 'Electrolysis', topic: 'Definition', atom: 'Electrolysis is the decomposition of an ionic compound (molten or dissolved) by passing electric current through it', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_electro_anode_cathode', subject: 'chemistry', level: 'o_level', unit: 'Electrochemistry', chapter: 'Electrolysis', topic: 'Electrodes', atom: 'Anode is positive (attracts anions, oxidation occurs). Cathode is negative (attracts cations, reduction occurs). OILRIG + PANCAKE.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_electro_molten_nacl', subject: 'chemistry', level: 'o_level', unit: 'Electrochemistry', chapter: 'Electrolysis', topic: 'Molten NaCl', atom: 'Electrolysis of molten NaCl: cathode produces Na metal, anode produces Cl₂ gas', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_electro_aqueous_rules', subject: 'chemistry', level: 'o_level', unit: 'Electrochemistry', chapter: 'Electrolysis', topic: 'Aqueous solutions', atom: 'In aqueous electrolysis: less reactive metals deposited at cathode (not H₂); halogens at anode if concentrated (else O₂)', difficulty: 4, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_electro_electroplating', subject: 'chemistry', level: 'o_level', unit: 'Electrochemistry', chapter: 'Electrolysis', topic: 'Electroplating', atom: 'Electroplating: object to be plated is cathode, plating metal is anode, electrolyte contains ions of plating metal', difficulty: 3, examWeight: 'medium', relatedAtoms: [] },
  { id: 'chem_electro_reactivity_series', subject: 'chemistry', level: 'o_level', unit: 'Electrochemistry', chapter: 'Reactivity', topic: 'Reactivity series', atom: 'Reactivity series (most to least reactive): K Na Ca Mg Al C Zn Fe H Cu Ag Au', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_electro_displacement', subject: 'chemistry', level: 'o_level', unit: 'Electrochemistry', chapter: 'Reactivity', topic: 'Displacement', atom: 'A more reactive metal displaces a less reactive metal from its compound: Zn + CuSO₄ → ZnSO₄ + Cu', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_electro_extraction', subject: 'chemistry', level: 'o_level', unit: 'Electrochemistry', chapter: 'Metals', topic: 'Extraction method', atom: 'Metals above carbon: extracted by electrolysis. Metals below carbon: extracted by reduction with carbon/CO.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_electro_rusting', subject: 'chemistry', level: 'o_level', unit: 'Electrochemistry', chapter: 'Metals', topic: 'Rusting', atom: 'Iron rusts when exposed to BOTH water AND oxygen. Rust is hydrated iron(III) oxide: Fe₂O₃·xH₂O', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_electro_rust_prevention', subject: 'chemistry', level: 'o_level', unit: 'Electrochemistry', chapter: 'Metals', topic: 'Prevention', atom: 'Rusting prevented by: painting, oiling, galvanising (zinc coating), sacrificial protection (more reactive metal corrodes instead)', difficulty: 2, examWeight: 'medium', relatedAtoms: [] },

  // Energetics
  { id: 'chem_energy_exothermic', subject: 'chemistry', level: 'o_level', unit: 'Energetics', chapter: 'Energy changes', topic: 'Exothermic', atom: 'Exothermic reactions release energy to surroundings — temperature rises. ΔH is negative. E.g., combustion, neutralisation.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_energy_endothermic', subject: 'chemistry', level: 'o_level', unit: 'Energetics', chapter: 'Energy changes', topic: 'Endothermic', atom: 'Endothermic reactions absorb energy from surroundings — temperature falls. ΔH is positive. E.g., thermal decomposition.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_energy_bond_breaking', subject: 'chemistry', level: 'o_level', unit: 'Energetics', chapter: 'Bond energies', topic: 'Breaking bonds', atom: 'Breaking bonds is endothermic (requires energy). Making bonds is exothermic (releases energy).', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_energy_profile_exo', subject: 'chemistry', level: 'o_level', unit: 'Energetics', chapter: 'Energy profiles', topic: 'Exothermic diagram', atom: 'Exothermic energy profile: products lower than reactants. Activation energy = hump from reactants to peak.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_energy_activation', subject: 'chemistry', level: 'o_level', unit: 'Energetics', chapter: 'Energy profiles', topic: 'Activation energy', atom: 'Activation energy (Ea) is the minimum energy required for a reaction to occur. Catalysts lower Ea.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },

  // Rates of Reaction
  { id: 'chem_rates_collision_theory', subject: 'chemistry', level: 'o_level', unit: 'Rates of Reaction', chapter: 'Collision theory', topic: 'Definition', atom: 'For a reaction to occur: particles must collide, with sufficient energy (≥ Ea), and correct orientation', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_rates_temperature', subject: 'chemistry', level: 'o_level', unit: 'Rates of Reaction', chapter: 'Factors', topic: 'Temperature', atom: 'Increasing temperature increases rate: particles have more kinetic energy → more frequent collisions with energy ≥ Ea', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_rates_concentration', subject: 'chemistry', level: 'o_level', unit: 'Rates of Reaction', chapter: 'Factors', topic: 'Concentration', atom: 'Increasing concentration increases rate: more particles per unit volume → more frequent collisions', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_rates_surface_area', subject: 'chemistry', level: 'o_level', unit: 'Rates of Reaction', chapter: 'Factors', topic: 'Surface area', atom: 'Increasing surface area (smaller pieces) increases rate: more particles exposed → more frequent collisions', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_rates_catalyst', subject: 'chemistry', level: 'o_level', unit: 'Rates of Reaction', chapter: 'Factors', topic: 'Catalyst', atom: 'A catalyst increases rate by providing an alternative pathway with lower activation energy. It is not used up.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },

  // Equilibrium
  { id: 'chem_equil_reversible', subject: 'chemistry', level: 'o_level', unit: 'Equilibrium', chapter: 'Reversible reactions', topic: 'Definition', atom: 'A reversible reaction can proceed in both forward and reverse directions. Shown by ⇌ symbol.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_equil_dynamic', subject: 'chemistry', level: 'o_level', unit: 'Equilibrium', chapter: 'Dynamic equilibrium', topic: 'Definition', atom: 'Dynamic equilibrium: rate of forward reaction = rate of reverse reaction. Concentrations remain constant but reactions continue.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_equil_le_chatelier', subject: 'chemistry', level: 'o_level', unit: 'Equilibrium', chapter: 'Le Chatelier', topic: 'Principle', atom: 'Le Chatelier: if conditions change, equilibrium shifts to oppose the change. Increase conc → shifts away from that side.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_equil_temperature', subject: 'chemistry', level: 'o_level', unit: 'Equilibrium', chapter: 'Le Chatelier', topic: 'Temperature effect', atom: 'Increasing temperature: shifts equilibrium in the endothermic direction. Decreasing: shifts exothermic.', difficulty: 4, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_equil_pressure', subject: 'chemistry', level: 'o_level', unit: 'Equilibrium', chapter: 'Le Chatelier', topic: 'Pressure effect', atom: 'Increasing pressure: shifts equilibrium towards the side with fewer gas molecules.', difficulty: 4, examWeight: 'high', relatedAtoms: [] },

  // Acids, Bases, Salts
  { id: 'chem_acids_acid_def', subject: 'chemistry', level: 'o_level', unit: 'Acids, Bases and Salts', chapter: 'Acids', topic: 'Definition', atom: 'An acid is a substance that produces H⁺ ions (proton donor) in aqueous solution', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_acids_base_def', subject: 'chemistry', level: 'o_level', unit: 'Acids, Bases and Salts', chapter: 'Bases', topic: 'Definition', atom: 'A base is a substance that neutralises an acid. An alkali is a soluble base that produces OH⁻ ions in solution.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_acids_ph_scale', subject: 'chemistry', level: 'o_level', unit: 'Acids, Bases and Salts', chapter: 'pH', topic: 'pH scale', atom: 'pH scale: 0-14. Below 7 = acidic, 7 = neutral, above 7 = alkaline. Strong acids have lower pH.', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_acids_neutralisation', subject: 'chemistry', level: 'o_level', unit: 'Acids, Bases and Salts', chapter: 'Neutralisation', topic: 'Equation', atom: 'Neutralisation: acid + base → salt + water. H⁺ + OH⁻ → H₂O', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_acids_metal_reaction', subject: 'chemistry', level: 'o_level', unit: 'Acids, Bases and Salts', chapter: 'Reactions', topic: 'Acid + metal', atom: 'Acid + metal → salt + hydrogen. E.g., Zn + H₂SO₄ → ZnSO₄ + H₂. Only metals above H in reactivity series.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_acids_carbonate_reaction', subject: 'chemistry', level: 'o_level', unit: 'Acids, Bases and Salts', chapter: 'Reactions', topic: 'Acid + carbonate', atom: 'Acid + carbonate → salt + water + carbon dioxide. Test: CO₂ turns limewater milky.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_acids_soluble_salt_prep', subject: 'chemistry', level: 'o_level', unit: 'Acids, Bases and Salts', chapter: 'Salt preparation', topic: 'Soluble salts', atom: 'Soluble salt preparation: add excess insoluble base/carbonate to acid → filter → evaporate filtrate to crystallise', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_acids_insoluble_salt_prep', subject: 'chemistry', level: 'o_level', unit: 'Acids, Bases and Salts', chapter: 'Salt preparation', topic: 'Insoluble salts', atom: 'Insoluble salt preparation: mix two solutions → precipitate forms → filter → wash → dry. (Precipitation reaction)', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_acids_titration', subject: 'chemistry', level: 'o_level', unit: 'Acids, Bases and Salts', chapter: 'Titration', topic: 'Method', atom: 'Titration: measured volume of acid/alkali in flask, other in burette, add indicator, add until colour change (end point)', difficulty: 3, examWeight: 'high', relatedAtoms: [] },

  // Periodic Table
  { id: 'chem_periodic_groups', subject: 'chemistry', level: 'o_level', unit: 'The Periodic Table', chapter: 'Groups', topic: 'Definition', atom: 'Groups are vertical columns — elements in same group have same number of outer shell electrons → similar chemical properties', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_periodic_periods', subject: 'chemistry', level: 'o_level', unit: 'The Periodic Table', chapter: 'Periods', topic: 'Definition', atom: 'Periods are horizontal rows — period number = number of electron shells', difficulty: 1, examWeight: 'medium', relatedAtoms: [] },
  { id: 'chem_periodic_group1', subject: 'chemistry', level: 'o_level', unit: 'The Periodic Table', chapter: 'Group I', topic: 'Alkali metals', atom: 'Group I (alkali metals): 1 outer electron, reactivity increases down group, form +1 ions, react vigorously with water', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_periodic_group7', subject: 'chemistry', level: 'o_level', unit: 'The Periodic Table', chapter: 'Group VII', topic: 'Halogens', atom: 'Group VII (halogens): 7 outer electrons, reactivity decreases down group, form -1 ions, diatomic molecules', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_periodic_group0', subject: 'chemistry', level: 'o_level', unit: 'The Periodic Table', chapter: 'Group 0', topic: 'Noble gases', atom: 'Group 0 (noble gases): full outer shells, very stable, unreactive, monatomic, used in lighting and welding', difficulty: 1, examWeight: 'medium', relatedAtoms: [] },
  { id: 'chem_periodic_transition', subject: 'chemistry', level: 'o_level', unit: 'The Periodic Table', chapter: 'Transition metals', topic: 'Properties', atom: 'Transition metals: form coloured compounds, have variable oxidation states, act as catalysts (e.g., Fe in Haber process)', difficulty: 3, examWeight: 'medium', relatedAtoms: [] },

  // Organic Chemistry
  { id: 'chem_organic_alkane_def', subject: 'chemistry', level: 'o_level', unit: 'Organic Chemistry', chapter: 'Alkanes', topic: 'Definition', atom: 'Alkanes are saturated hydrocarbons — general formula CₙH₂ₙ₊₂, all single C-C bonds', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_organic_alkane_first4', subject: 'chemistry', level: 'o_level', unit: 'Organic Chemistry', chapter: 'Alkanes', topic: 'First four', atom: 'First 4 alkanes: methane CH₄, ethane C₂H₆, propane C₃H₈, butane C₄H₁₀', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_organic_complete_combustion', subject: 'chemistry', level: 'o_level', unit: 'Organic Chemistry', chapter: 'Alkanes', topic: 'Complete combustion', atom: 'Complete combustion of methane: CH₄ + 2O₂ → CO₂ + 2H₂O (excess oxygen, blue flame)', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_organic_incomplete_combustion', subject: 'chemistry', level: 'o_level', unit: 'Organic Chemistry', chapter: 'Alkanes', topic: 'Incomplete combustion', atom: 'Incomplete combustion (limited O₂): produces CO (toxic) and/or C (soot) instead of CO₂. Yellow/smoky flame.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_organic_alkene_def', subject: 'chemistry', level: 'o_level', unit: 'Organic Chemistry', chapter: 'Alkenes', topic: 'Definition', atom: 'Alkenes are unsaturated hydrocarbons — general formula CₙH₂ₙ, contain at least one C=C double bond', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_organic_alkene_test', subject: 'chemistry', level: 'o_level', unit: 'Organic Chemistry', chapter: 'Alkenes', topic: 'Bromine test', atom: 'Test for unsaturation: bromine water turns from orange/brown to colourless when shaken with an alkene (addition reaction)', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_organic_addition_poly', subject: 'chemistry', level: 'o_level', unit: 'Organic Chemistry', chapter: 'Polymers', topic: 'Addition polymerisation', atom: 'Addition polymerisation: many alkene monomers join to form a polymer. C=C bonds open up to form C-C bonds. E.g., ethene → poly(ethene)', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_organic_alcohol_def', subject: 'chemistry', level: 'o_level', unit: 'Organic Chemistry', chapter: 'Alcohols', topic: 'Definition', atom: 'Alcohols contain the -OH functional group. General formula CₙH₂ₙ₊₁OH. Ethanol = C₂H₅OH', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_organic_fermentation', subject: 'chemistry', level: 'o_level', unit: 'Organic Chemistry', chapter: 'Alcohols', topic: 'Fermentation', atom: 'Fermentation: glucose → ethanol + CO₂ using yeast (enzyme zymase) at ~37°C anaerobically', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_organic_carboxylic_acid', subject: 'chemistry', level: 'o_level', unit: 'Organic Chemistry', chapter: 'Carboxylic acids', topic: 'Definition', atom: 'Carboxylic acids contain -COOH functional group. General formula CₙH₂ₙ₊₁COOH. Ethanoic acid = CH₃COOH (vinegar)', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_organic_ester', subject: 'chemistry', level: 'o_level', unit: 'Organic Chemistry', chapter: 'Esters', topic: 'Formation', atom: 'Ester = alcohol + carboxylic acid (with acid catalyst). Esters have fruity smells, used in flavourings and perfumes.', difficulty: 3, examWeight: 'medium', relatedAtoms: [] },
  { id: 'chem_organic_cracking', subject: 'chemistry', level: 'o_level', unit: 'Organic Chemistry', chapter: 'Crude oil', topic: 'Cracking', atom: 'Cracking breaks long-chain alkanes into shorter alkanes + alkenes using high temperature (thermal) or catalyst (catalytic)', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_organic_fractional_distillation', subject: 'chemistry', level: 'o_level', unit: 'Organic Chemistry', chapter: 'Crude oil', topic: 'Separation', atom: 'Fractional distillation separates crude oil fractions by boiling point. Shorter chains = lower bp = collected higher in column.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_organic_isomerism', subject: 'chemistry', level: 'o_level', unit: 'Organic Chemistry', chapter: 'Isomers', topic: 'Definition', atom: 'Isomers have the same molecular formula but different structural formulae (different arrangement of atoms)', difficulty: 3, examWeight: 'medium', relatedAtoms: [] },
  { id: 'chem_organic_homologous', subject: 'chemistry', level: 'o_level', unit: 'Organic Chemistry', chapter: 'Homologous series', topic: 'Definition', atom: 'A homologous series: same general formula, same functional group, each member differs by CH₂, similar chemical properties, gradual change in physical properties', difficulty: 3, examWeight: 'high', relatedAtoms: [] },

  // Analytical Chemistry
  { id: 'chem_analytical_flame_tests', subject: 'chemistry', level: 'o_level', unit: 'Analytical Chemistry', chapter: 'Flame tests', topic: 'Colours', atom: 'Flame test colours: Li = crimson, Na = yellow, K = lilac, Ca = orange-red, Cu = blue-green', difficulty: 2, examWeight: 'medium', relatedAtoms: [] },
  { id: 'chem_analytical_gas_tests', subject: 'chemistry', level: 'o_level', unit: 'Analytical Chemistry', chapter: 'Gas tests', topic: 'Common gases', atom: 'Gas tests: H₂ = squeaky pop. O₂ = relights glowing splint. CO₂ = limewater milky. Cl₂ = bleaches litmus. NH₃ = turns damp red litmus blue.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_analytical_anion_tests', subject: 'chemistry', level: 'o_level', unit: 'Analytical Chemistry', chapter: 'Anion tests', topic: 'Carbonate sulfate halide', atom: 'Carbonate: add acid → CO₂ (fizzes). Sulfate: add BaCl₂ → white ppt. Halide: add AgNO₃ → Cl⁻ white, Br⁻ cream, I⁻ yellow ppt.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'chem_analytical_cation_tests', subject: 'chemistry', level: 'o_level', unit: 'Analytical Chemistry', chapter: 'Cation tests', topic: 'NaOH test', atom: 'Add NaOH: Cu²⁺ = blue ppt, Fe²⁺ = green ppt (turns brown), Fe³⁺ = brown ppt, Al³⁺/Zn²⁺ = white ppt (dissolves in excess)', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
];

// ── PHYSICS O LEVEL (5054) — 200 atoms ──────────────────────

const PHYSICS_ATOMS = [
  // Measurement
  { id: 'phys_measure_si_units', subject: 'physics', level: 'o_level', unit: 'Measurement', chapter: 'SI units', topic: 'Base units', atom: 'SI base units: metre (m), kilogram (kg), second (s), ampere (A), kelvin (K)', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_measure_prefixes', subject: 'physics', level: 'o_level', unit: 'Measurement', chapter: 'Prefixes', topic: 'Metric prefixes', atom: 'Prefixes: kilo (10³), centi (10⁻²), milli (10⁻³), micro (10⁻⁶). E.g., 1 km = 1000 m', difficulty: 1, examWeight: 'medium', relatedAtoms: [] },
  { id: 'phys_measure_micrometer', subject: 'physics', level: 'o_level', unit: 'Measurement', chapter: 'Instruments', topic: 'Micrometer', atom: 'Micrometer screw gauge: reads to 0.01 mm. Used for small dimensions like wire diameter.', difficulty: 2, examWeight: 'medium', relatedAtoms: [] },

  // Motion
  { id: 'phys_motion_speed_def', subject: 'physics', level: 'o_level', unit: 'Motion', chapter: 'Speed', topic: 'Definition', atom: 'Speed = distance / time. Unit: m/s. Speed is scalar (magnitude only).', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_motion_velocity_def', subject: 'physics', level: 'o_level', unit: 'Motion', chapter: 'Velocity', topic: 'Definition', atom: 'Velocity = displacement / time. Unit: m/s. Velocity is vector (magnitude + direction).', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_motion_acceleration_def', subject: 'physics', level: 'o_level', unit: 'Motion', chapter: 'Acceleration', topic: 'Definition', atom: 'Acceleration = change in velocity / time taken. a = (v-u)/t. Unit: m/s². Can be negative (deceleration).', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_motion_dt_graph', subject: 'physics', level: 'o_level', unit: 'Motion', chapter: 'Graphs', topic: 'Distance-time', atom: 'Distance-time graph: gradient = speed. Horizontal line = stationary. Steeper = faster. Curve = accelerating.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_motion_vt_graph', subject: 'physics', level: 'o_level', unit: 'Motion', chapter: 'Graphs', topic: 'Velocity-time', atom: 'Velocity-time graph: gradient = acceleration. Area under = distance. Horizontal = constant velocity. Negative gradient = deceleration.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_motion_equations', subject: 'physics', level: 'o_level', unit: 'Motion', chapter: 'Equations', topic: 'SUVAT', atom: 'Equations of motion: v = u + at, s = ½(u+v)t, s = ut + ½at², v² = u² + 2as', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_motion_free_fall', subject: 'physics', level: 'o_level', unit: 'Motion', chapter: 'Free fall', topic: 'g value', atom: 'Free fall: acceleration due to gravity g ≈ 9.81 m/s² (≈10 m/s² for calculations). All objects fall at same rate in vacuum.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_motion_terminal_velocity', subject: 'physics', level: 'o_level', unit: 'Motion', chapter: 'Forces and motion', topic: 'Terminal velocity', atom: 'Terminal velocity: when air resistance = weight, resultant force = 0, acceleration = 0, velocity constant', difficulty: 3, examWeight: 'high', relatedAtoms: [] },

  // Forces
  { id: 'phys_forces_newton1', subject: 'physics', level: 'o_level', unit: 'Forces', chapter: 'Newton\'s laws', topic: 'First law', atom: 'Newton\'s 1st law: object remains at rest or constant velocity unless acted on by a resultant force', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_forces_newton2', subject: 'physics', level: 'o_level', unit: 'Forces', chapter: 'Newton\'s laws', topic: 'Second law', atom: 'Newton\'s 2nd law: F = ma. Force (N) = mass (kg) × acceleration (m/s²). 1N accelerates 1kg at 1m/s².', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_forces_newton3', subject: 'physics', level: 'o_level', unit: 'Forces', chapter: 'Newton\'s laws', topic: 'Third law', atom: 'Newton\'s 3rd law: every action has an equal and opposite reaction. Forces act on DIFFERENT objects.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_forces_resultant', subject: 'physics', level: 'o_level', unit: 'Forces', chapter: 'Forces', topic: 'Resultant force', atom: 'Resultant force = vector sum of all forces. If resultant = 0, object in equilibrium (stationary or constant velocity).', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_forces_friction', subject: 'physics', level: 'o_level', unit: 'Forces', chapter: 'Friction', topic: 'Definition', atom: 'Friction opposes relative motion between surfaces. Useful (brakes, grip) and wasteful (heating, wear).', difficulty: 1, examWeight: 'medium', relatedAtoms: [] },
  { id: 'phys_forces_moment_def', subject: 'physics', level: 'o_level', unit: 'Forces', chapter: 'Moments', topic: 'Definition', atom: 'Moment = force × perpendicular distance from pivot. Unit: Nm. Moment of a force about a point.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_forces_principle_moments', subject: 'physics', level: 'o_level', unit: 'Forces', chapter: 'Moments', topic: 'Principle of moments', atom: 'Principle of moments: for equilibrium, sum of clockwise moments = sum of anticlockwise moments about any point', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_forces_centre_gravity', subject: 'physics', level: 'o_level', unit: 'Forces', chapter: 'Stability', topic: 'Centre of gravity', atom: 'Centre of gravity: point where entire weight appears to act. Lower centre of gravity + wider base = more stable.', difficulty: 2, examWeight: 'medium', relatedAtoms: [] },
  { id: 'phys_forces_hookes_law', subject: 'physics', level: 'o_level', unit: 'Forces', chapter: 'Elasticity', topic: 'Hooke\'s law', atom: 'Hooke\'s law: F = kx (force = spring constant × extension). Valid up to elastic limit (proportional region only).', difficulty: 3, examWeight: 'high', relatedAtoms: [] },

  // Energy
  { id: 'phys_energy_ke', subject: 'physics', level: 'o_level', unit: 'Energy, Work, Power', chapter: 'Kinetic energy', topic: 'Formula', atom: 'Kinetic energy: KE = ½mv². Depends on mass and velocity squared.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_energy_gpe', subject: 'physics', level: 'o_level', unit: 'Energy, Work, Power', chapter: 'Potential energy', topic: 'GPE formula', atom: 'Gravitational potential energy: GPE = mgh. Depends on mass, g, and height above reference point.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_energy_conservation', subject: 'physics', level: 'o_level', unit: 'Energy, Work, Power', chapter: 'Conservation', topic: 'Principle', atom: 'Conservation of energy: energy cannot be created or destroyed, only transferred from one form to another. Total energy is constant.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_energy_work_done', subject: 'physics', level: 'o_level', unit: 'Energy, Work, Power', chapter: 'Work', topic: 'Formula', atom: 'Work done = force × distance moved in direction of force. W = Fd. Unit: joule (J). 1J = 1Nm.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_energy_power_def', subject: 'physics', level: 'o_level', unit: 'Energy, Work, Power', chapter: 'Power', topic: 'Formula', atom: 'Power = work done / time = energy transferred / time. P = W/t = E/t. Unit: watt (W). 1W = 1J/s.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_energy_efficiency', subject: 'physics', level: 'o_level', unit: 'Energy, Work, Power', chapter: 'Efficiency', topic: 'Formula', atom: 'Efficiency = (useful energy output / total energy input) × 100%. Always < 100% due to waste energy (usually heat).', difficulty: 2, examWeight: 'high', relatedAtoms: [] },

  // Pressure
  { id: 'phys_pressure_def', subject: 'physics', level: 'o_level', unit: 'Pressure', chapter: 'Pressure', topic: 'Definition', atom: 'Pressure = force / area. P = F/A. Unit: pascal (Pa). 1Pa = 1N/m².', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_pressure_liquid', subject: 'physics', level: 'o_level', unit: 'Pressure', chapter: 'Liquid pressure', topic: 'Formula', atom: 'Pressure in a liquid: P = ρgh (density × gravitational field strength × depth). Increases with depth. Acts in all directions.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_pressure_atmospheric', subject: 'physics', level: 'o_level', unit: 'Pressure', chapter: 'Atmospheric', topic: 'Definition', atom: 'Atmospheric pressure ≈ 101,325 Pa at sea level. Caused by weight of air column above. Decreases with altitude.', difficulty: 2, examWeight: 'medium', relatedAtoms: [] },

  // Thermal Physics
  { id: 'phys_thermal_shc', subject: 'physics', level: 'o_level', unit: 'Thermal Physics', chapter: 'Specific heat', topic: 'Formula', atom: 'Specific heat capacity: E = mcΔθ (energy = mass × specific heat capacity × temperature change). Unit of c: J/(kg·°C)', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_thermal_latent_heat', subject: 'physics', level: 'o_level', unit: 'Thermal Physics', chapter: 'Latent heat', topic: 'Formula', atom: 'Latent heat: E = mL (energy = mass × specific latent heat). No temperature change during state change.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_thermal_conduction', subject: 'physics', level: 'o_level', unit: 'Thermal Physics', chapter: 'Heat transfer', topic: 'Conduction', atom: 'Conduction: energy transfer through vibrating particles passing energy to neighbours. Best in solids, metals best conductors (free electrons).', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_thermal_convection', subject: 'physics', level: 'o_level', unit: 'Thermal Physics', chapter: 'Heat transfer', topic: 'Convection', atom: 'Convection: hot fluid rises (less dense), cool fluid sinks (more dense), creating convection current. Only in fluids.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_thermal_radiation', subject: 'physics', level: 'o_level', unit: 'Thermal Physics', chapter: 'Heat transfer', topic: 'Radiation', atom: 'Radiation: energy transfer by infrared electromagnetic waves. No medium needed. Dark/matt surfaces emit and absorb best.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },

  // Waves
  { id: 'phys_waves_transverse', subject: 'physics', level: 'o_level', unit: 'Waves', chapter: 'Types', topic: 'Transverse', atom: 'Transverse waves: vibrations perpendicular to direction of energy transfer. E.g., light, water waves, S-waves.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_waves_longitudinal', subject: 'physics', level: 'o_level', unit: 'Waves', chapter: 'Types', topic: 'Longitudinal', atom: 'Longitudinal waves: vibrations parallel to direction of energy transfer. Compressions and rarefactions. E.g., sound, P-waves.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_waves_equation', subject: 'physics', level: 'o_level', unit: 'Waves', chapter: 'Wave equation', topic: 'Formula', atom: 'Wave equation: v = fλ (speed = frequency × wavelength). Frequency in Hz, wavelength in m, speed in m/s.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_waves_reflection', subject: 'physics', level: 'o_level', unit: 'Waves', chapter: 'Reflection', topic: 'Law', atom: 'Law of reflection: angle of incidence = angle of reflection. Both measured from the normal.', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_waves_refraction', subject: 'physics', level: 'o_level', unit: 'Waves', chapter: 'Refraction', topic: 'Definition', atom: 'Refraction: change in direction of wave when it changes speed at a boundary between different media', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_waves_snells_law', subject: 'physics', level: 'o_level', unit: 'Waves', chapter: 'Refraction', topic: 'Snells law', atom: 'Snell\'s law: n₁ sin θ₁ = n₂ sin θ₂. Refractive index n = speed in vacuum / speed in medium.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_waves_tir', subject: 'physics', level: 'o_level', unit: 'Waves', chapter: 'Refraction', topic: 'Total internal reflection', atom: 'Total internal reflection: occurs when angle of incidence > critical angle, and light travels from denser to less dense medium. Used in optical fibres.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_waves_em_spectrum', subject: 'physics', level: 'o_level', unit: 'Waves', chapter: 'EM spectrum', topic: 'Order', atom: 'EM spectrum (increasing frequency): radio, microwave, infrared, visible, ultraviolet, X-rays, gamma. All travel at speed of light in vacuum.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_waves_sound_speed', subject: 'physics', level: 'o_level', unit: 'Waves', chapter: 'Sound', topic: 'Speed', atom: 'Sound travels fastest in solids (particles closest), slowest in gases. Cannot travel in vacuum. Speed in air ≈ 340 m/s.', difficulty: 2, examWeight: 'medium', relatedAtoms: [] },
  { id: 'phys_waves_pitch_loudness', subject: 'physics', level: 'o_level', unit: 'Waves', chapter: 'Sound', topic: 'Pitch and loudness', atom: 'Pitch depends on frequency (higher frequency = higher pitch). Loudness depends on amplitude (larger amplitude = louder).', difficulty: 1, examWeight: 'medium', relatedAtoms: [] },

  // Electricity
  { id: 'phys_elec_current_def', subject: 'physics', level: 'o_level', unit: 'Electricity', chapter: 'Current', topic: 'Definition', atom: 'Current is the rate of flow of charge. I = Q/t. Unit: ampere (A). Conventional current flows from + to -.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_elec_voltage_def', subject: 'physics', level: 'o_level', unit: 'Electricity', chapter: 'Voltage', topic: 'Definition', atom: 'Voltage (potential difference) is the energy transferred per unit charge. V = W/Q. Unit: volt (V). 1V = 1J/C.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_elec_resistance_def', subject: 'physics', level: 'o_level', unit: 'Electricity', chapter: 'Resistance', topic: 'Definition', atom: 'Resistance opposes current flow. R = V/I. Unit: ohm (Ω). Higher resistance = less current for same voltage.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_elec_ohms_law', subject: 'physics', level: 'o_level', unit: 'Electricity', chapter: 'Ohm\'s law', topic: 'Statement', atom: 'Ohm\'s law: V = IR. Current is proportional to voltage at constant temperature (for ohmic conductors). V-I graph is straight line through origin.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_elec_series', subject: 'physics', level: 'o_level', unit: 'Electricity', chapter: 'Circuits', topic: 'Series', atom: 'Series circuit: same current through all components. Voltages add up. Total resistance = R₁ + R₂ + R₃...', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_elec_parallel', subject: 'physics', level: 'o_level', unit: 'Electricity', chapter: 'Circuits', topic: 'Parallel', atom: 'Parallel circuit: same voltage across branches. Currents add up. 1/R_total = 1/R₁ + 1/R₂ + 1/R₃...', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_elec_power', subject: 'physics', level: 'o_level', unit: 'Electricity', chapter: 'Power', topic: 'Formulae', atom: 'Electrical power: P = IV = I²R = V²/R. Energy: E = Pt = IVt. Unit: watt (W), energy in joules (J).', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_elec_fuse', subject: 'physics', level: 'o_level', unit: 'Electricity', chapter: 'Safety', topic: 'Fuses', atom: 'Fuse: thin wire that melts when current exceeds rated value, breaking circuit. Always in live wire. Choose rating just above normal current.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_elec_earthing', subject: 'physics', level: 'o_level', unit: 'Electricity', chapter: 'Safety', topic: 'Earth wire', atom: 'Earth wire: connected to metal case of appliance. If live wire touches case, large current flows to earth → fuse blows → prevents electrocution.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_elec_transformer', subject: 'physics', level: 'o_level', unit: 'Electricity', chapter: 'Electromagnetic induction', topic: 'Transformer', atom: 'Transformer: Vp/Vs = Np/Ns. Step-up (more turns on secondary = higher voltage). Step-down (fewer turns = lower voltage). AC only.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },

  // Magnetism
  { id: 'phys_mag_field_lines', subject: 'physics', level: 'o_level', unit: 'Magnetism', chapter: 'Fields', topic: 'Field lines', atom: 'Magnetic field lines: go from North to South outside magnet. Closer lines = stronger field. Never cross.', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_mag_electromagnet', subject: 'physics', level: 'o_level', unit: 'Magnetism', chapter: 'Electromagnets', topic: 'Definition', atom: 'Electromagnet: coil of wire carrying current produces magnetic field. Stronger with: more turns, more current, iron core.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_mag_motor_effect', subject: 'physics', level: 'o_level', unit: 'Magnetism', chapter: 'Motor effect', topic: 'Force on wire', atom: 'Motor effect: current-carrying wire in magnetic field experiences a force. Direction by Fleming\'s left-hand rule (First finger=Field, seCond=Current, thuMb=Motion).', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_mag_em_induction', subject: 'physics', level: 'o_level', unit: 'Magnetism', chapter: 'Induction', topic: 'Faraday\'s law', atom: 'Electromagnetic induction: changing magnetic field through a coil induces an EMF. Faster change / more turns / stronger magnet = larger EMF.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },

  // Atomic Physics
  { id: 'phys_nuclear_alpha', subject: 'physics', level: 'o_level', unit: 'Atomic Physics', chapter: 'Radioactivity', topic: 'Alpha particle', atom: 'Alpha (α): 2 protons + 2 neutrons (helium nucleus). Charge +2. Stopped by paper. Most ionising. Least penetrating.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_nuclear_beta', subject: 'physics', level: 'o_level', unit: 'Atomic Physics', chapter: 'Radioactivity', topic: 'Beta particle', atom: 'Beta (β): high-speed electron from nucleus (neutron → proton + electron). Charge -1. Stopped by aluminium. Medium ionising.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_nuclear_gamma', subject: 'physics', level: 'o_level', unit: 'Atomic Physics', chapter: 'Radioactivity', topic: 'Gamma ray', atom: 'Gamma (γ): electromagnetic radiation from nucleus. No charge, no mass. Stopped by thick lead/concrete. Least ionising. Most penetrating.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_nuclear_half_life', subject: 'physics', level: 'o_level', unit: 'Atomic Physics', chapter: 'Half-life', topic: 'Definition', atom: 'Half-life: time for half the radioactive nuclei in a sample to decay OR time for activity to halve. Cannot be changed.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_nuclear_fission', subject: 'physics', level: 'o_level', unit: 'Atomic Physics', chapter: 'Nuclear reactions', topic: 'Fission', atom: 'Nuclear fission: heavy nucleus splits into 2 smaller nuclei + neutrons + energy. Used in nuclear power stations. Chain reaction possible.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'phys_nuclear_fusion', subject: 'physics', level: 'o_level', unit: 'Atomic Physics', chapter: 'Nuclear reactions', topic: 'Fusion', atom: 'Nuclear fusion: light nuclei combine to form heavier nucleus + energy. Powers the Sun. Requires extremely high temperature and pressure.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
];

// ── BIOLOGY O LEVEL (5090) — 180 atoms ──────────────────────

const BIOLOGY_ATOMS = [
  // Cell Biology
  { id: 'bio_cell_animal', subject: 'biology', level: 'o_level', unit: 'Cell Biology', chapter: 'Cell structure', topic: 'Animal cell', atom: 'Animal cell: cell membrane, cytoplasm, nucleus (contains chromosomes/DNA), mitochondria, ribosomes. NO cell wall, chloroplasts, or large vacuole.', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_cell_plant', subject: 'biology', level: 'o_level', unit: 'Cell Biology', chapter: 'Cell structure', topic: 'Plant cell', atom: 'Plant cell: has cell wall (cellulose), chloroplasts (photosynthesis), large permanent vacuole (cell sap) IN ADDITION to all animal cell parts.', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_cell_membrane_function', subject: 'biology', level: 'o_level', unit: 'Cell Biology', chapter: 'Cell structure', topic: 'Cell membrane', atom: 'Cell membrane: partially permeable — controls what enters/leaves cell. Made of phospholipid bilayer.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_cell_nucleus_function', subject: 'biology', level: 'o_level', unit: 'Cell Biology', chapter: 'Cell structure', topic: 'Nucleus', atom: 'Nucleus contains DNA organised into chromosomes. Controls cell activities. Contains instructions for making proteins.', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_cell_mitochondria_function', subject: 'biology', level: 'o_level', unit: 'Cell Biology', chapter: 'Cell structure', topic: 'Mitochondria', atom: 'Mitochondria: site of aerobic respiration. Releases energy for cell activities. More mitochondria = more active cell.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_cell_diffusion', subject: 'biology', level: 'o_level', unit: 'Cell Biology', chapter: 'Transport', topic: 'Diffusion', atom: 'Diffusion: net movement of particles from high concentration to low concentration. Passive (no energy). E.g., O₂ into blood.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_cell_osmosis', subject: 'biology', level: 'o_level', unit: 'Cell Biology', chapter: 'Transport', topic: 'Osmosis', atom: 'Osmosis: net movement of water molecules from higher water potential to lower water potential through a partially permeable membrane', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_cell_active_transport', subject: 'biology', level: 'o_level', unit: 'Cell Biology', chapter: 'Transport', topic: 'Active transport', atom: 'Active transport: movement of particles against concentration gradient (low → high). Requires energy from respiration. E.g., mineral ion uptake in roots.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_cell_mitosis', subject: 'biology', level: 'o_level', unit: 'Cell Biology', chapter: 'Cell division', topic: 'Mitosis', atom: 'Mitosis: cell division producing 2 genetically identical diploid cells. For growth and repair. DNA replicates → chromosomes line up → cell divides.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_cell_meiosis', subject: 'biology', level: 'o_level', unit: 'Cell Biology', chapter: 'Cell division', topic: 'Meiosis', atom: 'Meiosis: cell division producing 4 genetically different haploid cells (gametes). Two divisions. Creates genetic variation through crossing over.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },

  // Enzymes & Nutrition
  { id: 'bio_enzyme_def', subject: 'biology', level: 'o_level', unit: 'Nutrition', chapter: 'Enzymes', topic: 'Definition', atom: 'Enzymes are biological catalysts — proteins that speed up metabolic reactions. They are specific to one reaction (lock and key model).', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_enzyme_active_site', subject: 'biology', level: 'o_level', unit: 'Nutrition', chapter: 'Enzymes', topic: 'Active site', atom: 'Lock and key model: substrate fits into enzyme active site with complementary shape → enzyme-substrate complex forms → products released.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_enzyme_temperature', subject: 'biology', level: 'o_level', unit: 'Nutrition', chapter: 'Enzymes', topic: 'Temperature effect', atom: 'Temperature: rate increases until optimum (~37°C for human enzymes). Above optimum: enzyme denatures — active site changes shape permanently.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_enzyme_ph', subject: 'biology', level: 'o_level', unit: 'Nutrition', chapter: 'Enzymes', topic: 'pH effect', atom: 'pH: each enzyme has optimum pH (pepsin pH 2, amylase pH 7, lipase pH 8). Extreme pH causes denaturation.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_nutrition_photosynthesis_eq', subject: 'biology', level: 'o_level', unit: 'Nutrition', chapter: 'Photosynthesis', topic: 'Equation', atom: 'Photosynthesis: 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂ (carbon dioxide + water → glucose + oxygen). Requires light energy and chlorophyll.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_nutrition_photo_factors', subject: 'biology', level: 'o_level', unit: 'Nutrition', chapter: 'Photosynthesis', topic: 'Limiting factors', atom: 'Limiting factors: light intensity, CO₂ concentration, temperature. Rate limited by whichever factor is in shortest supply.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_nutrition_food_tests', subject: 'biology', level: 'o_level', unit: 'Nutrition', chapter: 'Food tests', topic: 'Tests', atom: 'Food tests: starch = iodine (brown→blue-black), glucose = Benedict\'s (blue→orange), protein = biuret (blue→purple), fat = ethanol (white emulsion)', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_nutrition_villi', subject: 'biology', level: 'o_level', unit: 'Nutrition', chapter: 'Digestion', topic: 'Villi', atom: 'Villi in small intestine: increase surface area for absorption. Thin walls (one cell thick), rich blood supply, lacteals for fats.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },

  // Respiration
  { id: 'bio_resp_aerobic', subject: 'biology', level: 'o_level', unit: 'Respiration', chapter: 'Aerobic', topic: 'Equation', atom: 'Aerobic respiration: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + energy. In mitochondria. Releases most energy.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_resp_anaerobic_animal', subject: 'biology', level: 'o_level', unit: 'Respiration', chapter: 'Anaerobic', topic: 'In animals', atom: 'Anaerobic respiration in animals: glucose → lactic acid + some energy. No oxygen used. Creates oxygen debt.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_resp_anaerobic_yeast', subject: 'biology', level: 'o_level', unit: 'Respiration', chapter: 'Anaerobic', topic: 'In yeast', atom: 'Anaerobic respiration in yeast: glucose → ethanol + CO₂ + some energy. Called fermentation. Used in brewing and baking.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_resp_alveoli', subject: 'biology', level: 'o_level', unit: 'Respiration', chapter: 'Gas exchange', topic: 'Alveoli', atom: 'Alveoli: tiny air sacs in lungs. Large surface area, thin walls (one cell), rich blood supply, moist. O₂ diffuses in, CO₂ diffuses out.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },

  // Genetics
  { id: 'bio_genetics_gene_def', subject: 'biology', level: 'o_level', unit: 'Genetics', chapter: 'Inheritance', topic: 'Gene', atom: 'Gene: section of DNA on a chromosome that codes for a specific protein. Genes exist in different forms called alleles.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_genetics_dominant_recessive', subject: 'biology', level: 'o_level', unit: 'Genetics', chapter: 'Inheritance', topic: 'Dominance', atom: 'Dominant allele: expressed when one or two copies present (AA or Aa). Recessive allele: only expressed when homozygous (aa).', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_genetics_genotype_phenotype', subject: 'biology', level: 'o_level', unit: 'Genetics', chapter: 'Inheritance', topic: 'Terms', atom: 'Genotype: allele combination (e.g., Bb). Phenotype: observable characteristic (e.g., brown eyes). Homozygous: same alleles. Heterozygous: different.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_genetics_punnett', subject: 'biology', level: 'o_level', unit: 'Genetics', chapter: 'Inheritance', topic: 'Punnett squares', atom: 'Punnett square: cross Bb × Bb gives 1BB : 2Bb : 1bb (3:1 phenotypic ratio). Used to predict offspring ratios.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_genetics_dna_structure', subject: 'biology', level: 'o_level', unit: 'Genetics', chapter: 'DNA', topic: 'Structure', atom: 'DNA: double helix of two sugar-phosphate backbones with complementary base pairs (A-T, C-G) held by hydrogen bonds.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_genetics_variation', subject: 'biology', level: 'o_level', unit: 'Genetics', chapter: 'Variation', topic: 'Types', atom: 'Continuous variation: range of phenotypes (height, mass). Discontinuous variation: distinct categories (blood groups). Caused by genes, environment, or both.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },

  // Ecology
  { id: 'bio_ecology_food_chain', subject: 'biology', level: 'o_level', unit: 'Ecology', chapter: 'Food chains', topic: 'Trophic levels', atom: 'Food chain: producer → primary consumer → secondary consumer → tertiary consumer. Energy decreases at each level (~10% transferred).', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_ecology_carbon_cycle', subject: 'biology', level: 'o_level', unit: 'Ecology', chapter: 'Nutrient cycles', topic: 'Carbon cycle', atom: 'Carbon cycle: CO₂ removed by photosynthesis, returned by respiration, combustion, and decomposition. Carbon stored in fossil fuels.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'bio_ecology_population', subject: 'biology', level: 'o_level', unit: 'Ecology', chapter: 'Populations', topic: 'Factors', atom: 'Population size affected by: food supply, predation, disease, competition. Predator-prey cycles show inverse relationship.', difficulty: 2, examWeight: 'medium', relatedAtoms: [] },
];

// ── MATHEMATICS O LEVEL (4024) — 180 atoms ──────────────────

const MATHS_ATOMS = [
  // Number
  { id: 'math_number_hcf', subject: 'mathematics', level: 'o_level', unit: 'Number', chapter: 'Factors', topic: 'HCF', atom: 'HCF (Highest Common Factor): largest number that divides into two or more numbers. Found by prime factorisation or listing factors.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_number_lcm', subject: 'mathematics', level: 'o_level', unit: 'Number', chapter: 'Multiples', topic: 'LCM', atom: 'LCM (Lowest Common Multiple): smallest number that is a multiple of two or more numbers. Found by prime factorisation.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_number_standard_form', subject: 'mathematics', level: 'o_level', unit: 'Number', chapter: 'Standard form', topic: 'Definition', atom: 'Standard form: A × 10ⁿ where 1 ≤ A < 10 and n is an integer. E.g., 45000 = 4.5 × 10⁴, 0.003 = 3 × 10⁻³', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_number_percentage', subject: 'mathematics', level: 'o_level', unit: 'Number', chapter: 'Percentages', topic: 'Increase/decrease', atom: 'Percentage increase: new = original × (1 + r/100). Percentage decrease: new = original × (1 - r/100). Reverse: original = new / multiplier.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_number_ratio', subject: 'mathematics', level: 'o_level', unit: 'Number', chapter: 'Ratio', topic: 'Dividing in ratio', atom: 'To divide amount in ratio a:b: total parts = a+b. Each share = (part/total) × amount.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_number_bounds', subject: 'mathematics', level: 'o_level', unit: 'Number', chapter: 'Bounds', topic: 'Upper and lower', atom: 'Upper bound: measured value + half the precision. Lower bound: value - half. E.g., 5.3 cm (to 1dp): LB=5.25, UB=5.35', difficulty: 3, examWeight: 'high', relatedAtoms: [] },

  // Algebra
  { id: 'math_algebra_indices_laws', subject: 'mathematics', level: 'o_level', unit: 'Algebra', chapter: 'Indices', topic: 'Laws', atom: 'Laws of indices: aᵐ × aⁿ = aᵐ⁺ⁿ, aᵐ ÷ aⁿ = aᵐ⁻ⁿ, (aᵐ)ⁿ = aᵐⁿ, a⁰ = 1, a⁻ⁿ = 1/aⁿ, a^(1/n) = ⁿ√a', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_algebra_expand_brackets', subject: 'mathematics', level: 'o_level', unit: 'Algebra', chapter: 'Expressions', topic: 'Expanding', atom: 'Expanding double brackets: (a+b)(c+d) = ac + ad + bc + bd. Use FOIL: First, Outer, Inner, Last.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_algebra_factorise_common', subject: 'mathematics', level: 'o_level', unit: 'Algebra', chapter: 'Factorisation', topic: 'Common factor', atom: 'Factorising by common factor: 6x² + 9x = 3x(2x + 3). Take out the highest common factor.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_algebra_factorise_quadratic', subject: 'mathematics', level: 'o_level', unit: 'Algebra', chapter: 'Factorisation', topic: 'Quadratics', atom: 'Factorising x² + bx + c: find two numbers that multiply to c and add to b. E.g., x² + 5x + 6 = (x+2)(x+3)', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_algebra_quadratic_formula', subject: 'mathematics', level: 'o_level', unit: 'Algebra', chapter: 'Quadratics', topic: 'Formula', atom: 'Quadratic formula: x = (-b ± √(b²-4ac)) / 2a for ax² + bx + c = 0. Used when factorisation is not possible.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_algebra_completing_square', subject: 'mathematics', level: 'o_level', unit: 'Algebra', chapter: 'Quadratics', topic: 'Completing square', atom: 'Completing the square: x² + bx = (x + b/2)² - (b/2)². Useful for finding turning point of parabola.', difficulty: 4, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_algebra_discriminant', subject: 'mathematics', level: 'o_level', unit: 'Algebra', chapter: 'Quadratics', topic: 'Discriminant', atom: 'Discriminant = b² - 4ac. If > 0: two real roots. If = 0: one repeated root. If < 0: no real roots.', difficulty: 4, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_algebra_simultaneous_linear', subject: 'mathematics', level: 'o_level', unit: 'Algebra', chapter: 'Simultaneous equations', topic: 'Linear', atom: 'Solve simultaneous equations by elimination (make coefficients equal, add/subtract) or substitution (express one variable in terms of other).', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_algebra_inequality', subject: 'mathematics', level: 'o_level', unit: 'Algebra', chapter: 'Inequalities', topic: 'Solving', atom: 'Solve inequalities like equations BUT reverse the inequality sign when multiplying/dividing by a negative number.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_algebra_sequences_nth', subject: 'mathematics', level: 'o_level', unit: 'Algebra', chapter: 'Sequences', topic: 'nth term', atom: 'Linear sequence nth term: an + b where a = common difference. E.g., 3,7,11,15: common diff = 4, nth term = 4n - 1', difficulty: 3, examWeight: 'high', relatedAtoms: [] },

  // Geometry
  { id: 'math_geom_angle_triangle', subject: 'mathematics', level: 'o_level', unit: 'Geometry', chapter: 'Angles', topic: 'Triangle angles', atom: 'Angles in a triangle sum to 180°. Equilateral: all 60°. Isosceles: two equal. Right-angled: one 90°.', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_geom_parallel_lines', subject: 'mathematics', level: 'o_level', unit: 'Geometry', chapter: 'Angles', topic: 'Parallel lines', atom: 'Parallel lines: alternate angles equal (Z-shape), corresponding angles equal (F-shape), co-interior angles sum to 180° (C-shape)', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_geom_circle_theorems', subject: 'mathematics', level: 'o_level', unit: 'Geometry', chapter: 'Circle theorems', topic: 'Key theorems', atom: 'Angle at centre = 2× angle at circumference. Angle in semicircle = 90°. Angles in same segment equal. Opposite angles in cyclic quad = 180°.', difficulty: 4, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_geom_pythagoras', subject: 'mathematics', level: 'o_level', unit: 'Geometry', chapter: 'Pythagoras', topic: 'Theorem', atom: 'Pythagoras: a² + b² = c² where c is the hypotenuse. Only for right-angled triangles.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_geom_similar_triangles', subject: 'mathematics', level: 'o_level', unit: 'Geometry', chapter: 'Similarity', topic: 'Scale factors', atom: 'Similar shapes: same shape, different size. Linear SF = k, area SF = k², volume SF = k³.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },

  // Trigonometry
  { id: 'math_trig_sohcahtoa', subject: 'mathematics', level: 'o_level', unit: 'Trigonometry', chapter: 'Right-angle trig', topic: 'Ratios', atom: 'SOH CAH TOA: sin θ = opposite/hypotenuse, cos θ = adjacent/hypotenuse, tan θ = opposite/adjacent', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_trig_sine_rule', subject: 'mathematics', level: 'o_level', unit: 'Trigonometry', chapter: 'Non-right triangles', topic: 'Sine rule', atom: 'Sine rule: a/sin A = b/sin B = c/sin C. Used when you have a pair of opposite side and angle.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_trig_cosine_rule', subject: 'mathematics', level: 'o_level', unit: 'Trigonometry', chapter: 'Non-right triangles', topic: 'Cosine rule', atom: 'Cosine rule: a² = b² + c² - 2bc cos A. Used when you have SAS (two sides + included angle) or SSS (three sides).', difficulty: 3, examWeight: 'high', relatedAtoms: [] },

  // Statistics
  { id: 'math_stats_mean', subject: 'mathematics', level: 'o_level', unit: 'Statistics', chapter: 'Averages', topic: 'Mean', atom: 'Mean = sum of all values / number of values. For frequency table: mean = Σfx / Σf', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_stats_median', subject: 'mathematics', level: 'o_level', unit: 'Statistics', chapter: 'Averages', topic: 'Median', atom: 'Median: middle value when data arranged in order. For n values: position = (n+1)/2. For grouped data: use cumulative frequency graph.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_stats_cumulative_freq', subject: 'mathematics', level: 'o_level', unit: 'Statistics', chapter: 'Cumulative frequency', topic: 'Reading', atom: 'Cumulative frequency curve: plot at upper class boundary. Read median at n/2, LQ at n/4, UQ at 3n/4. IQR = UQ - LQ.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_stats_histogram', subject: 'mathematics', level: 'o_level', unit: 'Statistics', chapter: 'Histograms', topic: 'Frequency density', atom: 'Histogram: frequency density = frequency / class width. Area of bar represents frequency (NOT height).', difficulty: 4, examWeight: 'high', relatedAtoms: [] },

  // Probability
  { id: 'math_prob_basic', subject: 'mathematics', level: 'o_level', unit: 'Probability', chapter: 'Basic', topic: 'Definition', atom: 'P(event) = number of favourable outcomes / total number of possible outcomes. Always between 0 and 1.', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_prob_tree', subject: 'mathematics', level: 'o_level', unit: 'Probability', chapter: 'Tree diagrams', topic: 'Rules', atom: 'Tree diagrams: multiply along branches (AND), add between branches (OR). P(A and B) = P(A) × P(B) if independent.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },

  // Calculus
  { id: 'math_calc_differentiate', subject: 'mathematics', level: 'o_level', unit: 'Calculus', chapter: 'Differentiation', topic: 'Power rule', atom: 'Differentiation power rule: if y = axⁿ then dy/dx = naxⁿ⁻¹. Gives the gradient function.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_calc_stationary', subject: 'mathematics', level: 'o_level', unit: 'Calculus', chapter: 'Differentiation', topic: 'Stationary points', atom: 'Stationary points: where dy/dx = 0. Maximum: d²y/dx² < 0. Minimum: d²y/dx² > 0.', difficulty: 4, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_calc_integrate', subject: 'mathematics', level: 'o_level', unit: 'Calculus', chapter: 'Integration', topic: 'Power rule', atom: 'Integration power rule: ∫axⁿ dx = ax^(n+1)/(n+1) + C. Reverse of differentiation. +C for indefinite integrals.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_calc_area_under', subject: 'mathematics', level: 'o_level', unit: 'Calculus', chapter: 'Integration', topic: 'Area under curve', atom: 'Area under curve between x=a and x=b: ∫ₐᵇ y dx. Definite integral — no +C needed. Negative area below x-axis.', difficulty: 4, examWeight: 'high', relatedAtoms: [] },

  // Vectors
  { id: 'math_vectors_column', subject: 'mathematics', level: 'o_level', unit: 'Vectors', chapter: 'Basics', topic: 'Column vectors', atom: 'Column vector (x,y): x = horizontal displacement, y = vertical displacement. Magnitude = √(x² + y²).', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'math_vectors_addition', subject: 'mathematics', level: 'o_level', unit: 'Vectors', chapter: 'Operations', topic: 'Addition', atom: 'Vector addition: add corresponding components. a + b = (x₁+x₂, y₁+y₂). Head-to-tail on diagram.', difficulty: 2, examWeight: 'medium', relatedAtoms: [] },
];

// ── ECONOMICS A LEVEL (9708) — 120 atoms ──────────────────────

const ECONOMICS_ATOMS = [
  { id: 'econ_basic_scarcity', subject: 'economics', level: 'a_level', unit: 'Basic Economic Problem', chapter: 'Scarcity', topic: 'Definition', atom: 'Scarcity: unlimited wants but limited resources. Forces choice. Creates opportunity cost.', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'econ_basic_opp_cost', subject: 'economics', level: 'a_level', unit: 'Basic Economic Problem', chapter: 'Opportunity cost', topic: 'Definition', atom: 'Opportunity cost: the next best alternative forgone when a choice is made. Not all alternatives — just the NEXT best.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'econ_basic_ppf', subject: 'economics', level: 'a_level', unit: 'Basic Economic Problem', chapter: 'PPC', topic: 'Production possibility curve', atom: 'PPC shows maximum output combinations. Points on curve = efficient. Inside = inefficient. Outside = unattainable (without growth).', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'econ_demand_law', subject: 'economics', level: 'a_level', unit: 'Microeconomics', chapter: 'Demand', topic: 'Law of demand', atom: 'Law of demand: ceteris paribus, as price rises, quantity demanded falls (and vice versa). Inverse relationship.', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'econ_demand_shift', subject: 'economics', level: 'a_level', unit: 'Microeconomics', chapter: 'Demand', topic: 'Shifts', atom: 'Demand curve shifts due to: income, tastes, population, price of substitutes/complements, advertising. NOT price of the good itself.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'econ_demand_ped', subject: 'economics', level: 'a_level', unit: 'Microeconomics', chapter: 'Elasticity', topic: 'PED', atom: 'PED = % change in Qd / % change in P. Always negative. |PED| > 1 = elastic, < 1 = inelastic, = 1 = unit elastic.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'econ_supply_law', subject: 'economics', level: 'a_level', unit: 'Microeconomics', chapter: 'Supply', topic: 'Law of supply', atom: 'Law of supply: ceteris paribus, as price rises, quantity supplied rises. Positive relationship.', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'econ_equilibrium', subject: 'economics', level: 'a_level', unit: 'Microeconomics', chapter: 'Market', topic: 'Equilibrium', atom: 'Market equilibrium: where demand = supply. Equilibrium price and quantity. Excess supply → price falls. Excess demand → price rises.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'econ_market_failure', subject: 'economics', level: 'a_level', unit: 'Microeconomics', chapter: 'Market failure', topic: 'Definition', atom: 'Market failure: when free market leads to misallocation of resources. Causes: externalities, public goods, merit/demerit goods, monopoly, information failure.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'econ_externalities', subject: 'economics', level: 'a_level', unit: 'Microeconomics', chapter: 'Market failure', topic: 'Externalities', atom: 'Externalities: costs/benefits to third parties not reflected in price. Negative (pollution), positive (education). MSC ≠ MPC or MSB ≠ MPB.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'econ_gdp_def', subject: 'economics', level: 'a_level', unit: 'Macroeconomics', chapter: 'GDP', topic: 'Definition', atom: 'GDP: total value of goods and services produced in a country in one year. Real GDP adjusted for inflation. GDP per capita = GDP / population.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'econ_inflation_def', subject: 'economics', level: 'a_level', unit: 'Macroeconomics', chapter: 'Inflation', topic: 'Definition', atom: 'Inflation: sustained increase in general price level over time. Measured by CPI. Demand-pull (too much AD) or cost-push (rising costs).', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'econ_unemployment_types', subject: 'economics', level: 'a_level', unit: 'Macroeconomics', chapter: 'Unemployment', topic: 'Types', atom: 'Types: frictional (between jobs), structural (skills mismatch), cyclical (recession), seasonal. Natural rate = frictional + structural.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'econ_monetary_policy', subject: 'economics', level: 'a_level', unit: 'Macroeconomics', chapter: 'Monetary policy', topic: 'Tools', atom: 'Monetary policy: central bank uses interest rates, money supply, QE to control inflation and stimulate growth. Lower rates → more borrowing → more AD.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'econ_fiscal_policy', subject: 'economics', level: 'a_level', unit: 'Macroeconomics', chapter: 'Fiscal policy', topic: 'Tools', atom: 'Fiscal policy: government uses taxation and spending to influence AD. Expansionary = cut taxes/increase spending. Contractionary = opposite.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'econ_trade_comparative', subject: 'economics', level: 'a_level', unit: 'International Trade', chapter: 'Trade theory', topic: 'Comparative advantage', atom: 'Comparative advantage: a country should specialise in producing goods with lowest opportunity cost. Both countries benefit from trade even if one is more efficient at everything.', difficulty: 4, examWeight: 'high', relatedAtoms: [] },
  { id: 'econ_exchange_rates', subject: 'economics', level: 'a_level', unit: 'International Trade', chapter: 'Exchange rates', topic: 'Systems', atom: 'Floating: determined by supply/demand for currency. Fixed: pegged by central bank. Managed float: mostly floating with intervention.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'econ_bop', subject: 'economics', level: 'a_level', unit: 'International Trade', chapter: 'Balance of payments', topic: 'Components', atom: 'Balance of payments: current account (trade in goods/services + transfers) + capital/financial account. Must balance overall.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
];

// ── ENGLISH LANGUAGE O LEVEL (1123) — 100 atoms ──────────────

const ENGLISH_ATOMS = [
  // Reading Comprehension
  { id: 'eng_read_explicit', subject: 'english', level: 'o_level', unit: 'Reading Comprehension', chapter: 'Skills', topic: 'Explicit information', atom: 'Explicit information: directly stated in the text. Find key words in the question, locate them in the passage, extract the answer.', difficulty: 1, examWeight: 'high', relatedAtoms: [] },
  { id: 'eng_read_implicit', subject: 'english', level: 'o_level', unit: 'Reading Comprehension', chapter: 'Skills', topic: 'Implicit meaning', atom: 'Implicit meaning: not directly stated but suggested. Reader must infer from context, connotation, and tone. "The text suggests..." or "This implies..."', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'eng_read_own_words', subject: 'english', level: 'o_level', unit: 'Reading Comprehension', chapter: 'Skills', topic: 'Own words', atom: '"In your own words" means paraphrase — do NOT lift text. Find synonyms for key words. Lifting = 0 marks.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'eng_read_writers_effect', subject: 'english', level: 'o_level', unit: 'Reading Comprehension', chapter: 'Language analysis', topic: 'Writer\'s effect', atom: 'Writer\'s effect questions: identify technique → quote → explain specific effect on reader. "The writer uses X to create a sense of Y because Z."', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'eng_read_connotation', subject: 'english', level: 'o_level', unit: 'Reading Comprehension', chapter: 'Language analysis', topic: 'Connotation', atom: 'Connotation: associated meaning beyond literal definition. "Slender" vs "skinny" — same meaning, different connotations (positive vs negative).', difficulty: 3, examWeight: 'high', relatedAtoms: [] },

  // Summary
  { id: 'eng_summary_selection', subject: 'english', level: 'o_level', unit: 'Summary Skills', chapter: 'Content', topic: 'Point selection', atom: 'Summary: identify relevant content points from the passage. One mark per distinct point. Typically 15 points available, select best ones.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'eng_summary_paraphrase', subject: 'english', level: 'o_level', unit: 'Summary Skills', chapter: 'Language', topic: 'Paraphrasing', atom: 'Summary language marks: paraphrase fluently in own words. Use synonyms. Do NOT copy phrases directly. Concise — no unnecessary repetition.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'eng_summary_word_limit', subject: 'english', level: 'o_level', unit: 'Summary Skills', chapter: 'Format', topic: 'Word limit', atom: 'Summary word limit: usually ~160 words. Content beyond word limit is not marked. One continuous paragraph. No bullet points.', difficulty: 1, examWeight: 'high', relatedAtoms: [] },

  // Directed Writing
  { id: 'eng_directed_format', subject: 'english', level: 'o_level', unit: 'Directed Writing', chapter: 'Format', topic: 'Text types', atom: 'Directed writing formats: letter (formal/informal), report (headings, formal), speech (direct address, rhetorical), article (headline, engaging). Format marks available.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },
  { id: 'eng_directed_register', subject: 'english', level: 'o_level', unit: 'Directed Writing', chapter: 'Register', topic: 'Matching', atom: 'Register must match purpose and audience. Formal report ≠ informal letter. Speech to peers ≠ speech to governors. Wrong register = marks lost.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'eng_directed_bullet_points', subject: 'english', level: 'o_level', unit: 'Directed Writing', chapter: 'Content', topic: 'Bullet points', atom: 'Address ALL bullet points in the question. Each must be developed (not just mentioned). Missing a bullet point = missing content marks.', difficulty: 2, examWeight: 'high', relatedAtoms: [] },

  // Composition
  { id: 'eng_comp_narrative_structure', subject: 'english', level: 'o_level', unit: 'Composition', chapter: 'Narrative', topic: 'Structure', atom: 'Narrative structure: engaging opening → rising action → climax → resolution. Start in medias res for impact. Avoid "I woke up..."', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'eng_comp_descriptive', subject: 'english', level: 'o_level', unit: 'Composition', chapter: 'Descriptive', topic: 'Sensory detail', atom: 'Descriptive writing: use all 5 senses (sight, sound, smell, touch, taste). Show don\'t tell. "The floor was cold" → "The tiles bit into her bare feet."', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'eng_comp_sentence_variety', subject: 'english', level: 'o_level', unit: 'Composition', chapter: 'Technique', topic: 'Sentence variety', atom: 'Sentence variety: mix simple, compound, complex sentences. Short for impact. Long for description. Varied openers: adverb, participle, time.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
  { id: 'eng_comp_argumentative', subject: 'english', level: 'o_level', unit: 'Composition', chapter: 'Argumentative', topic: 'Structure', atom: 'Argumentative: clear thesis → point 1 + evidence → point 2 + evidence → counter-argument → rebuttal → conclusion. Must have both sides for top marks.', difficulty: 3, examWeight: 'high', relatedAtoms: [] },
];

// ═══════════════════════════════════════════════════════════════
// COMBINED DATABASE + HELPER FUNCTIONS
// ═══════════════════════════════════════════════════════════════

const STARKY_ATOMS = [
  ...CHEMISTRY_ATOMS,
  ...PHYSICS_ATOMS,
  ...BIOLOGY_ATOMS,
  ...MATHS_ATOMS,
  ...ECONOMICS_ATOMS,
  ...ENGLISH_ATOMS,
];

const ATOM_COUNTS = {
  chemistry: CHEMISTRY_ATOMS.length,
  physics: PHYSICS_ATOMS.length,
  biology: BIOLOGY_ATOMS.length,
  mathematics: MATHS_ATOMS.length,
  economics: ECONOMICS_ATOMS.length,
  english: ENGLISH_ATOMS.length,
  total: STARKY_ATOMS.length,
};

function getAtomsBySubject(subject) {
  const lower = (subject || '').toLowerCase();
  return STARKY_ATOMS.filter(a => a.subject === lower || a.subject.includes(lower) || lower.includes(a.subject));
}

function getAtomsByUnit(subject, unit) {
  return getAtomsBySubject(subject).filter(a => a.unit === unit);
}

function getAtomsByDifficulty(subject, difficulty) {
  return getAtomsBySubject(subject).filter(a => a.difficulty === difficulty);
}

function getExamWeightAtoms(subject, weight) {
  return getAtomsBySubject(subject).filter(a => a.examWeight === weight);
}

function getAtomById(atomId) {
  return STARKY_ATOMS.find(a => a.id === atomId) || null;
}

module.exports = {
  STARKY_ATOMS,
  ATOM_COUNTS,
  CHEMISTRY_ATOMS,
  PHYSICS_ATOMS,
  BIOLOGY_ATOMS,
  MATHS_ATOMS,
  ECONOMICS_ATOMS,
  ENGLISH_ATOMS,
  getAtomsBySubject,
  getAtomsByUnit,
  getAtomsByDifficulty,
  getExamWeightAtoms,
  getAtomById,
};
