#!/bin/bash
# Auto-generate SESSION.md on session end.
# Captures: what changed this session, recent commits, uncommitted state.
# Called by Stop hook in each project. Zero manual work required.

cd "$(git rev-parse --show-toplevel 2>/dev/null || echo ".")"

[ -d .git ] || exit 0
mkdir -p .claude

NOW=$(date '+%Y-%m-%d %H:%M')
PROJECT=$(basename "$(pwd)")

# Files modified in this session (uncommitted)
UNCOMMITTED=$(git status --short 2>/dev/null)

# What's been pushed today
TODAY_COMMITS=$(git log --since="$(date '+%Y-%m-%d') 00:00" --oneline 2>/dev/null)
TODAY_COUNT=$(echo "$TODAY_COMMITS" | grep -c "^[a-f0-9]" || echo 0)

# Recent commits regardless of date (last 5)
RECENT=$(git log --oneline -5 2>/dev/null)

# Files changed in last commit
LAST_FILES=$(git diff HEAD~1 --name-only 2>/dev/null | head -10)

# Branch + remote status
BRANCH=$(git branch --show-current 2>/dev/null)
AHEAD=$(git rev-list --count @{u}..HEAD 2>/dev/null || echo "?")
BEHIND=$(git rev-list --count HEAD..@{u} 2>/dev/null || echo "?")

cat > .claude/SESSION.md <<EOF
# Session handover — ${PROJECT}
**Generated:** ${NOW}

## Current state
- **Branch:** ${BRANCH}
- **Ahead of remote:** ${AHEAD} commits
- **Behind remote:** ${BEHIND} commits
- **Today's pushes:** ${TODAY_COUNT}

## Uncommitted changes
${UNCOMMITTED:-_(working tree clean)_}

## Today's commits
\`\`\`
${TODAY_COMMITS:-(no commits today)}
\`\`\`

## Last 5 commits (any date)
\`\`\`
${RECENT}
\`\`\`

## Files in last commit
\`\`\`
${LAST_FILES}
\`\`\`

## Where to resume
Look at uncommitted changes above. If clean, the project is at a stable point — last commit is the resume point.

---
_Auto-generated by .claude Stop hook. Update install: \`bash /Users/khurramb/projects/newworld-platform/scripts/install-cost-discipline.sh\`_
EOF

# Quiet success — no system message needed (the Stop hook chain already prints CLAUDE.md sync)
exit 0
